In [15]:
import html_processor
import project_name_tagger
import resource_table_extractor
import table_processor
import classifier
importlib.reload(html_processor)
importlib.reload(project_name_tagger)
importlib.reload(resource_table_extractor)
importlib.reload(table_processor)
importlib.reload(classifier)

{'category': {'indicated': {'indicated', 'i', 'ind'},
              'inferred': {'inf', 'inferred', 'infe'},
              'meas_ind': {'m & i',
                           'm + i',
                           'm / i',
                           'm&i',
                           'm+i',
                           'm/i',
                           'meas & ind',
                           'meas / ind',
                           'meas ind',
                           'meas&ind',
                           'meas-ind',
                           'meas/ind',
                           'meas_ind',
                           'measured & indicated',
                           'measured and indicated',
                           'mi'},
              'measured': {'m', 'meas', 'measured'},
              'probable': {'prob', 'probable', 'proba'},
              'prov_prob': {'p & p',
                            'p + p',
                            'p / p',
                            'p&p',
                            'p/p',
                            'prov / prob',
                            'prov prob',
                            'prov-prob',
                            'prov/prob',
                            'prov_prob',
                            'proven & probable',
                            'proven + probable',
                            'proven / probable',
                            'proven/probable'},
              'proven': {'proven', 'prov'}},
 'commodity': {'3pge': {'3pge', 'pd+pt+au'},
               'altered ilmenite': {'altered ilmenite'},
               'aluminous clay': {'aluminous clay'},
               'aluminum': {'aluminum', 'al'},
               'aluminum oxide (alumina)': {'al2o3',
                                            'alumina',
                                            'aluminum oxide'},
               'alumnium': {'alumnium'},
               'alunite': {'alunite', 'aln'},
               'alunite al2o3': {'alunite', 'al2o3', 'alua'},
               'alunite k2o': {'aluk', 'alunite k2o'},
               'anatase': {'tio2', 'anatase'},
               'antimony': {'antimony', 'sb'},
               'antimony oxide': {'sb2o3', 'antimony oxide'},
               'arsenic': {'arsenic', 'as'},
               'asbestos': {'asbestos', 'ab'},
               'barite': {'barite', 'baso4'},
               'barium': {'ba', 'barium'},
               'bauxite (al2o3)': {'al2o3', 'bauxite', 'bx'},
               'beryl': {'beryl', 'brl'},
               'beryllium': {'be', 'beryllium'},
               'bismuth': {'bismuth', 'bi'},
               'borate': {'bor', 'borate'},
               'boron': {'boron', 'b'},
               'bromine': {'br', 'bromine'},
               'cadmium': {'cd', 'cadmium'},
               'celestine': {'clt', 'celestine'},
               'cerium': {'cerium', 'ce'},
               'cerium ( iii ) oxide ce2o3': {'ce2o3', 'cerium iii'},
               'cerium ( iv ) oxide ceo2': {'cerium iv', 'ceo2'},
               'cesium': {'cesium', 'cs'},
               'cesium oxide': {'cesium oxide', 'cs2o'},
               'chromite': {'chromite', 'cr2o3'},
               'chromium': {'chromium', 'cr'},
               'coal': {'coal', 'c'},
               'coal - bituminous': {'bituminous'},
               'coal - metallurgical/coking': {'coking', 'metallurgical'},
               'coal - metallurgical/pci': {'metallurgical', 'pci'},
               'coal- thermal/steam': {'thermal', 'steam'},
               'cobalt': {'co', 'cobalt'},
               'copper': {'copper', 'cu'},
               'diamond': {'diamond', 'di'},
               'diatomite': {'diatomite', 'diat'},
               'dolomite': {'dolomite', 'dol'},
               'dysprosium': {'dy', 'dysprosium'},
               'dysprosium oxide dy2o3': {'dysprosium oxide', 'dy2o3'},
               'emerald': {'emerald'},
               'erbium': {'er', 'erbium'},
               'erbium oxide er2o3': {'er2o3', 'erbium oxide'},
               'europium': {'europium', 'eu'},
               'europium oxide eu2o3': {'europium oxide', 'eu2o3'},
               'ferric oxide fe2o3': {'fe2o3', 'ferric oxide'},
               'ferrochrome': {'ferrochrome'},
               'ferrous oxide feo': {'ferrous oxide', 'feo'},
               'fluorite': {'flr', 'fluorite'},
               'fluorspar': {'fluorspar', 'caf2'},
               'frac sand': {'sio2', 'frac sand'},
               'gadolinium': {'gadolinium', 'gd'},
               'gadolinium oxide gd2o3': {'gadolinium oxide', 'gd2o3'},
               'gallium': {'ga', 'gallium'},
               'garnet': {'grt', 'garnet'},
               'gemstones': {'gem', 'gemstones'},
               'germanium': {'germanium', 'ge'},
               'gold': {'au', 'gold'},
               'gold eq.': {'gold eq.'},
               'graphite': {'graphite', 'gr'},
               'gypsum': {'gypsum', 'gp'},
               'hafnium': {'hfo2', 'hafnium'},
               'heavy mineral sands': {'hms', 'heavy mineral sands'},
               'heavy rare earth oxides': {'hreo', 'heavy rare earth oxides'},
               'hi-ti ( hi-ty )': {'hi ty', 'hi ti'},
               'hi-ti imenite': {'hi-ti imenite'},
               'hi-ti leucoxene': {'hi-ti leucoxene'},
               'hi-ti rutile': {'hi-ti rutile'},
               'holmium': {'holmium', 'ho'},
               'holmium oxide ho2o3': {'ho2o3', 'holmium oxide'},
               'ilmenite': {'fetio3', 'ilmenite'},
               'indium': {'in', 'indium'},
               'iodine': {'iodine'},
               'iridium': {'ir', 'iridium'},
               'iron': {'iron', 'fe'},
               'iron ore': {'iron ore'},
               'iron oxide': {'fe2o3', 'iron oxide'},
               'iron sands': {'fe3o4', 'iron sands'},
               'jade': {'jad', 'jade'},
               'kaolin': {'kn', 'kaolin'},
               'kyanite': {'al2sio6', 'kyanite'},
               'lanthanum': {'la', 'lanthanum'},
               'lanthanum oxide la2o3': {'lanthanum oxide', 'la2o3'},
               'lead': {'pb', 'lead'},
               'leucoxene': {'fetio3', 'leucoxene'},
               'light rare earth elements': {'light rare earth elements',
                                             'lree'},
               'light rare earth oxides': {'lreo', 'light rare earth oxides'},
               'limestone': {'lst', 'limestone'},
               'lithium': {'lithium', 'li'},
               'lithium (lce)': {'lce', 'lithium (lce)'},
               'lithium oxide (li2o)': {'lithium oxide', 'li2o'},
               'lutetium': {'lu', 'lutetium'},
               'lutetium oxide lu2o3': {'lu2o3', 'lutetium oxide'},
               'magnesite': {'mgs', 'magnesite'},
               'magnesium': {'magnesium', 'mg'},
               'magnesium oxide': {'mgo', 'magnesium oxide'},
               'magnetic hm': {'mag1', 'magnetic hm'},
               'magnetite': {'magnetite', 'mag'},
               'manganese': {'manganese', 'mn'},
               'manganese carbonate': {'manganese carbonate'},
               'mercury': {'hg', 'mercury'},
               'mica': {'mca', 'mica'},
               'molybdenum': {'molybdenum', 'mo'},
               'monazite': {'mnz', 'monazite'},
               'neodymium': {'nd', 'neodymium'},
               'neodymium oxide nd2o3': {'neodymium oxide', 'nd2o3'},
               'nickel': {'nickel', 'ni'},
               'niobium': {'niobium', 'nb'},
               'niobium oxide': {'niobium oxide', 'nb2o5'},
               'nitrate': {'nit', 'nitrate'},
               'opal': {'opal', 'opl'},
               'osmium': {'osmium', 'os'},
               'palladium': {'pd', 'palladium'},
               'perlite': {'prl', 'perlite'},
               'pge 2e': {'pge 2e', 'pt+pd'},
               'pge 3e': {'pt+pd+au', 'pge 3e'},
               'pge 4e': {'pge 4e', 'pt+pd+rh+au'},
               'pge 6e': {'pt+pd+rh+ru+ir+au', 'pge 6e'},
               'pge 7e': {'pt+pd+rh+ru+ir+os+au', 'pge 7e'},
               'phosphate': {'p', 'phosphate'},
               'phosphorus oxide': {'p2o5', 'phosphorus oxide'},
               'platinum': {'platinum', 'pt'},
               'platinum group elements': {'pge', 'platinum group elements'},
               'potash': {'pot', 'potash'},
               'potash (sop_k2so4)': {'k2so4', 'sop_k2so4', 'potash'},
               'potash k2o': {'k2o', 'potash'},
               'potash kcl': {'kcl', 'potash kcl'},
               'praseodymium': {'pr', 'praseodymium'},
               'praseodymium ( iii ) oxide pr2o3': {'pr2o3',
                                                    'praseodymium iii'},
               'praseodymium ( iii,iv ) oxide pr6o11': {'pr6o11',
                                                        'praseodymium iii iv'},
               'pyrite': {'pyrite'},
               'pyrophyllite': {'pyrophyllite', 'pyro'},
               'rare earth + yttrium oxide': {'rare earth + yttrium oxide',
                                              'treo-y'},
               'rare earth elements': {'ree', 'rare earth elements'},
               'rhenium': {'re', 'rhenium'},
               'rhodium': {'rh', 'rhodium'},
               'rubidium': {'rubidium', 'rb'},
               'ruby': {'ruby'},
               'ruthenium': {'ruthenium', 'ru'},
               'rutile': {'rutile', 'tio2'},
               'salt': {'salt', 'nacl'},
               'samarium': {'samarium', 'sm'},
               'samarium oxide sm2o3': {'sm2o3', 'samarium oxide'},
               'sapphire': {'sapphire'},
               'scandium': {'sc', 'scandium'},
               'scandium oxide': {'scandium oxide', 'sc2o3'},
               'selenium': {'se', 'selenium'},
               'si tiox ( siliceous ti-oxide )': {'si tiox',
                                                  'siliceous ti-oxide'},
               'silica': {'sio2', 'silica'},
               'silica sand': {'silica sand', 'si'},
               'silver': {'ag', 'silver'},
               'silver eq.': {'silver eq'},
               'sodium': {'na', 'sodium'},
               'sodium carbonate (soda ash)': {'sodium carbonate', 'soda ash'},
               'sodium oxide': {'na2o', 'sodium oxide'},
               'soluble\xa0copper scu': {'soluble\xa0copper', 'scu'},
               'staurolite': {'fe mg 2al9 si al 4o20 o oh 4', 'staurolite'},
               'strontium': {'strontium', 'sr'},
               'sulfur': {'s', 'sulfur'},
               'talc': {'tc', 'talc'},
               'tantalum': {'tantalum', 'ta'},
               'tantalum pentoxide': {'tantalum pentoxide', 'ta2o5'},
               'tanzanite': {'tanzanite'},
               'tellurium': {'te', 'tellurium'},
               'terbium': {'tb', 'terbium'},
               'terbium ( iii ) oxide tb2o3': {'tb4o7', 'terbium iii'},
               'terbium ( iii, iv ) oxide tb4o7': {'tb4o7', 'terbium iii iv'},
               'thorium': {'th', 'thorium'},
               'thorium oxide': {'thorium oxide', 'tho2'},
               'thulium': {'thulium', 'tm'},
               'thulium oxide tm2o3': {'thulium oxide', 'tm2o3'},
               'tin': {'tin', 'sn'},
               'titanium': {'titanium', 'ti'},
               'titanium oxide': {'tio2', 'titanium oxide'},
               'titanomagnetite': {'titanomagnetite', 'timag'},
               'total rare earth elements': {'total rare earth elements',
                                             'tree'},
               'total rare earth oxide': {'treo', 'total rare earth oxide'},
               'trona': {'trona'},
               'tungsten': {'tungsten', 'w'},
               'tungsten trioxide': {'tungsten trioxide', 'wo3'},
               'uranium': {'uranium', 'u'},
               'uranium oxide': {'u3o8', 'uranium oxide'},
               'valuable heavy minerals': {'valuable heavy minerals'},
               'vanadium': {'v', 'vanadium'},
               'vanadium oxide': {'vanadium oxide', 'v2o5'},
               'xenotime': {'xenotime', 'ypo4'},
               'ytterbium': {'ytterbium', 'yb2o3'},
               'ytterbium oxide yb2o3': {'yb2o3', 'ytterbium oxide'},
               'yttrium': {'yttrium', 'y'},
               'yttrium oxide y2o3': {'y2o3', 'yttrium oxide'},
               'zeolite': {'zeo', 'zeolite'},
               'zinc': {'zinc', 'zn'},
               'zircon': {'zircon', 'zrsio4'},
               'zirconium': {'zr', 'zirconium'},
               'zirconium dioxide': {'zro2', 'zirconium dioxide'}},
 'measurement': {'%': {'%'},
                 'carat': {'carat'},
                 'carats/sq metre': {'carats/sq metre'},
                 'cpht': {'cpht'},
                 'cpt': {'cpt'},
                 'ct/100 cu m': {'ct/100 cu m'},
                 'ct/cu m': {'ct/cu m'},
                 'cubic km': {'cubic km'},
                 'cubic metre': {'cubic metre'},
                 'cubic yard': {'cubic yard'},
                 'flask': {'flask'},
                 'g/cu m': {'g/cu m'},
                 'g/t': {'g/t'},
                 'gram': {'gram'},
                 'kct': {'kct'},
                 'kg': {'kg'},
                 'koz': {'koz'},
                 'kt': {'kt'},
                 'lb': {'lb'},
                 'ltu': {'ltu'},
                 'mg/l': {'mg/l'},
                 'mtu': {'mtu'},
                 'oz': {'oz'},
                 'oz/cu yd': {'oz/cu yd'},
                 'oz/ton': {'oz/ton'},
                 'ppb': {'ppb'},
                 'ppm': {'ppm'},
                 'sq metre': {'sq metre'},
                 'stu': {'stu'},
                 't': {'t'},
                 'ton': {'ton'},
                 'wet t': {'wet t'},
                 'wet tons': {'wet tons'}},
 'metric': {'contained': {'metal', 'contained', 'content', 'cont'},
            'grade': {'grade', 'avg', 'average'},
            'tonnage': {'ton', 'tonnage', 'tonn', 'tons', 'tonnes'}},
 'minetype': {'brine/salar': {'salar', 'brine'},
              'in circuit': {'in-circuit', 'in circuit'},
              'in-situ': {'in situ', 'insitu', 'in-situ'},
              'ocean': {'ocean'},
              'open cast (strip mining)': {'open cast',
                                           'open-cast',
                                           'strip mining',
                                           'strip-mining'},
              'open pit': {'op', 'open pit', 'open-pit'},
              'placer': {'placer'},
              'stockpile': {'stockpile', 'sp', 'stockpiles'},
              'surface (other)': {'surface'},
              'tailings': {'tailings'},
              'underground': {'ug', 'underground'},
              'underground access': {'underground access'}},
 'oretype': {'alloy': {'alloy'},
             'carbonate': {'carbonate'},
             'chloride': {'chloride'},
             'fluorides': {'fluorides'},
             'liquid': {'liquid'},
             'native element': {'native element'},
             'nitrate': {'nitrate'},
             'oxide': {'oxide'},
             'oxide + sulphide': {'oxide+sulphide', 'oxide + sulphide'},
             'oxide+transitional': {'oxide + transitional',
                                    'oxide+transitional'},
             'phosphates': {'phosphates'},
             'refractory': {'refractory'},
             'silicate': {'silicate'},
             'sulphates': {'sulphates'},
             'sulphide': {'sulphide'},
             'sulphide+transitional': {'sulphide + transitional',
                                       'sulphide+transitional'},
             'transitional/mixed': {'transitional', 'mixed'},
             'tungstate': {'tungstate'},
             'vanadate': {'vanadate'}},
 'processtype': {'acid chloride leach': {'acid chloride leach'},
                 'acid leach': {'acid leach'},
                 'activox': {'activox'},
                 'agglomerated fines heap leach (afhl)': {'afhl',
                                                          'agglomerated fines '
                                                          'heap leach'},
                 'agglomeration': {'agglomeration'},
                 'agitated tank leach (al)': {'agitated tank leach', 'al'},
                 'albion process': {'albion'},
                 'alkaline leach': {'alkaline leach'},
                 'alloystream': {'alloystream'},
                 'alluvial (generic)': {'generic', 'alluvial'},
                 'amalgamation': {'amalgamation'},
                 'ammonia leach': {'ammonia leach'},
                 'atmospheric leach': {'atmospheric leach'},
                 'bacterial oxidation (biox)': {'bacterial oxidation', 'biox'},
                 'bayer process': {'bayer'},
                 'betterton-kroll process (asarco process)': {'asarco',
                                                              'betterton '
                                                              'kroll'},
                 'bio-heap leach (dump bioleach)': {'bio-heap leach',
                                                    'dump bioleach'},
                 'biox / column bioleach': {'biox', 'column bioleach'},
                 'blast furnace (pyro) smelting': {'blast furnace', 'pyro'},
                 'calcination / sintering': {'calcination / sintering'},
                 'carbon absorption-desorbtion-refining (adr)': {'adr',
                                                                 'carbon '
                                                                 'absorption '
                                                                 'desorbtion '
                                                                 'refining'},
                 'carbon-in-column (cic)': {'carbon-in-column', 'cic'},
                 'carbon-in-leach (cil)_': {'cil', 'carbon-in-leach'},
                 'carbon-in-pulp (cip)': {'carbon-in-pulp', 'cip'},
                 'carbonation and crystallisation': {'carbonation and '
                                                     'crystallisation'},
                 'carbonyl refining (mond process)': {'carbonyl', 'mond'},
                 'caron process': {'caron process'},
                 'catalytic leaching': {'catalytic leaching'},
                 'caustic fusion': {'caustic fusion'},
                 'cesl': {'cesl'},
                 'chlorination (kroll process)': {'kroll', 'chlorination'},
                 'chlorination (turco process)': {'turco'},
                 'column leach': {'column leach'},
                 'copper heap bioleach': {'copper heap bioleach'},
                 'counter current decantation (ccd)': {'ccd',
                                                       'counter current '
                                                       'decantation'},
                 'cyanidation (cyanide leach /  macarthur-forrest process)': {'cyanidation',
                                                                              'cyanide '
                                                                              'leach',
                                                                              'macarthur-forrest'},
                 'dense media / gravity separation (dms)': {'dense media',
                                                            'dms',
                                                            'gravity '
                                                            'separation'},
                 'desorption electrolysis': {'desorption electrolysis'},
                 'direct lithium extraction (dle)': {'direct lithium '
                                                     'extraction',
                                                     'dle'},
                 'dni leach process': {'dni'},
                 'dry milling': {'dry milling', 'mill'},
                 'dump leach': {'dump leach'},
                 'dynamic leach (dynamic heap leach)': {'dynamic heap leach',
                                                        'dynamic leach'},
                 'dynamic leach (on off pad)': {'on off pad'},

In [86]:
# Set maximum number of rows to display
pd.set_option('display.max_rows', 2000)

# Set maximum number of columns to display
pd.set_option('display.max_columns', 2000)

# Set maximum width of each column
pd.set_option('display.max_colwidth', 2000)

# Set the width of the display in characters
pd.set_option('display.width', 2200)

In [9]:
import pandas as pd
from tqdm.notebook import tqdm

import importlib

#### Search for mining news articles (8000 urls)

In [ ]:
from search import search_news

urls = search_news(8000)
df = pd.DataFrame(urls, columns=['url'])
df.head()

#### Download the html files

In [19]:
from download import fetch_and_write_all

file_paths = await fetch_and_write_all(urls)
df['path'] = file_paths
df.head()

,url,path
0,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c1544.html
1,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c5893.html
2,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c4520.html
3,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c4355.html
4,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c1563.html

In [21]:
df.index.name = 'id'
df.to_csv("data.csv")

In [10]:
df = pd.read_csv("data.csv")
df.set_index('id', inplace=True)

#### Tag articles with mentioned project / mine names

In [ ]:
import html_processor
import project_name_tagger
importlib.reload(html_processor)
importlib.reload(project_name_tagger)

from html_processor import get_article
from project_name_tagger import get_project_names
import time

def p_name_helper(title, provider, published_date, body):
    try:
        project_names = get_project_names(f"TITLE: {title}, PROVIDER: {provider}, PUBLISHED_DATE: {published_date}, BODY: {body}")
        return str(project_names)
    except:
        return None

times = 0
total = len(df)
processed_count = 0

if 'project_names' not in df.columns:
    df['project_names'] = ''

for i, [idx, row] in tqdm(enumerate(df.iterrows()), total=total):
    start = time.time()

    if i < 1900:
        continue

    existing_projects = df.at[idx, 'project_names']
    if existing_projects is not None and pd.notna(existing_projects) and existing_projects != '[]' and existing_projects != '':
        # print('exists')
        continue
        
    try:
        with open(row.get('path'), 'r') as file:
            title, provider, published_date, body = get_article(file.read(), redact_tables=True, convert_to_text=True)
    except:
        # print('exception')
        continue

    if len(body) / 3 > 10000:
        # print('too long')
        continue

    result = p_name_helper(title, provider, published_date, body)
    df.at[idx, 'project_names'] = result
    
    if i%50 == 0:
        df.to_csv("data.csv")

    processed_count += 1
        
    end = time.time()
    times += end - start
    avg_time = times / processed_count

    # print(f"Processed {processed_count} docs, Average time per doc: {avg_time:.4f} seconds", end='\n')
    print(f"Processed {processed_count} docs, Average time per doc: {avg_time:.4f} seconds, estimated time: {(total - i) * avg_time / 60 / 60:.4f} hours", end='\r')

  0%|          | 0/8000 [00:00<?, ?it/s]

Processed 3756 docs, Average time per doc: 7.2110 seconds, estimated time: 4.4628 hourss

In [7]:
df.describe()

,url,path,project_names
count,8000,7968,5589
unique,7999,7967,4814
top,http://www.newswire.ca/en/releases/archive/Jul...,articles/July202508c9439.html,"['Lunahuasi', 'Los Helados']"
freq,2,2,26

#### Classification of articles into Resource, Drilling, Production
Only 'Resource' classification is implemented

In [3]:
from classifier import is_resource_table

if not 'category' in df.columns:
    df['category'] = ''

for idx, row in tqdm(df.iterrows(), total=len(df)):
    try:
        tables = pd.read_html(row.get('path'))
    except:
        tables = []
    for table in tables:
        is_resource = is_resource_table(table)
        df.at[idx, 'category'] = 'resource'
        break;

['ton', 'cont', 'tons', 'tonn', 'metal', 'tonnes', 'average', 'tonnage', 'content', 'contained', 'avg', 'grade']
['proven', 'meas / ind', 'infe', 'm+i', 'p', 'prov_prob', 'meas', 'pro', 'proven & probable', 'p & p', 'p/p', 'prov-prob', 'prov / prob', 'meas/ind', 'm & i', 'prov prob', 'inf', 'meas-ind', 'i', 'p / p', 'proven / probable', 'measured', 'proven + probable', 'm / i', 'ind', 'meas&ind', 'indicated', 'meas ind', 'prov', 'prob', 'meas_ind', 'p + p', 'inferred', 'm/i', 'meas & ind', 'm&i', 'proven/probable', 'mi', 'm + i', 'prov/prob', 'probable', 'm', 'proba']

  0%|          | 0/8000 [00:00<?, ?it/s]

In [20]:
df.describe()

,url,path,project_names,category
count,8000,7968,5589,2383
unique,7999,7967,4814,1
top,http://www.newswire.ca/en/releases/archive/Jul...,articles/July202508c9439.html,"['Lunahuasi', 'Los Helados']",resource
freq,2,2,26,2383

In [21]:
df.to_csv('data.csv')

In [26]:


import sys
sys.path.append("..") # Adds higher directory to python modules path.

In [70]:
tables = pd.read_html('articles/February202623c6856.html')
tables[0]

,0,1,2,3,4
0,Mineral Resource Estimate,Mineral Resource Estimate,Mineral Resource Estimate,Mineral Resource Estimate,Mineral Resource Estimate
1,Domain,Tonnes Above Cut- off (millions),Li Grade (ppm),Li Contained (million t),LCE (million t)
2,Measured,858.26,990,0.850,4.523
3,Indicated,280.33,891,0.250,1.329
4,Measured & Indicated,1138.59,966,1.099,5.852
5,Inferred,187.28,820,0.154,0.817
6,"1.The effective date of the Mineral Resource Estimate is April 29, 2024. The QP for the estimate...","1.The effective date of the Mineral Resource Estimate is April 29, 2024. The QP for the estimate...","1.The effective date of the Mineral Resource Estimate is April 29, 2024. The QP for the estimate...","1.The effective date of the Mineral Resource Estimate is April 29, 2024. The QP for the estimate...","1.The effective date of the Mineral Resource Estimate is April 29, 2024. The QP for the estimate..."

In [100]:
from resource_table_extractor import parse_table
from classifier import is_resource_table

for idx, row in df.iterrows():
    try:
        tables = pd.read_html(row.get('path'))
    except:
        tables = []
    for i, table in enumerate(tables):
        is_resource = is_resource_table(table)
        if is_resource:
            parsed_table = parse_table(table)
            if parsed_table is None:
                continue
            print("file:///home/ravi/work/mining/project/"+row.get('path'))
            print(i+1)
            display(parsed_table)
            display(HTML(table.to_html()))

file:///home/ravi/work/mining/project/articles/February202623c6856.html
1

      value     metric   category measurement      commodity
0    858.26    tonnage   measured         NaN            NaN
1       990      grade   measured         ppm        lithium
2     0.850  contained   measured           t        lithium
3     4.523        NaN   measured           t  lithium (lce)
4    280.33    tonnage  indicated         NaN            NaN
5       891      grade  indicated         ppm        lithium
6     0.250  contained  indicated           t        lithium
7     1.329        NaN  indicated           t  lithium (lce)
8   1138.59    tonnage   meas_ind         NaN            NaN
9       966      grade   meas_ind         ppm        lithium
10    1.099  contained   meas_ind           t        lithium
11    5.852        NaN   meas_ind           t  lithium (lce)
12   187.28    tonnage   inferred         NaN            NaN
13      820      grade   inferred         ppm        lithium
14    0.154  contained   inferred           t        lithium
15    0.817        NaN   inferred           t  lithium (lce)

file:///home/ravi/work/mining/project/articles/February202623c6856.html
2

     value     metric   category measurement      commodity
0   266.39    tonnage     proven         NaN            NaN
1     1147      grade     proven         ppm        lithium
2    0.306  contained     proven           t        lithium
3    1.626        NaN     proven           t  lithium (lce)
4    21.26    tonnage   probable         NaN            NaN
5     1174      grade   probable         ppm        lithium
6    0.025  contained   probable           t        lithium
7    0.133        NaN   probable           t  lithium (lce)
8   287.65    tonnage  prov_prob         NaN            NaN
9     1149      grade  prov_prob         ppm        lithium
10   0.330  contained  prov_prob           t        lithium
11   1.759        NaN  prov_prob           t  lithium (lce)

file:///home/ravi/work/mining/project/articles/February202619c7968.html
1

   value     metric  category measurement commodity
0   8000      grade       NaN         NaN       NaN
1   37.2    tonnage  measured         NaN       NaN
2   2.70      grade       NaN         g/t      gold
3   11.5      grade       NaN         g/t    silver
4   0.39      grade       NaN         NaN      zinc
5   2.86      grade       NaN         g/t      gold
6   3.22  contained  measured         NaN      gold
7   3.42  contained  measured         NaN      gold
8   87 %      grade       NaN         NaN      gold
9   2.80        NaN  measured         NaN      gold
10  2.97        NaN  measured         NaN      gold
11  2.48        NaN  measured         NaN      gold
12  2.61        NaN  measured         NaN      gold

file:///home/ravi/work/mining/project/articles/February202619c7968.html
9

             value   minetype      processtype   category measurement commodity     metric
0             2768   open pit  heap leach (hl)   measured          kt       NaN        NaN
1             0.79   open pit  heap leach (hl)   measured         g/t      gold      grade
2            16.21   open pit  heap leach (hl)   measured         g/t    silver      grade
3             0.85   open pit  heap leach (hl)   measured         g/t       NaN      grade
4               71   open pit  heap leach (hl)   measured          oz      gold  contained
5             1442   open pit  heap leach (hl)   measured          oz    silver  contained
6               76   open pit  heap leach (hl)   measured          oz       NaN  contained
7             8.44   open pit  heap leach (hl)   measured         g/t      gold      grade
8            37309   open pit  heap leach (hl)  indicated          kt       NaN        NaN
9             0.69   open pit  heap leach (hl)  indicated         g/t      gold      grade
10           13.10   open pit  heap leach (hl)  indicated         g/t    silver      grade
11            0.74   open pit  heap leach (hl)  indicated         g/t       NaN      grade
12             823   open pit  heap leach (hl)  indicated          oz      gold  contained
13           15708   open pit  heap leach (hl)  indicated          oz    silver  contained
14             893   open pit  heap leach (hl)  indicated          oz       NaN  contained
15            8.44   open pit  heap leach (hl)  indicated         g/t      gold      grade
16           40077   open pit  heap leach (hl)   meas_ind          kt       NaN        NaN
17            0.69   open pit  heap leach (hl)   meas_ind         g/t      gold      grade
18           13.31   open pit  heap leach (hl)   meas_ind         g/t    silver      grade
19            0.75   open pit  heap leach (hl)   meas_ind         g/t       NaN      grade
20             893   open pit  heap leach (hl)   meas_ind          oz      gold  contained
21           17151   open pit  heap leach (hl)   meas_ind          oz    silver  contained
22             969   open pit  heap leach (hl)   meas_ind          oz       NaN  contained
23            8.44   open pit  heap leach (hl)   meas_ind         g/t      gold      grade
24            1523   open pit  heap leach (hl)   inferred          kt       NaN        NaN
25            0.74   open pit  heap leach (hl)   inferred         g/t      gold      grade
26           12.26   open pit  heap leach (hl)   inferred         g/t    silver      grade
27            0.80   open pit  heap leach (hl)   inferred         g/t       NaN      grade
28              36   open pit  heap leach (hl)   inferred          oz      gold  contained
29             600   open pit  heap leach (hl)   inferred          oz    silver  contained
30              39   open pit  heap leach (hl)   inferred          oz       NaN  contained
31            8.44   open pit  heap leach (hl)   inferred         g/t      gold      grade
32               0   open pit      dry milling   measured          kt       NaN        NaN
33           14.06   open pit      dry milling   measured         g/t      gold      grade
34            2213   open pit      dry milling  indicated          kt       NaN        NaN
35            0.85   open pit      dry milling  indicated         g/t      gold      grade
36            8.91   open pit      dry milling  indicated         g/t    silver      grade
37            3947   open pit      dry milling  indicated         ppm      zinc      grade
38            0.94   open pit      dry milling  indicated         g/t       NaN      grade
39              60   open pit      dry milling  indicated          oz      gold  contained
40             634   open pit      dry milling  indicated          oz    silver  contained
41              19   open pit      dry milling  indicated          lb      zinc  contained
42              67   open pit      dry milling  indicated          oz       NaN  contained
43           14.06   open pit      dry milling  indicated         g/t      gold      grade
44            2213   open pit      dry milling   meas_ind          kt       NaN        NaN
45            0.85   open pit      dry milling   meas_ind         g/t      gold      grade
46            8.91   open pit      dry milling   meas_ind         g/t    silver      grade
47            3947   open pit      dry milling   meas_ind         ppm      zinc      grade
48            0.94   open pit      dry milling   meas_ind         g/t       NaN      grade
49              60   open pit      dry milling   meas_ind          oz      gold  contained
50             634   open pit      dry milling   meas_ind          oz    silver  contained
51              19   open pit      dry milling   meas_ind          lb      zinc  contained
52              67   open pit      dry milling   meas_ind          oz       NaN  contained
53           14.06   open pit      dry milling   meas_ind         g/t      gold      grade
54              71   open pit      dry milling   inferred          kt       NaN        NaN
55            0.85   open pit      dry milling   inferred         g/t      gold      grade
56            8.69   open pit      dry milling   inferred         g/t    silver      grade
57            2951   open pit      dry milling   inferred         ppm      zinc      grade
58            0.95   open pit      dry milling   inferred         g/t       NaN      grade
59               2   open pit      dry milling   inferred          oz      gold  contained
60              20   open pit      dry milling   inferred          oz    silver  contained
61               0   open pit      dry milling   inferred          lb      zinc  contained
62               2   open pit      dry milling   inferred          oz       NaN  contained
63           14.06   open pit      dry milling   inferred         g/t      gold      grade
64            2768   open pit              NaN   measured          kt       NaN        NaN
65            0.79   open pit              NaN   measured         g/t      gold      grade
66           16.21   open pit              NaN   measured         g/t    silver      grade
67            0.85   open pit              NaN   measured         g/t       NaN      grade
68              71   open pit              NaN   measured          oz      gold  contained
69            1442   open pit              NaN   measured          oz    silver  contained
70               0   open pit              NaN   measured          lb      zinc  contained
71              76   open pit              NaN   measured          oz       NaN  contained
72   8.44 to 14.06   open pit              NaN   measured         g/t      gold      grade
73           39522   open pit              NaN  indicated          kt       NaN        NaN
74            0.69   open pit              NaN  indicated         g/t      gold      grade
75           12.86   open pit              NaN  indicated         g/t    silver      grade
76             221   open pit              NaN  indicated         ppm      zinc      grade
77            0.76   open pit              NaN  indicated         g/t       NaN      grade
78             883   open pit              NaN  indicated          oz      gold  contained
79           16342   open pit              NaN  indicated          oz    silver  contained
80              19   open pit              NaN  indicated          lb      zinc  contained
81             960   open pit              NaN  indicated          oz       NaN  contained
82   8.44 to 14.06   open pit              NaN  indicated         g/t      gold      grade
83           42290   open pit              NaN   meas_ind          kt       NaN        NaN
84            0.70   open pit              NaN   meas_ind         g/t      gold      grade
85           13.08   open pit              NaN   meas_ind         g/t    silver      grade
86             207   open pit              NaN   meas_ind         ppm      zinc      grade
87            0.76   open pit              NaN   meas_ind         g/t       NaN      grade
88             953   open pit              NaN   meas_ind          oz      gold  contained
89           17785   open pit              NaN   meas_ind          oz    silver  contained
90              19   open pit              NaN   meas_ind          lb      zinc  contained
91            1036   open pit              NaN   meas_ind          oz       NaN  contained
92   8.44 to 14.06   open pit              NaN   meas_ind         g/t      gold      grade
93            1594   open pit              NaN   inferred          kt       NaN        NaN
94            0.74   open pit              NaN   inferred         g/t      gold      grade
95           12.10   open pit              NaN   inferred         g/t    silver      grade
96             131   open pit              NaN   inferred         ppm      zinc      grade
97            0.80   open pit              NaN   inferred         g/t       NaN      grade
98              38   open pit              NaN   inferred          oz      gold  contained
99             620   open pit              NaN   inferred          oz    silver  contained
100              0   open pit              NaN   inferred          lb      zinc  contained
101             41   open pit              NaN   inferred          oz       NaN  contained
102  8.44 to 14.06   open pit              NaN   inferred         g/t      gold      grade
103              0        NaN  heap leach (hl)   measured          kt       NaN        NaN
104       57 to 66        NaN  heap leach (hl)   measured         g/t      gold      grade
105           3298        NaN  heap leach (hl)  indicated          kt       NaN        NaN
106           2.54        NaN  heap leach (hl)  indicated         g/t      gold      grade
107          12.23        NaN  heap leach (hl)  indicated         g/t    silver      grade
108           2.66        NaN  heap leach (hl)  indicated         g/t       NaN      grade
109            269        NaN  heap leach (hl)  indicated          oz      gold  contained
110           1297        NaN  heap leach (hl)  indicated          oz    silver  contained
111            282        NaN  heap leach (hl)  indicated          oz       NaN  contained
112       57 to 66        NaN  heap leach (hl)  indicated         g/t      gold      grade
113           3298        NaN  heap leach (hl)   meas_ind          kt       NaN        NaN
114           2.54        NaN  heap leach (hl)   meas_ind         g/t      gold      grade
115          12.23        NaN  heap leach (hl)   meas_ind         g/t    silver      grade
116           2.66        NaN  heap leach (hl)   meas_ind         g/t       NaN      grade
117            269        NaN  heap leach (hl)   meas_ind          oz      gold  contained
118           1297        NaN  heap leach (hl)   meas_ind          oz    silver  contained
119            282        NaN  heap leach (hl)   meas_ind          oz       NaN  contained
120       57 to 66        NaN  heap leach (hl)   meas_ind         g/t      gold      grade
121            198        NaN  heap leach (hl)   inferred          kt       NaN        NaN
122           2.39        NaN  heap leach (hl)   inferred         g/t      gold      grade
123          14.62        NaN  heap leach (hl)   inferred         g/t    silver      grade
124           2.53        NaN  heap leach (hl)   inferred         g/t       NaN      grade
125             15        NaN  heap leach (hl)   inferred          oz      gold  contained
126             93        NaN  heap leach (hl)   inferred          oz    silver  contained
127             16        NaN  heap leach (hl)   inferred          oz       NaN  contained
128       57 to 66        NaN  heap leach (hl)   inferred         g/t      gold      grade
129              0        NaN      dry milling   measured          kt       NaN        NaN
130       63 to 72        NaN      dry milling   measured         g/t      gold      grade
131          45965        NaN      dry milling  indicated          kt       NaN        NaN
132           2.53        NaN      dry milling  indicated         g/t      gold      grade
133          11.28        NaN      dry milling  indicated         g/t    silver      grade
134           3783        NaN      dry milling  indicated         ppm      zinc      grade
135            2.7        NaN      dry milling  indicated         g/t       NaN      grade
136           3745        NaN      dry milling  indicated          oz      gold  contained
137          16674        NaN      dry milling  indicated          oz    silver  contained
138            383        NaN      dry milling  indicated          lb      zinc  contained
139           3985        NaN      dry milling  indicated          oz       NaN  contained
140       63 to 72        NaN      dry milling  indicated         g/t      gold      grade
141          45965        NaN      dry milling   meas_ind          kt       NaN        NaN
142           2.53        NaN      dry milling   meas_ind         g/t      gold      grade
143          11.28        NaN      dry milling   meas_ind         g/t    silver      grade
144           3783        NaN      dry milling   meas_ind         ppm      zinc      grade
145            2.7        NaN      dry milling   meas_ind         g/t       NaN      grade
146           3745        NaN      dry milling   meas_ind          oz      gold  contained
147          16674        NaN      dry milling   meas_ind          oz    silver  contained
148            383        NaN      dry milling   meas_ind          lb      zinc  contained
149           3985        NaN      dry milling   meas_ind          oz       NaN  contained
150       63 to 72        NaN      dry milling   meas_ind         g/t      gold      grade
151           3974        NaN      dry milling   inferred          kt       NaN        NaN
152           2.51        NaN      dry milling   inferred         g/t      gold      grade
153          10.95        NaN      dry milling   inferred         g/t    silver      grade
154           6613        NaN      dry milling   inferred         ppm      zinc      grade
155           2.82        NaN      dry milling   inferred         g/t       NaN      grade
156            321        NaN      dry milling   inferred          oz      gold  contained
157           1398        NaN      dry milling   inferred          oz    silver  contained
158             58        NaN      dry milling   inferred          lb      zinc  contained
159            360        NaN      dry milling   inferred          oz       NaN  contained
160       63 to 72        NaN      dry milling   inferred         g/t      gold      grade
161              0        NaN              NaN   measured          kt       NaN        NaN
162       57 to 72        NaN              NaN   measured         g/t      gold      grade
163          49263        NaN              NaN  indicated          kt       NaN        NaN
164           2.53        NaN              NaN  indicated         g/t      gold      grade
165          11.35        NaN              NaN  indicated         g/t    silver      grade
166           3530        NaN              NaN  indicated         ppm      zinc      grade
167           2.69        NaN              NaN  indicated         g/t       NaN      grade
168           4014        NaN              NaN  indicated          oz      gold  contained
169          17971        NaN              NaN  indicated          oz    silver  contained
170            383        NaN              NaN  indicated          lb      zinc  contained
171           4267        NaN              NaN  indicated          oz       NaN  contained
172       57 to 72        NaN              NaN  indicated         g/t      gold      grade
173          49263        NaN              NaN   meas_ind          kt       NaN        NaN
174           2.53        NaN              NaN   meas_ind         g/t      gold      grade
175          11.35        NaN              NaN   meas_ind         g/t    silver      grade
176           3530        NaN              NaN   meas_ind         ppm      zinc      grade
177           2.69        NaN              NaN   meas_ind         g/t       NaN      grade
178           4014        NaN              NaN   meas_ind          oz      gold  contained
179          17971        NaN              NaN   meas_ind          oz    silver  contained
180            383        NaN              NaN   meas_ind          lb      zinc  contained
181           4267        NaN              NaN   meas_ind          oz       NaN  contained
182       57 to 72        NaN              NaN   meas_ind         g/t      gold      grade
183           4172        NaN              NaN   inferred          kt       NaN        NaN
184           2.50        NaN              NaN   inferred         g/t      gold      grade
185          11.12        NaN              NaN   inferred         g/t    silver      grade
186           6299        NaN              NaN   inferred         ppm      zinc      grade
187           2.80        NaN              NaN   inferred         g/t       NaN      grade
188            336        NaN              NaN   inferred          oz      gold  contained
189           1491        NaN              NaN   inferred          oz    silver  contained
190             58        NaN              NaN   inferred          lb      zinc  contained
191            376        NaN              NaN   inferred          oz       NaN  contained
192       57 to 72        NaN              NaN   inferred         g/t      gold      grade
193            588  stockpile              NaN   measured          kt       NaN        NaN
194           0.34  stockpile              NaN   measured         g/t      gold      grade
195          20.25  stockpile              NaN   measured         g/t    silver      grade
196           0.34  stockpile              NaN   measured         g/t       NaN      grade
197              6  stockpile              NaN   measured          oz      gold  contained
198            383  stockpile              NaN   measured          oz    silver  contained
199              6  stockpile              NaN   measured          oz       NaN  contained
200              0  stockpile              NaN  indicated          kt       NaN        NaN
201            588  stockpile              NaN   meas_ind          kt       NaN        NaN
202           0.34  stockpile              NaN   meas_ind         g/t      gold      grade
203          20.25  stockpile              NaN   meas_ind         g/t    silver      grade
204           0.34  stockpile              NaN   meas_ind         g/t       NaN      grade
205              6  stockpile              NaN   meas_ind          oz      gold  contained
206            383  stockpile              NaN   meas_ind          oz    silver  contained
207              6  stockpile              NaN   meas_ind          oz       NaN  contained
208              0  stockpile              NaN   inferred          kt       NaN        NaN
209            588  stockpile              NaN        NaN          kt       NaN        NaN
210           0.34  stockpile              NaN        NaN         g/t      gold      grade
211          20.25  stockpile              NaN        NaN         g/t    silver      grade
212           0.34  stockpile              NaN        NaN         g/t       NaN      grade
213              6  stockpile              NaN        NaN          oz      gold  contained
214            383  stockpile              NaN        NaN          oz    silver  contained
215              6  stockpile              NaN        NaN          oz       NaN  contained
216           3355        NaN              NaN   measured          kt       NaN        NaN
217           0.71        NaN              NaN   measured         g/t      gold      grade

file:///home/ravi/work/mining/project/articles/February202619c7968.html
12

      value commodity     metric measurement  category
0        y1   yttrium        NaN         NaN       NaN
1        y2   yttrium        NaN         NaN       NaN
2        y3   yttrium        NaN         NaN       NaN
3        y4   yttrium        NaN         NaN       NaN
4        y5   yttrium        NaN         NaN       NaN
5        y6   yttrium        NaN         NaN       NaN
6        y7   yttrium        NaN         NaN       NaN
7        y8   yttrium        NaN         NaN       NaN
8        y9   yttrium        NaN         NaN       NaN
9       y10   yttrium        NaN         NaN       NaN
10      y11   yttrium        NaN         NaN       NaN
11      y12   yttrium        NaN         NaN       NaN
12      y13   yttrium        NaN         NaN       NaN
13      y14   yttrium        NaN         NaN       NaN
14      y15   yttrium        NaN         NaN       NaN
15      y16   yttrium        NaN         NaN       NaN
16      y17   yttrium        NaN         NaN       NaN
17   y18-20   yttrium        NaN         NaN       NaN
18     2.70      gold      grade         g/t       NaN
19     2.48      gold      grade         g/t       NaN
20     2.61      gold      grade         g/t       NaN
21     2.67      gold      grade         g/t       NaN
22     2.46      gold      grade         g/t       NaN
23     2.77      gold      grade         g/t       NaN
24     2.80      gold      grade         g/t       NaN
25     2.75      gold      grade         g/t       NaN
26     2.65      gold      grade         g/t       NaN
27     2.73      gold      grade         g/t       NaN
28     2.66      gold      grade         g/t       NaN
29     2.77      gold      grade         g/t       NaN
30     2.82      gold      grade         g/t       NaN
31     2.77      gold      grade         g/t       NaN
32     2.99      gold      grade         g/t       NaN
33     2.84      gold      grade         g/t       NaN
34     2.88      gold      grade         g/t       NaN
35     2.22      gold      grade         g/t       NaN
36     11.5    silver      grade         g/t       NaN
37     11.5    silver      grade         g/t       NaN
38     13.2    silver      grade         g/t       NaN
39     12.7    silver      grade         g/t       NaN
40     11.9    silver      grade         g/t       NaN
41     11.7    silver      grade         g/t       NaN
42     10.9    silver      grade         g/t       NaN
43     12.1    silver      grade         g/t       NaN
44     11.3    silver      grade         g/t       NaN
45     12.2    silver      grade         g/t       NaN
46     11.7    silver      grade         g/t       NaN
47     10.7    silver      grade         g/t       NaN
48      9.3    silver      grade         g/t       NaN
49     10.1    silver      grade         g/t       NaN
50     10.8    silver      grade         g/t       NaN
51      8.2    silver      grade         g/t       NaN
52      6.5    silver      grade         g/t       NaN
53      9.2    silver      grade         g/t       NaN
54     0.39      zinc      grade         NaN       NaN
55     0.37      zinc      grade         NaN       NaN
56     0.40      zinc      grade         NaN       NaN
57     0.38      zinc      grade         NaN       NaN
58     0.37      zinc      grade         NaN       NaN
59     0.36      zinc      grade         NaN       NaN
60     0.35      zinc      grade         NaN       NaN
61     0.38      zinc      grade         NaN       NaN
62     0.38      zinc      grade         NaN       NaN
63     0.42      zinc      grade         NaN       NaN
64     0.39      zinc      grade         NaN       NaN
65     0.47      zinc      grade         NaN       NaN
66     0.43      zinc      grade         NaN       NaN
67     0.43      zinc      grade         NaN       NaN
68     0.40      zinc      grade         NaN       NaN
69     0.34      zinc      grade         NaN       NaN
70     0.26      zinc      grade         NaN       NaN
71     0.31      zinc      grade         NaN       NaN
72     3223      gold  contained          oz       NaN
73      233      gold  contained          oz       NaN
74      222      gold  contained          oz       NaN
75      249      gold  contained          oz       NaN
76      231      gold  contained          oz       NaN
77      260      gold  contained          oz       NaN
78      263      gold  contained          oz       NaN
79      259      gold  contained          oz       NaN
80      267      gold  contained          oz       NaN
81      243      gold  contained          oz       NaN
82      248      gold  contained          oz       NaN
83      215      gold  contained          oz       NaN
84      174      gold  contained          oz       NaN
85      154      gold  contained          oz       NaN
86      109      gold  contained          oz       NaN
87       68      gold  contained          oz       NaN
88       27      gold  contained          oz       NaN
89        2      gold  contained          oz       NaN
90    13705    silver  contained          oz       NaN
91     1081    silver  contained          oz       NaN
92     1121    silver  contained          oz       NaN
93     1180    silver  contained          oz       NaN
94     1118    silver  contained          oz       NaN
95     1101    silver  contained          oz       NaN
96     1025    silver  contained          oz       NaN
97     1133    silver  contained          oz       NaN
98     1137    silver  contained          oz       NaN
99     1090    silver  contained          oz       NaN
100    1094    silver  contained          oz       NaN
101     832    silver  contained          oz       NaN
102     572    silver  contained          oz       NaN
103     560    silver  contained          oz       NaN
104     395    silver  contained          oz       NaN
105     197    silver  contained          oz       NaN
106      61    silver  contained          oz       NaN
107       7    silver  contained          oz       NaN
108   319.2      zinc  contained         NaN  measured
109    24.1      zinc  contained         NaN  measured
110    23.5      zinc  contained         NaN  measured
111    24.0      zinc  contained         NaN  measured
112    24.1      zinc  contained         NaN  measured
113    23.2      zinc  contained         NaN  measured
114    22.5      zinc  contained         NaN  measured
115    24.5      zinc  contained         NaN  measured
116    26.0      zinc  contained         NaN  measured
117    25.9      zinc  contained         NaN  measured
118    24.7      zinc  contained         NaN  measured
119    24.9      zinc  contained         NaN  measured
120    18.0      zinc  contained         NaN  measured
121    16.4      zinc  contained         NaN  measured
122     9.9      zinc  contained         NaN  measured
123     5.6      zinc  contained         NaN  measured
124     1.7      zinc  contained         NaN  measured
125     0.2      zinc  contained         NaN  measured
126    3423      gold  contained          oz       NaN
127     248      gold  contained          oz       NaN
128     236      gold  contained          oz       NaN
129     264      gold  contained          oz       NaN
130     247      gold  contained          oz       NaN
131     275      gold  contained          oz       NaN
132     277      gold  contained          oz       NaN
133     274      gold  contained          oz       NaN
134     284      gold  contained          oz       NaN
135     259      gold  contained          oz       NaN
136     264      gold  contained          oz       NaN
137     230      gold  contained          oz       NaN
138     184      gold  contained          oz       NaN
139     164      gold  contained          oz       NaN
140     116      gold  contained          oz       NaN
141      72      gold  contained          oz       NaN
142      28      gold  contained          oz       NaN
143       2      gold  contained          oz       NaN
144    2796      gold        NaN          oz       NaN
145     204      gold        NaN          oz       NaN
146     190      gold        NaN          oz       NaN
147     216      gold        NaN          oz       NaN
148     202      gold        NaN          oz       NaN
149     226      gold        NaN          oz       NaN
150     229      gold        NaN          oz       NaN
151     226      gold        NaN          oz       NaN
152     231      gold        NaN          oz       NaN
153     210      gold        NaN          oz       NaN
154     213      gold        NaN          oz       NaN
155     185      gold        NaN          oz       NaN
156     150      gold        NaN          oz       NaN
157     133      gold        NaN          oz       NaN
158      95      gold        NaN          oz       NaN
159      60      gold        NaN          oz       NaN
160      23      gold        NaN          oz       NaN
161       2      gold        NaN          oz       NaN
162   10231    silver        NaN          oz       NaN
163     823    silver        NaN          oz       NaN
164     798    silver        NaN          oz       NaN
165     865    silver        NaN          oz       NaN
166     849    silver        NaN          oz       NaN
167     828    silver        NaN          oz       NaN
168     763    silver        NaN          oz       NaN
169     862    silver        NaN          oz       NaN
170     849    silver        NaN          oz       NaN
171     811    silver        NaN          oz       NaN
172     813    silver        NaN          oz       NaN
173     625    silver        NaN          oz       NaN
174     424    silver        NaN          oz       NaN
175     412    silver        NaN          oz       NaN
176     305    silver        NaN          oz       NaN
177     152    silver        NaN          oz       NaN
178      48    silver        NaN          oz       NaN
179       6    silver        NaN          oz       NaN
180   127.5      zinc        NaN         NaN  measured
181     8.0      zinc        NaN         NaN  measured
182     6.4      zinc        NaN         NaN  measured
183     7.2      zinc        NaN         NaN  measured
184     8.0      zinc        NaN         NaN  measured
185     7.5      zinc        NaN         NaN  measured
186     7.0      zinc        NaN         NaN  measured
187     8.2      zinc        NaN         NaN  measured
188    10.9      zinc        NaN         NaN  measured
189     9.7      zinc        NaN         NaN  measured
190    10.6      zinc        NaN         NaN  measured
191    14.5      zinc        NaN         NaN  measured
192    10.3      zinc        NaN         NaN  measured
193     8.9      zinc        NaN         NaN  measured
194     5.8      zinc        NaN         NaN  measured
195     3.8      zinc        NaN         NaN  measured
196     0.8      zinc        NaN         NaN  measured
197     0.1      zinc        NaN         NaN  measured
198    2969      gold        NaN          oz       NaN
199     217      gold        NaN          oz       NaN
200     202      gold        NaN          oz       NaN
201     229      gold        NaN          oz       NaN
202     216      gold        NaN          oz       NaN
203     239      gold        NaN          oz       NaN
204     240      gold        NaN          oz       NaN
205     240      gold        NaN          oz       NaN
206     245      gold        NaN          oz       NaN
207     224      gold        NaN          oz       NaN
208     227      gold        NaN          oz       NaN
209     198      gold        NaN          oz       NaN
210     159      gold        NaN          oz       NaN
211     141      gold        NaN          oz       NaN
212     101      gold        NaN          oz       NaN
213      63      gold        NaN          oz       NaN
214      24      gold        NaN          oz       NaN
215       2      gold        NaN          oz       NaN
216    2478      gold        NaN          oz       NaN
217     181      gold        NaN          oz       NaN
218     167      gold        NaN          oz       NaN
219     191      gold        NaN          oz       NaN
220     180      gold        NaN          oz       NaN
221     201      gold        NaN          oz       NaN
222     202      gold        NaN          oz       NaN
223     201      gold        NaN          oz       NaN
224     205      gold        NaN          oz       NaN
225     186      gold        NaN          oz       NaN
226     189      gold        NaN          oz       NaN
227     164      gold        NaN          oz       NaN
228     133      gold        NaN          oz       NaN
229     118      gold        NaN          oz       NaN
230      85      gold        NaN          oz       NaN
231      53      gold        NaN          oz       NaN
232      21      gold        NaN          oz       NaN
233       1      gold        NaN          oz       NaN
234    8404    silver        NaN          oz       NaN
235     676    silver        NaN          oz       NaN
236     653    silver        NaN          oz       NaN
237     711    silver        NaN          oz       NaN
238     698    silver        NaN          oz       NaN
239     681    silver        NaN          oz       NaN
240     627    silver        NaN          oz       NaN
241     709    silver        NaN          oz       NaN
242     697    silver        NaN          oz       NaN
243     664    silver        NaN          oz       NaN
244     667    silver        NaN          oz       NaN
245     513    silver        NaN          oz       NaN
246     349    silver        NaN          oz       NaN
247     338    silver        NaN          oz       NaN
248     252    silver        NaN          oz       NaN
249     125    silver        NaN          oz       NaN
250      39    silver        NaN          oz       NaN
251       5    silver        NaN          oz       NaN
252    91.9      zinc        NaN         NaN  measured
253     5.8      zinc        NaN         NaN  measured
254     4.6      zinc        NaN         NaN  measured
255     5.2      zinc        NaN         NaN  measured
256     5.8      zinc        NaN         NaN  measured
257     5.4      zinc        NaN         NaN  measured
258     5.0      zinc        NaN         NaN  measured
259     5.9      zinc        NaN         NaN  measured
260     7.9      zinc        NaN         NaN  measured
261     7.0      zinc        NaN         NaN  measured
262     7.6      zinc        NaN         NaN  measured
263    10.4      zinc        NaN         NaN  measured
264     7.4      zinc        NaN         NaN  measured
265     6.4      zinc        NaN         NaN  measured
266     4.2      zinc        NaN         NaN  measured
267     2.7      zinc        NaN         NaN  measured
268     0.6      zinc        NaN         NaN  measured
269     0.0      zinc        NaN         NaN  measured
270    2615      gold        NaN          oz       NaN
271     192      gold        NaN          oz       NaN
272     177      gold        NaN          oz       NaN
273     202      gold        NaN          oz       NaN
274     190      gold        NaN          oz       NaN
275     211      gold        NaN          oz       NaN
276     212      gold        NaN          oz       NaN
277     211      gold        NaN          oz       NaN
278     216      gold        NaN          oz       NaN
279     197      gold        NaN          oz       NaN
280     200      gold        NaN          oz       NaN
281     175      gold        NaN          oz       NaN
282     140      gold        NaN          oz       NaN
283     124      gold        NaN          oz       NaN
284      89      gold        NaN          oz       NaN
285      56      gold        NaN          oz       NaN
286      22      gold        NaN          oz       NaN
287       1      gold        NaN          oz       NaN
288    2645       NaN        NaN         NaN  measured
289     176       NaN        NaN         NaN  measured
290     180       NaN        NaN         NaN  measured
291     205       NaN        NaN         NaN  measured
292     204       NaN        NaN         NaN  measured
293     204       NaN        NaN         NaN  measured
294     208       NaN        NaN         NaN  measured
295     209       NaN        NaN         NaN  measured
296     207       NaN        NaN         NaN  measured
297     187       NaN        NaN         NaN  measured
298     193       NaN        NaN         NaN  measured
299     163       NaN        NaN         NaN  measured
300     142       NaN        NaN         NaN  measured
301     130       NaN        NaN         NaN  measured
302      94       NaN        NaN         NaN  measured
303      76       NaN        NaN         NaN  measured
304      47       NaN        NaN         NaN  measured
305      20       NaN        NaN         NaN  measured
306    1067      gold        NaN          oz       NaN
307     970      gold        NaN          oz       NaN
308    1076      gold        NaN          oz       NaN
309    1072      gold        NaN          oz       NaN
310    1137      gold        NaN          oz       NaN
311    1016      gold        NaN          oz       NaN
312    1026      gold        NaN          oz       NaN
313    1041      gold        NaN          oz       NaN
314    1013      gold        NaN          oz       NaN
315    1001      gold        NaN          oz       NaN
316    1020      gold        NaN          oz       NaN
317     989      gold        NaN          oz       NaN
318    1072      gold        NaN          oz       NaN
319    1107      gold        NaN          oz       NaN
320    1114      gold        NaN          oz       NaN
321    1437      gold        NaN          oz       NaN
322    2263      gold        NaN          oz       NaN
323   14828      gold        NaN          oz       NaN
324     608       NaN        NaN         NaN  measured
325     143   yttrium        NaN         NaN  measured
326     465   yttrium        NaN         NaN  measured
327     489       NaN        NaN         NaN  measured
328      46       NaN        NaN         NaN  measured
329      40       NaN        NaN         NaN  measured
330      41       NaN        NaN         NaN  measured
331      41       NaN        NaN         NaN  measured
332      37       NaN        NaN         NaN  measured
333      29       NaN        NaN         NaN  measured
334      33       NaN        NaN         NaN  measured
335      46       NaN        NaN         NaN  measured
336      46       NaN        NaN         NaN  measured
337      32       NaN        NaN         NaN  measured
338      27       NaN        NaN         NaN  measured
339      20       NaN        NaN         NaN  measured
340      18       NaN        NaN         NaN  measured
341      13       NaN        NaN         NaN  measured
342      11       NaN        NaN         NaN  measured
343       7       NaN        NaN         NaN  measured
344       2       NaN        NaN         NaN  measured
345     153       NaN        NaN         NaN  measured
346      11       NaN        NaN         NaN  measured
347      10       NaN        NaN         NaN  measured
348      12       NaN        NaN         NaN  measured
349      11       NaN        NaN         NaN  measured
350      12       NaN        NaN         NaN  measured
351      12       NaN        NaN         NaN  measured
352      12       NaN        NaN         NaN  measured
353      13       NaN        NaN         NaN  measured
354      12       NaN        NaN         NaN  measured
355      12       NaN        NaN         NaN  measured
356      10       NaN        NaN         NaN  measured
357       8       NaN        NaN         NaN  measured
358       7       NaN        NaN         NaN  measured
359       5       NaN        NaN         NaN  measured
360       3       NaN        NaN         NaN  measured
361       1       NaN        NaN         NaN  measured

file:///home/ravi/work/mining/project/articles/February202618c1164.html
3

      value   category measurement  commodity   metric oretype
0     10872  prov_prob          kt  phosphate      NaN     NaN
1   3350506  prov_prob          kt     copper  tonnage     NaN
2      0.32  prov_prob         NaN     copper    grade     NaN
3    101674        NaN          kt        NaN  tonnage     NaN
4      0.40        NaN         NaN     copper    grade     NaN
5      3484        NaN          kt        NaN  tonnage     NaN
6      0.91        NaN         NaN     copper    grade     NaN
7    259640        NaN          kt        NaN  tonnage   oxide
8      0.39        NaN         NaN     copper    grade   oxide
9   1011825        NaN          kt        NaN  tonnage     NaN
10     0.30        NaN         NaN     copper    grade     NaN
11    34972        NaN          kt        NaN  tonnage     NaN
12     0.11        NaN         NaN     copper    grade     NaN
13     6347  prov_prob          kt  phosphate      NaN     NaN
14  1938911  prov_prob          kt     copper  tonnage     NaN
15     0.33  prov_prob         NaN     copper    grade     NaN

file:///home/ravi/work/mining/project/articles/February202618c1164.html
5

       value     metric   category measurement   commodity     minetype
0     487110    tonnage   measured          kt         NaN          NaN
1     487110    tonnage   measured          kt         NaN          NaN
2     487110    tonnage   measured          kt         NaN          NaN
3       0.40      grade   measured         NaN      copper          NaN
4       0.10      grade   measured         g/t        gold          NaN
5       0.10      grade   measured         g/t        gold          NaN
6       1.36      grade   measured         g/t      silver          NaN
7       1.36      grade   measured         g/t      silver          NaN
8       1948  contained   measured          kt      copper          NaN
9       1948  contained   measured          kt      copper          NaN
10      1519  contained   measured         koz        gold          NaN
11      1519  contained   measured         koz        gold          NaN
12     21236  contained   measured         koz      silver          NaN
13      80 %  contained   measured         NaN         NaN          NaN
14      80 %        NaN   measured         NaN         NaN          NaN
15     65339    tonnage  indicated          kt         NaN     open pit
16     65339    tonnage  indicated          kt         NaN     open pit
17     65339    tonnage  indicated          kt         NaN     open pit
18      0.26      grade  indicated         NaN      copper     open pit
19      0.07      grade  indicated         g/t        gold     open pit
20      0.07      grade  indicated         g/t        gold     open pit
21      1.02      grade  indicated         g/t      silver     open pit
22      1.02      grade  indicated         g/t      silver     open pit
23       170  contained  indicated          kt      copper     open pit
24       170  contained  indicated          kt      copper     open pit
25       151  contained  indicated         koz        gold     open pit
26       151  contained  indicated         koz        gold     open pit
27      2147  contained  indicated         koz      silver     open pit
28      80 %  contained  indicated         NaN         NaN     open pit
29      80 %        NaN  indicated         NaN         NaN     open pit
30    552449    tonnage   meas_ind          kt         NaN          NaN
31    552449    tonnage   meas_ind          kt         NaN          NaN
32    552449    tonnage   meas_ind          kt         NaN          NaN
33      0.38      grade   meas_ind         NaN      copper          NaN
34      0.09      grade   meas_ind         g/t        gold          NaN
35      0.09      grade   meas_ind         g/t        gold          NaN
36      1.32      grade   meas_ind         g/t      silver          NaN
37      1.32      grade   meas_ind         g/t      silver          NaN
38      2118  contained   meas_ind          kt      copper          NaN
39      2118  contained   meas_ind          kt      copper          NaN
40      1670  contained   meas_ind         koz        gold          NaN
41      1670  contained   meas_ind         koz        gold          NaN
42     23383  contained   meas_ind         koz      silver          NaN
43      80 %  contained   meas_ind         NaN         NaN          NaN
44      80 %        NaN   meas_ind         NaN         NaN          NaN
45     11489    tonnage   inferred          kt         NaN          NaN
46     11489    tonnage   inferred          kt         NaN          NaN
47     11489    tonnage   inferred          kt         NaN          NaN
48      0.19      grade   inferred         NaN      copper          NaN
49      0.05      grade   inferred         g/t        gold          NaN
50      0.05      grade   inferred         g/t        gold          NaN
51      0.86      grade   inferred         g/t      silver          NaN
52      0.86      grade   inferred         g/t      silver          NaN
53        21  contained   inferred          kt      copper          NaN
54        21  contained   inferred          kt      copper          NaN
55        20  contained   inferred         koz        gold          NaN
56        20  contained   inferred         koz        gold          NaN
57       316  contained   inferred         koz      silver          NaN
58      80 %  contained   inferred         NaN         NaN          NaN
59      80 %        NaN   inferred         NaN         NaN          NaN
60     64297    tonnage   measured          kt   lanthanum          NaN
61     64297    tonnage   measured          kt   lanthanum          NaN
62     64297    tonnage   measured          kt   lanthanum          NaN
63      0.38      grade   measured         NaN      copper          NaN
64      0.08      grade   measured         g/t        gold          NaN
65      0.08      grade   measured         g/t        gold          NaN
66      0.33      grade   measured         g/t      silver          NaN
67      0.33      grade   measured         g/t      silver          NaN
68       242  contained   measured          kt      copper          NaN
69       242  contained   measured          kt      copper          NaN
70       161  contained   measured         koz        gold          NaN
71       161  contained   measured         koz        gold          NaN
72       684  contained   measured         koz      silver          NaN
73      80 %  contained   measured         NaN   lanthanum          NaN
74      80 %        NaN   measured         NaN   lanthanum          NaN
75     97599    tonnage  indicated          kt         NaN          NaN
76     97599    tonnage  indicated          kt         NaN          NaN
77     97599    tonnage  indicated          kt         NaN          NaN
78      0.31      grade  indicated         NaN      copper          NaN
79      0.06      grade  indicated         g/t        gold          NaN
80      0.06      grade  indicated         g/t        gold          NaN
81      0.31      grade  indicated         g/t      silver          NaN
82      0.31      grade  indicated         g/t      silver          NaN
83       305  contained  indicated          kt      copper          NaN
84       305  contained  indicated          kt      copper          NaN
85       182  contained  indicated         koz        gold          NaN
86       182  contained  indicated         koz        gold          NaN
87       960  contained  indicated         koz      silver          NaN
88      80 %  contained  indicated         NaN         NaN          NaN
89      80 %        NaN  indicated         NaN         NaN          NaN
90    161896    tonnage   meas_ind          kt         NaN          NaN
91    161896    tonnage   meas_ind          kt         NaN          NaN
92    161896    tonnage   meas_ind          kt         NaN          NaN
93      0.34      grade   meas_ind         NaN      copper          NaN
94      0.07      grade   meas_ind         g/t        gold          NaN
95      0.07      grade   meas_ind         g/t        gold          NaN
96      0.32      grade   meas_ind         g/t      silver          NaN
97      0.32      grade   meas_ind         g/t      silver          NaN
98       548  contained   meas_ind          kt      copper          NaN
99       548  contained   meas_ind          kt      copper          NaN
100      343  contained   meas_ind         koz        gold          NaN
101      343  contained   meas_ind         koz        gold          NaN
102     1644  contained   meas_ind         koz      silver          NaN
103     80 %  contained   meas_ind         NaN         NaN          NaN
104     80 %        NaN   meas_ind         NaN         NaN          NaN
105    43677    tonnage   inferred          kt         NaN          NaN
106    43677    tonnage   inferred          kt         NaN          NaN
107    43677    tonnage   inferred          kt         NaN          NaN
108     0.28      grade   inferred         NaN      copper          NaN
109     0.05      grade   inferred         g/t        gold          NaN
110     0.05      grade   inferred         g/t        gold          NaN
111     0.25      grade   inferred         g/t      silver          NaN
112     0.25      grade   inferred         g/t      silver          NaN
113      122  contained   inferred          kt      copper          NaN
114      122  contained   inferred          kt      copper          NaN
115       66  contained   inferred         koz        gold          NaN
116       66  contained   inferred         koz        gold          NaN
117      355  contained   inferred         koz      silver          NaN
118     80 %  contained   inferred         NaN         NaN          NaN
119     80 %        NaN   inferred         NaN         NaN          NaN
120   192402    tonnage   measured          kt         NaN  underground
121   192402    tonnage   measured          kt         NaN  underground
122   192402    tonnage   measured          kt         NaN  underground
123     0.86      grade   measured         NaN      copper  underground
124     0.20      grade   measured         g/t        gold  underground
125     0.20      grade   measured         g/t        gold  underground
126     3.57      grade   measured         g/t      silver  underground
127     3.57      grade   measured         g/t      silver  underground
128     1655  contained   measured          kt      copper  underground
129     1655  contained   measured          kt      copper  underground
130     1250  contained   measured         koz        gold  underground
131     1250  contained   measured         koz        gold  underground
132    22090  contained   measured         koz      silver  underground
133     80 %  contained   measured         NaN         NaN  underground
134     80 %        NaN   measured         NaN         NaN  underground
135   259416    tonnage  indicated          kt         NaN          NaN
136   259416    tonnage  indicated          kt         NaN          NaN
137   259416    tonnage  indicated          kt         NaN          NaN
138     0.77      grade  indicated         NaN      copper          NaN
139     0.17      grade  indicated         g/t        gold          NaN
140     0.17      grade  indicated         g/t        gold          NaN
141     3.14      grade  indicated         g/t      silver          NaN
142     3.14      grade  indicated         g/t      silver          NaN
143     2000  contained  indicated          kt      copper          NaN
144     2000  contained  indicated          kt      copper          NaN
145     1418  contained  indicated         koz        gold          NaN
146     1418  contained  indicated         koz        gold          NaN
147    26189  contained  indicated         koz      silver          NaN
148     80 %  contained  indicated         NaN         NaN          NaN
149     80 %        NaN  indicated         NaN         NaN          NaN
150   451818    tonnage   meas_ind          kt         NaN          NaN
151   451818    tonnage   meas_ind          kt         NaN          NaN
152   451818    tonnage   meas_ind          kt         NaN          NaN
153     0.81      grade   meas_ind         NaN      copper          NaN
154     0.18      grade   meas_ind         g/t        gold          NaN
155     0.18      grade   meas_ind         g/t        gold          NaN
156     3.32      grade   meas_ind         g/t      silver          NaN
157     3.32      grade   meas_ind         g/t      silver          NaN
158     3655  contained   meas_ind          kt      copper          NaN
159     3655  contained   meas_ind          kt      copper          NaN
160     2667  contained   meas_ind         koz        gold          NaN
161     2667  contained   meas_ind         koz        gold          NaN
162    48279  contained   meas_ind         koz      silver          NaN
163     80 %  contained   meas_ind         NaN         NaN          NaN
164     80 %        NaN   meas_ind         NaN         NaN          NaN
165    48782    tonnage   inferred          kt         NaN          NaN
166    48782    tonnage   inferred          kt         NaN          NaN
167    48782    tonnage   inferred          kt         NaN          NaN
168     0.72      grade   inferred         NaN      copper          NaN
169     0.15      grade   inferred         g/t        gold          NaN
170     0.15      grade   inferred         g/t        gold          NaN
171     2.01      grade   inferred         g/t      silver          NaN
172     2.01      grade   inferred         g/t      silver          NaN
173      349  contained   inferred          kt      copper          NaN
174      349  contained   inferred          kt      copper          NaN
175      234  contained   inferred         koz        gold          NaN
176      234  contained   inferred         koz        gold          NaN
177     3156  contained   inferred         koz      silver          NaN
178     80 %  contained   inferred         NaN         NaN          NaN
179     80 %        NaN   inferred         NaN         NaN          NaN
180     80 %  contained   measured         NaN         NaN    stockpile
181     80 %        NaN   measured         NaN         NaN    stockpile
182    86187    tonnage  indicated          kt         NaN          NaN
183    86187    tonnage  indicated          kt         NaN          NaN
184    86187    tonnage  indicated          kt         NaN          NaN
185     0.29      grade  indicated         NaN      copper          NaN
186     0.09      grade  indicated         g/t        gold          NaN
187     0.09      grade  indicated         g/t        gold          NaN
188     1.20      grade  indicated         g/t      silver          NaN
189     1.20      grade  indicated         g/t      silver          NaN
190      246  contained  indicated          kt      copper          NaN
191      246  contained  indicated          kt      copper          NaN
192      238  contained  indicated         koz        gold          NaN
193      238  contained  indicated         koz        gold          NaN
194     3325  contained  indicated         koz      silver          NaN
195     80 %  contained  indicated         NaN         NaN          NaN
196     80 %        NaN  indicated         NaN         NaN          NaN
197    86187    tonnage   meas_ind          kt         NaN          NaN
198    86187    tonnage   meas_ind          kt         NaN          NaN
199    86187    tonnage   meas_ind          kt         NaN          NaN
200     0.29      grade   meas_ind         NaN      copper          NaN
201     0.09      grade   meas_ind         g/t        gold          NaN
202     0.09      grade   meas_ind         g/t        gold          NaN
203     1.20      grade   meas_ind         g/t      silver          NaN
204     1.20      grade   meas_ind         g/t      silver          NaN
205      246  contained   meas_ind          kt      copper          NaN
206      246  contained   meas_ind          kt      copper          NaN
207      238  contained   meas_ind         koz        gold          NaN
208      238  contained   meas_ind         koz        gold          NaN
209     3325  contained   meas_ind         koz      silver          NaN
210     80 %  contained   meas_ind         NaN         NaN          NaN
211     80 %        NaN   meas_ind         NaN         NaN          NaN
212     80 %  contained   inferred         NaN         NaN          NaN
213     80 %        NaN   inferred         NaN         NaN          NaN
214    51494    tonnage   measured          kt         NaN          NaN
215    51494    tonnage   measured          kt         NaN          NaN
216    51494    tonnage   measured          kt         NaN          NaN
217     0.94      grade   measured         NaN      copper          NaN
218     0.22      grade   measured         g/t        gold          NaN
219     0.22      grade   measured         g/t        gold          NaN
220     1.96      grade   measured         g/t      silver          NaN
221     1.96      grade   measured         g/t      silver          NaN
222      484  contained   measured          kt      copper          NaN
223      484  contained   measured          kt      copper          NaN
224      364  contained   measured         koz        gold          NaN
225      364  contained   measured         koz        gold          NaN
226     3245  contained   measured         koz      silver          NaN
227     80 %  contained   measured         NaN         NaN          NaN
228     80 %        NaN   measured         NaN         NaN          NaN
229    53888    tonnage  indicated          kt         NaN  underground
230    53888    tonnage  indicated          kt         NaN  underground
231    53888    tonnage  indicated          kt         NaN  underground
232     0.83      grade  indicated         NaN      copper  underground
233     0.18      grade  indicated         g/t        gold  underground
234     0.18      grade  indicated         g/t        gold  underground
235     1.96      grade  indicated         g/t      silver  underground
236     1.96      grade  indicated         g/t      silver  underground
237      448  contained  indicated          kt      copper  underground
238      448  contained  indicated          kt      copper  underground
239      315  contained  indicated         koz        gold  underground
240      315  contained  indicated         koz        gold  underground
241     3401  contained  indicated         koz      silver  underground
242     80 %  contained  indicated         NaN         NaN  underground
243     80 %        NaN  indicated         NaN         NaN  underground
244   105382    tonnage   meas_ind          kt         NaN          NaN
245   105382    tonnage   meas_ind          kt         NaN          NaN
246   105382    tonnage   meas_ind          kt         NaN          NaN
247     0.88      grade   meas_ind         NaN      copper          NaN
248     0.20      grade   meas_ind         g/t        gold          NaN
249     0.20      grade   meas_ind         g/t        gold          NaN
250     1.96      grade   meas_ind         g/t      silver          NaN
251     1.96      grade   meas_ind         g/t      silver          NaN
252      932  contained   meas_ind          kt      copper          NaN
253      932  contained   meas_ind          kt      copper          NaN
254      680  contained   meas_ind         koz        gold          NaN
255      680  contained   meas_ind         koz        gold          NaN
256     6646  contained   meas_ind         koz      silver          NaN
257     80 %  contained   meas_ind         NaN         NaN          NaN
258     80 %        NaN   meas_ind         NaN         NaN          NaN
259    23963    tonnage   inferred          kt         NaN          NaN
260    23963    tonnage   inferred          kt         NaN          NaN
261    23963    tonnage   inferred          kt         NaN          NaN
262     0.89      grade   inferred         NaN      copper          NaN
263     0.18      grade   inferred         g/t        gold          NaN
264     0.18      grade   inferred         g/t        gold          NaN
265     2.48      grade   inferred         g/t      silver          NaN
266     2.48      grade   inferred         g/t      silver          NaN
267      213  contained   inferred          kt      copper          NaN
268      213  contained   inferred          kt      copper          NaN
269      142  contained   inferred         koz        gold          NaN
270      142  contained   inferred         koz        gold          NaN
271     1908  contained   inferred         koz      silver          NaN
272     80 %  contained   inferred         NaN         NaN          NaN
273     80 %        NaN   inferred         NaN         NaN          NaN
274   795303    tonnage   measured          kt         NaN          NaN
275   795303    tonnage   measured          kt         NaN          NaN

file:///home/ravi/work/mining/project/articles/February202618c1164.html
6

     value     metric   oretype   category commodity measurement
0     50 %  contained     oxide   measured      gold         NaN
1      301    tonnage     oxide  indicated      gold         NaN
2      301    tonnage     oxide  indicated      gold         NaN
3      301    tonnage     oxide  indicated      gold         NaN
4     0.25        NaN     oxide  indicated      gold         g/t
5     0.25      grade     oxide  indicated      gold         g/t
6     0.25      grade     oxide  indicated      gold         g/t
7      2.7      grade     oxide  indicated      gold         g/t
8      2.7      grade     oxide  indicated      gold         g/t
9      2.7        NaN     oxide  indicated      gold         g/t
10     2.4        NaN     oxide  indicated      gold         NaN
11     2.4  contained     oxide  indicated      gold         NaN
12      26  contained     oxide  indicated      gold         NaN
13    50 %  contained     oxide  indicated      gold         NaN
14     301    tonnage       NaN   meas_ind       NaN         NaN
15     301    tonnage       NaN   meas_ind       NaN         NaN
16     301    tonnage       NaN   meas_ind       NaN         NaN
17    0.25        NaN       NaN   meas_ind      gold         g/t
18    0.25      grade       NaN   meas_ind      gold         g/t
19    0.25      grade       NaN   meas_ind      gold         g/t
20     2.7      grade       NaN   meas_ind    silver         g/t
21     2.7      grade       NaN   meas_ind    silver         g/t
22     2.7        NaN       NaN   meas_ind    silver         g/t
23     2.4        NaN       NaN   meas_ind      gold         NaN
24     2.4  contained       NaN   meas_ind      gold         NaN
25      26  contained       NaN   meas_ind    silver         NaN
26    50 %  contained       NaN   meas_ind       NaN         NaN
27     711    tonnage       NaN   inferred       NaN         NaN
28     711    tonnage       NaN   inferred       NaN         NaN
29     711    tonnage       NaN   inferred       NaN         NaN
30    0.18        NaN       NaN   inferred      gold         g/t
31    0.18      grade       NaN   inferred      gold         g/t
32    0.18      grade       NaN   inferred      gold         g/t
33     3.0      grade       NaN   inferred    silver         g/t
34     3.0      grade       NaN   inferred    silver         g/t
35     3.0        NaN       NaN   inferred    silver         g/t
36     4.1        NaN       NaN   inferred      gold         NaN
37     4.1  contained       NaN   inferred      gold         NaN
38      69  contained       NaN   inferred    silver         NaN
39    50 %  contained       NaN   inferred       NaN         NaN
40    50 %  contained     oxide   measured    copper         NaN
41     467    tonnage     oxide  indicated    copper         NaN
42     467    tonnage     oxide  indicated    copper         NaN
43     467    tonnage     oxide  indicated    copper         NaN
44    0.32        NaN     oxide  indicated    copper         NaN
45    0.32        NaN     oxide  indicated    copper         NaN
46    0.27        NaN     oxide  indicated    copper         g/t
47    0.27      grade     oxide  indicated    copper         g/t
48    0.27      grade     oxide  indicated    copper         g/t
49     2.5      grade     oxide  indicated    copper         g/t
50     2.5      grade     oxide  indicated    copper         g/t
51     2.5        NaN     oxide  indicated    copper         g/t
52    1474        NaN     oxide  indicated    copper          kt
53    1474        NaN     oxide  indicated    copper          kt
54    1474        NaN     oxide  indicated    copper          kt
55    1474        NaN     oxide  indicated    copper          kt
56     4.1        NaN     oxide  indicated    copper         NaN
57     4.1  contained     oxide  indicated    copper         NaN
58      38  contained     oxide  indicated    copper         NaN
59    50 %  contained     oxide  indicated    copper         NaN
60     467    tonnage       NaN   meas_ind       NaN         NaN
61     467    tonnage       NaN   meas_ind       NaN         NaN
62     467    tonnage       NaN   meas_ind       NaN         NaN
63    0.32        NaN       NaN   meas_ind    copper         NaN
64    0.32        NaN       NaN   meas_ind    copper         NaN
65    0.27        NaN       NaN   meas_ind      gold         g/t
66    0.27      grade       NaN   meas_ind      gold         g/t
67    0.27      grade       NaN   meas_ind      gold         g/t
68     2.5      grade       NaN   meas_ind    silver         g/t
69     2.5      grade       NaN   meas_ind    silver         g/t
70     2.5        NaN       NaN   meas_ind    silver         g/t
71    1474        NaN       NaN   meas_ind    copper          kt
72    1474        NaN       NaN   meas_ind    copper          kt
73    1474        NaN       NaN   meas_ind    copper          kt
74    1474        NaN       NaN   meas_ind    copper          kt
75     4.1        NaN       NaN   meas_ind      gold         NaN
76     4.1  contained       NaN   meas_ind      gold         NaN
77      38  contained       NaN   meas_ind    silver         NaN
78    50 %  contained       NaN   meas_ind       NaN         NaN
79     431    tonnage       NaN   inferred       NaN         NaN
80     431    tonnage       NaN   inferred       NaN         NaN
81     431    tonnage       NaN   inferred       NaN         NaN
82    0.23        NaN       NaN   inferred    copper         NaN
83    0.23        NaN       NaN   inferred    copper         NaN
84    0.20        NaN       NaN   inferred      gold         g/t
85    0.20      grade       NaN   inferred      gold         g/t
86    0.20      grade       NaN   inferred      gold         g/t
87     2.2      grade       NaN   inferred    silver         g/t
88     2.2      grade       NaN   inferred    silver         g/t
89     2.2        NaN       NaN   inferred    silver         g/t
90     982        NaN       NaN   inferred    copper          kt
91     982        NaN       NaN   inferred    copper          kt
92     982        NaN       NaN   inferred    copper          kt
93     982        NaN       NaN   inferred    copper          kt
94     2.7        NaN       NaN   inferred      gold         NaN
95     2.7  contained       NaN   inferred      gold         NaN
96      30  contained       NaN   inferred    silver         NaN
97    50 %  contained       NaN   inferred       NaN         NaN
98    50 %  contained     oxide   measured    silver         NaN
99      71    tonnage     oxide  indicated    silver         NaN
100     71    tonnage     oxide  indicated    silver         NaN
101     71    tonnage     oxide  indicated    silver         NaN
102   0.36        NaN     oxide  indicated    silver         NaN
103   0.36        NaN     oxide  indicated    silver         NaN
104   0.36        NaN     oxide  indicated    silver         g/t
105   0.36      grade     oxide  indicated    silver         g/t
106   0.36      grade     oxide  indicated    silver         g/t
107  119.7      grade     oxide  indicated    silver         g/t
108  119.7      grade     oxide  indicated    silver         g/t
109  119.7        NaN     oxide  indicated    silver         g/t
110    254        NaN     oxide  indicated    silver          kt
111    254        NaN     oxide  indicated    silver          kt
112    254        NaN     oxide  indicated    silver          kt
113    254        NaN     oxide  indicated    silver          kt
114    0.8        NaN     oxide  indicated    silver         NaN
115    0.8  contained     oxide  indicated    silver         NaN
116    272  contained     oxide  indicated    silver         NaN
117   50 %  contained     oxide  indicated    silver         NaN
118     71    tonnage       NaN   meas_ind       NaN         NaN
119     71    tonnage       NaN   meas_ind       NaN         NaN
120     71    tonnage       NaN   meas_ind       NaN         NaN
121   0.36        NaN       NaN   meas_ind    copper         NaN
122   0.36        NaN       NaN   meas_ind    copper         NaN
123   0.36        NaN       NaN   meas_ind      gold         g/t
124   0.36      grade       NaN   meas_ind      gold         g/t
125   0.36      grade       NaN   meas_ind      gold         g/t
126  119.7      grade       NaN   meas_ind    silver         g/t
127  119.7      grade       NaN   meas_ind    silver         g/t
128  119.7        NaN       NaN   meas_ind    silver         g/t
129    254        NaN       NaN   meas_ind    copper          kt
130    254        NaN       NaN   meas_ind    copper          kt
131    254        NaN       NaN   meas_ind    copper          kt
132    254        NaN       NaN   meas_ind    copper          kt
133    0.8        NaN       NaN   meas_ind      gold         NaN
134    0.8  contained       NaN   meas_ind      gold         NaN
135    272  contained       NaN   meas_ind    silver         NaN
136   50 %  contained       NaN   meas_ind       NaN         NaN
137     95    tonnage       NaN   inferred       NaN         NaN
138     95    tonnage       NaN   inferred       NaN         NaN
139     95    tonnage       NaN   inferred       NaN         NaN
140   0.08        NaN       NaN   inferred    copper         NaN
141   0.08        NaN       NaN   inferred    copper         NaN
142   0.14        NaN       NaN   inferred      gold         g/t
143   0.14      grade       NaN   inferred      gold         g/t
144   0.14      grade       NaN   inferred      gold         g/t
145   35.1      grade       NaN   inferred    silver         g/t
146   35.1      grade       NaN   inferred    silver         g/t
147   35.1        NaN       NaN   inferred    silver         g/t
148     75        NaN       NaN   inferred    copper          kt
149     75        NaN       NaN   inferred    copper          kt
150     75        NaN       NaN   inferred    copper          kt
151     75        NaN       NaN   inferred    copper          kt
152    0.4        NaN       NaN   inferred      gold         NaN
153    0.4  contained       NaN   inferred      gold         NaN
154    108  contained       NaN   inferred    silver         NaN
155   50 %  contained       NaN   inferred       NaN         NaN
156   50 %  contained  sulphide   measured       NaN         NaN
157   1733    tonnage  sulphide  indicated       NaN         NaN
158   1733    tonnage  sulphide  indicated       NaN         NaN
159   1733    tonnage  sulphide  indicated       NaN         NaN
160   0.46        NaN  sulphide  indicated    copper         NaN
161   0.46        NaN  sulphide  indicated    copper         NaN
162   0.34        NaN  sulphide  indicated      gold         g/t
163   0.34      grade  sulphide  indicated      gold         g/t
164   0.34      grade  sulphide  indicated      gold         g/t
165    6.0      grade  sulphide  indicated    silver         g/t
166    6.0      grade  sulphide  indicated    silver         g/t
167    6.0        NaN  sulphide  indicated    silver         g/t
168   8031        NaN  sulphide  indicated    copper          kt
169   8031        NaN  sulphide  indicated    copper          kt
170   8031        NaN  sulphide  indicated    copper          kt
171   8031        NaN  sulphide  indicated    copper          kt
172   19.2        NaN  sulphide  indicated      gold         NaN
173   19.2  contained  sulphide  indicated      gold         NaN
174    336  contained  sulphide  indicated    silver         NaN
175   50 %  contained  sulphide  indicated       NaN         NaN
176   1733    tonnage       NaN   meas_ind       NaN         NaN
177   1733    tonnage       NaN   meas_ind       NaN         NaN
178   1733    tonnage       NaN   meas_ind       NaN         NaN
179   0.46        NaN       NaN   meas_ind    copper         NaN
180   0.46        NaN       NaN   meas_ind    copper         NaN
181   0.34        NaN       NaN   meas_ind      gold         g/t
182   0.34      grade       NaN   meas_ind      gold         g/t
183   0.34      grade       NaN   meas_ind      gold         g/t
184    6.0      grade       NaN   meas_ind    silver         g/t
185    6.0      grade       NaN   meas_ind    silver         g/t
186    6.0        NaN       NaN   meas_ind    silver         g/t
187   8031        NaN       NaN   meas_ind    copper          kt
188   8031        NaN       NaN   meas_ind    copper          kt
189   8031        NaN       NaN   meas_ind    copper          kt
190   8031        NaN       NaN   meas_ind    copper          kt
191   19.2        NaN       NaN   meas_ind      gold         NaN
192   19.2  contained       NaN   meas_ind      gold         NaN
193    336  contained       NaN   meas_ind    silver         NaN
194   50 %  contained       NaN   meas_ind       NaN         NaN
195   8721    tonnage       NaN   inferred       NaN         NaN
196   8721    tonnage       NaN   inferred       NaN         NaN
197   8721    tonnage       NaN   inferred       NaN         NaN
198   0.34        NaN       NaN   inferred    copper         NaN
199   0.34        NaN       NaN   inferred    copper         NaN
200   0.18        NaN       NaN   inferred      gold         g/t
201   0.18      grade       NaN   inferred      gold         g/t
202   0.18      grade       NaN   inferred      gold         g/t
203    2.9      grade       NaN   inferred    silver         g/t
204    2.9      grade       NaN   inferred    silver         g/t
205    2.9        NaN       NaN   inferred    silver         g/t
206  29683        NaN       NaN   inferred    copper          kt
207  29683        NaN       NaN   inferred    copper          kt
208  29683        NaN       NaN   inferred    copper          kt
209  29683        NaN       NaN   inferred    copper          kt
210   51.5        NaN       NaN   inferred      gold         NaN
211   51.5  contained       NaN   inferred      gold         NaN
212    823  contained       NaN   inferred    silver         NaN
213   50 %  contained       NaN   inferred       NaN         NaN
214   50 %  contained       NaN   measured       NaN         NaN
215   2572    tonnage       NaN  indicated       NaN         NaN
216   2572    tonnage       NaN  indicated       NaN         NaN
217   2572    tonnage       NaN  indicated       NaN         NaN
218   0.38        NaN       NaN  indicated    copper         NaN
219   0.38        NaN       NaN  indicated    copper         NaN
220   0.32        NaN       NaN  indicated      gold         g/t
221   0.32      grade       NaN  indicated      gold         g/t
222   0.32      grade       NaN  indicated      gold         g/t
223    8.1      grade       NaN  indicated    silver         g/t
224    8.1      grade       NaN  indicated    silver         g/t
225    8.1        NaN       NaN  indicated    silver         g/t
226   9759        NaN       NaN  indicated    copper          kt
227   9759        NaN       NaN  indicated    copper          kt
228   9759        NaN       NaN  indicated    copper          kt
229   9759        NaN       NaN  indicated    copper          kt
230   26.5        NaN       NaN  indicated      gold         NaN
231   26.5  contained       NaN  indicated      gold         NaN
232    672  contained       NaN  indicated    silver         NaN
233   50 %  contained       NaN  indicated       NaN         NaN
234   2572    tonnage       NaN   meas_ind       NaN         NaN
235   2572    tonnage       NaN   meas_ind       NaN         NaN
236   2572    tonnage       NaN   meas_ind       NaN         NaN
237   0.38        NaN       NaN   meas_ind    copper         NaN
238   0.38        NaN       NaN   meas_ind    copper         NaN
239   0.32        NaN       NaN   meas_ind      gold         g/t
240   0.32      grade       NaN   meas_ind      gold         g/t
241   0.32      grade       NaN   meas_ind      gold         g/t
242    8.1      grade       NaN   meas_ind    silver         g/t
243    8.1      grade       NaN   meas_ind    silver         g/t
244    8.1        NaN       NaN   meas_ind    silver         g/t
245   9759        NaN       NaN   meas_ind    copper          kt
246   9759        NaN       NaN   meas_ind    copper          kt
247   9759        NaN       NaN   meas_ind    copper          kt
248   9759        NaN       NaN   meas_ind    copper          kt
249   26.5        NaN       NaN   meas_ind      gold         NaN
250   26.5  contained       NaN   meas_ind      gold         NaN
251    672  contained       NaN   meas_ind    silver         NaN
252   50 %  contained       NaN   meas_ind       NaN         NaN
253   9958    tonnage       NaN   inferred       NaN         NaN
254   9958    tonnage       NaN   inferred       NaN         NaN
255   9958    tonnage       NaN   inferred       NaN         NaN
256   0.31        NaN       NaN   inferred    copper         NaN
257   0.31        NaN       NaN   inferred    copper         NaN
258   0.18        NaN       NaN   inferred      gold         g/t
259   0.18      grade       NaN   inferred      gold         g/t
260   0.18      grade       NaN   inferred      gold         g/t
261    3.2      grade       NaN   inferred    silver         g/t
262    3.2      grade       NaN   inferred    silver         g/t
263    3.2        NaN       NaN   inferred    silver         g/t
264  30740        NaN       NaN   inferred    copper          kt
265  30740        NaN       NaN   inferred    copper          kt
266  30740        NaN       NaN   inferred    copper          kt
267  30740        NaN       NaN   inferred    copper          kt
268   58.7        NaN       NaN   inferred      gold         NaN
269   58.7  contained       NaN   inferred      gold         NaN
270   1030  contained       NaN   inferred    silver         NaN
271   50 %  contained       NaN   inferred       NaN         NaN
272    648    tonnage       NaN   measured       NaN         NaN
273    648    tonnage       NaN   measured       NaN         NaN
274    648    tonnage       NaN   measured       NaN         NaN
275   0.33        NaN       NaN   measured    copper         NaN
276   0.33        NaN       NaN   measured    copper         NaN
277   0.25        NaN       NaN   measured      gold         g/t
278   0.25      grade       NaN   measured      gold         g/t
279   0.25      grade       NaN   measured      gold         g/t
280    1.2      grade       NaN   measured    silver         g/t
281    1.2      grade       NaN   measured    silver         g/t
282    1.2        NaN       NaN   measured    silver         g/t
283   2143        NaN       NaN   measured    copper          kt
284   2143        NaN       NaN   measured    copper          kt
285   2143        NaN       NaN   measured    copper          kt
286   2143        NaN       NaN   measured    copper          kt
287    5.2        NaN       NaN   measured      gold         NaN
288    5.2  contained       NaN   measured      gold         NaN
289     25  contained       NaN   measured    silver         NaN
290   50 %  contained       NaN   measured       NaN         NaN
291    961    tonnage       NaN  indicated       NaN         NaN
292    961    tonnage       NaN  indicated       NaN         NaN
293    961    tonnage       NaN  indicated       NaN         NaN
294   0.25        NaN       NaN  indicated    copper         NaN
295   0.25        NaN       NaN  indicated    copper         NaN
296   0.15        NaN       NaN  indicated      gold         g/t
297   0.15      grade       NaN  indicated      gold         g/t
298   0.15      grade       NaN  indicated      gold         g/t
299    1.1      grade       NaN  indicated    silver         g/t
300    1.1      grade       NaN  indicated    silver         g/t
301    1.1        NaN       NaN  indicated    silver         g/t
302   2436        NaN       NaN  indicated    copper          kt
303   2436        NaN       NaN  indicated    copper          kt
304   2436        NaN       NaN  indicated    copper          kt
305   2436        NaN       NaN  indicated    copper          kt

file:///home/ravi/work/mining/project/articles/February202618c1164.html
7

       value     metric  category measurement   commodity     minetype processtype
0     269001    tonnage    proven          kt         NaN          NaN         NaN
1       0.45        NaN    proven         NaN      copper          NaN         NaN
2       0.11      grade    proven         g/t        gold          NaN         NaN
3       1.37      grade    proven         g/t      silver          NaN         NaN
4       1.37  contained    proven         g/t      silver          NaN         NaN
5       1208  contained    proven          kt      copper          NaN         NaN
6        917  contained    proven         koz        gold          NaN         NaN
7      11823  contained    proven         koz      silver          NaN         NaN
8       80 %  contained    proven         NaN         NaN          NaN         NaN
9       80 %        NaN    proven         NaN         NaN          NaN         NaN
10     24372    tonnage  probable          kt         NaN     open pit         NaN
11      0.29        NaN  probable         NaN      copper     open pit         NaN
12      0.08      grade  probable         g/t        gold     open pit         NaN
13      1.09      grade  probable         g/t      silver     open pit         NaN
14      1.09  contained  probable         g/t      silver     open pit         NaN
15        70  contained  probable          kt      copper     open pit         NaN
16        63  contained  probable         koz        gold     open pit         NaN
17       853  contained  probable         koz      silver     open pit         NaN
18      80 %  contained  probable         NaN         NaN     open pit         NaN
19      80 %        NaN  probable         NaN         NaN     open pit         NaN
20    293373    tonnage       NaN          kt         NaN          NaN         NaN
21      0.44        NaN       NaN         NaN      copper          NaN         NaN
22      0.10      grade       NaN         g/t        gold          NaN         NaN
23      1.34      grade       NaN         g/t      silver          NaN         NaN
24      1.34  contained       NaN         g/t      silver          NaN         NaN
25      1278  contained       NaN          kt      copper          NaN         NaN
26       979  contained       NaN         koz        gold          NaN         NaN
27     12676  contained       NaN         koz      silver          NaN         NaN
28      80 %  contained       NaN         NaN         NaN          NaN         NaN
29     52454    tonnage    proven          kt   lanthanum          NaN         NaN
30      0.40        NaN    proven         NaN      copper          NaN         NaN
31      0.08      grade    proven         g/t        gold          NaN         NaN
32      0.34      grade    proven         g/t      silver          NaN         NaN
33      0.34  contained    proven         g/t      silver          NaN         NaN
34       209  contained    proven          kt      copper          NaN         NaN
35       138  contained    proven         koz        gold          NaN         NaN
36       567  contained    proven         koz      silver          NaN         NaN
37      80 %  contained    proven         NaN   lanthanum          NaN         NaN
38      80 %        NaN    proven         NaN   lanthanum          NaN         NaN
39     64326    tonnage  probable          kt         NaN          NaN         NaN
40      0.36        NaN  probable         NaN      copper          NaN         NaN
41      0.07      grade  probable         g/t        gold          NaN         NaN
42      0.32      grade  probable         g/t      silver          NaN         NaN
43      0.32  contained  probable         g/t      silver          NaN         NaN
44       231  contained  probable          kt      copper          NaN         NaN
45       136  contained  probable         koz        gold          NaN         NaN
46       668  contained  probable         koz      silver          NaN         NaN
47      80 %  contained  probable         NaN         NaN          NaN         NaN
48      80 %        NaN  probable         NaN         NaN          NaN         NaN
49    116780    tonnage       NaN          kt         NaN          NaN         NaN
50      0.38        NaN       NaN         NaN      copper          NaN         NaN
51      0.07      grade       NaN         g/t        gold          NaN         NaN
52      0.33      grade       NaN         g/t      silver          NaN         NaN
53      0.33  contained       NaN         g/t      silver          NaN         NaN
54       440  contained       NaN          kt      copper          NaN         NaN
55       275  contained       NaN         koz        gold          NaN         NaN
56      1235  contained       NaN         koz      silver          NaN         NaN
57      80 %  contained       NaN         NaN         NaN          NaN         NaN
58     20999    tonnage    proven          kt         NaN  underground         NaN
59      0.85        NaN    proven         NaN      copper  underground         NaN
60      0.19      grade    proven         g/t        gold  underground         NaN
61      3.33      grade    proven         g/t      silver  underground         NaN
62      3.33  contained    proven         g/t      silver  underground         NaN
63       177  contained    proven          kt      copper  underground         NaN
64       131  contained    proven         koz        gold  underground         NaN
65      2248  contained    proven         koz      silver  underground         NaN
66      80 %  contained    proven         NaN         NaN  underground         NaN
67      80 %        NaN    proven         NaN         NaN  underground         NaN
68     62817    tonnage  probable          kt         NaN          NaN         NaN
69      0.78        NaN  probable         NaN      copper          NaN         NaN
70      0.17      grade  probable         g/t        gold          NaN         NaN
71      3.29      grade  probable         g/t      silver          NaN         NaN
72      3.29  contained  probable         g/t      silver          NaN         NaN
73       490  contained  probable          kt      copper          NaN         NaN
74       343  contained  probable         koz        gold          NaN         NaN
75      6653  contained  probable         koz      silver          NaN         NaN
76      80 %  contained  probable         NaN         NaN          NaN         NaN
77      80 %        NaN  probable         NaN         NaN          NaN         NaN
78     83816    tonnage       NaN          kt         NaN          NaN         NaN
79      0.80        NaN       NaN         NaN      copper          NaN         NaN
80      0.18      grade       NaN         g/t        gold          NaN         NaN
81      3.30      grade       NaN         g/t      silver          NaN         NaN
82      3.30  contained       NaN         g/t      silver          NaN         NaN
83       667  contained       NaN          kt      copper          NaN         NaN
84       474  contained       NaN         koz        gold          NaN         NaN
85      8901  contained       NaN         koz      silver          NaN         NaN
86      80 %  contained       NaN         NaN         NaN          NaN         NaN
87      80 %  contained    proven         NaN         NaN    stockpile         NaN
88      80 %        NaN    proven         NaN         NaN    stockpile         NaN
89     86187    tonnage  probable          kt         NaN          NaN         NaN
90      0.29        NaN  probable         NaN      copper          NaN         NaN
91      0.09      grade  probable         g/t        gold          NaN         NaN
92      1.20      grade  probable         g/t      silver          NaN         NaN
93      1.20  contained  probable         g/t      silver          NaN         NaN
94       246  contained  probable          kt      copper          NaN         NaN
95       238  contained  probable         koz        gold          NaN         NaN
96      3325  contained  probable         koz      silver          NaN         NaN
97      80 %  contained  probable         NaN         NaN          NaN         NaN
98      80 %        NaN  probable         NaN         NaN          NaN         NaN
99     86187    tonnage       NaN          kt         NaN          NaN         NaN
100     0.29        NaN       NaN         NaN      copper          NaN         NaN
101     0.09      grade       NaN         g/t        gold          NaN         NaN
102     1.20      grade       NaN         g/t      silver          NaN         NaN
103     1.20  contained       NaN         g/t      silver          NaN         NaN
104      246  contained       NaN          kt      copper          NaN         NaN
105      238  contained       NaN         koz        gold          NaN         NaN
106     3325  contained       NaN         koz      silver          NaN         NaN
107     80 %  contained       NaN         NaN         NaN          NaN         NaN
108     2984    tonnage    proven          kt         NaN          NaN         NaN
109     0.84        NaN    proven         NaN      copper          NaN         NaN
110     0.21      grade    proven         g/t        gold          NaN         NaN
111     1.97      grade    proven         g/t      silver          NaN         NaN
112     1.97  contained    proven         g/t      silver          NaN         NaN
113       25  contained    proven          kt      copper          NaN         NaN
114       20  contained    proven         koz        gold          NaN         NaN
115      189  contained    proven         koz      silver          NaN         NaN
116     80 %  contained    proven         NaN         NaN          NaN         NaN
117     80 %        NaN    proven         NaN         NaN          NaN         NaN
118     9572    tonnage  probable          kt         NaN  underground         NaN
119     0.83        NaN  probable         NaN      copper  underground         NaN
120     0.17      grade  probable         g/t        gold  underground         NaN
121     2.13      grade  probable         g/t      silver  underground         NaN
122     2.13  contained  probable         g/t      silver  underground         NaN
123       80  contained  probable          kt      copper  underground         NaN
124       54  contained  probable         koz        gold  underground         NaN
125      656  contained  probable         koz      silver  underground         NaN
126     80 %  contained  probable         NaN         NaN  underground         NaN
127     80 %        NaN  probable         NaN         NaN  underground         NaN
128    12556    tonnage       NaN          kt         NaN          NaN         NaN
129     0.83        NaN       NaN         NaN      copper          NaN         NaN
130     0.18      grade       NaN         g/t        gold          NaN         NaN
131     2.09      grade       NaN         g/t      silver          NaN         NaN
132     2.09  contained       NaN         g/t      silver          NaN         NaN
133      105  contained       NaN          kt      copper          NaN         NaN
134       73  contained       NaN         koz        gold          NaN         NaN
135      845  contained       NaN         koz      silver          NaN         NaN
136     80 %  contained       NaN         NaN         NaN          NaN         NaN
137   345438    tonnage    proven          kt         NaN          NaN         NaN
138     0.47        NaN    proven         NaN      copper          NaN         NaN
139     0.11      grade    proven         g/t        gold          NaN         NaN
140     1.34      grade    proven         g/t      silver          NaN         NaN
141     1.34  contained    proven         g/t      silver          NaN         NaN
142     1619  contained    proven          kt      copper          NaN         NaN
143     1206  contained    proven         koz        gold          NaN         NaN
144    14827  contained    proven         koz      silver          NaN         NaN
145     80 %  contained    proven         NaN         NaN          NaN         NaN
146     80 %        NaN    proven         NaN         NaN          NaN         NaN
147   247274    tonnage  probable          kt         NaN          NaN         NaN
148     0.45        NaN  probable         NaN      copper          NaN         NaN
149     0.10      grade  probable         g/t        gold          NaN         NaN
150     1.53      grade  probable         g/t      silver          NaN         NaN
151     1.53  contained  probable         g/t      silver          NaN         NaN
152     1117  contained  probable          kt      copper          NaN         NaN
153      834  contained  probable         koz        gold          NaN         NaN
154    12155  contained  probable         koz      silver          NaN         NaN
155     80 %  contained  probable         NaN         NaN          NaN         NaN
156     80 %        NaN  probable         NaN         NaN          NaN         NaN
157   592712    tonnage       NaN          kt         NaN          NaN         NaN
158     0.46        NaN       NaN         NaN      copper          NaN         NaN
159     0.11      grade       NaN         g/t        gold          NaN         NaN
160     1.42      grade       NaN         g/t      silver          NaN         NaN
161     1.42  contained       NaN         g/t      silver          NaN         NaN
162     2736  contained       NaN          kt      copper          NaN         NaN
163     2040  contained       NaN         koz        gold          NaN         NaN
164    26981  contained       NaN         koz      silver          NaN         NaN
165     80 %  contained       NaN         NaN         NaN          NaN         NaN
166   218883    tonnage    proven          kt         NaN          NaN         NaN
167     0.36        NaN    proven         NaN      copper          NaN         NaN
168      124  contained    proven         ppm  molybdenum          NaN         NaN
169      797  contained    proven          kt      copper          NaN         NaN
170       27  contained    proven          kt  molybdenum          NaN         NaN
171     70 %  contained    proven         NaN         NaN          NaN         NaN
172     70 %        NaN    proven         NaN         NaN          NaN         NaN
173   302930    tonnage  probable          kt         NaN          NaN         NaN
174     0.31        NaN  probable         NaN      copper          NaN         NaN
175      117  contained  probable         ppm  molybdenum          NaN         NaN
176      939  contained  probable          kt      copper          NaN         NaN
177       35  contained  probable          kt  molybdenum          NaN         NaN
178     70 %  contained  probable         NaN         NaN          NaN         NaN
179     70 %        NaN  probable         NaN         NaN          NaN         NaN
180   521813    tonnage       NaN          kt         NaN          NaN         NaN
181     0.33        NaN       NaN         NaN      copper          NaN         NaN
182      120  contained       NaN         ppm  molybdenum          NaN         NaN
183     1736  contained       NaN          kt      copper          NaN         NaN
184       63  contained       NaN          kt  molybdenum          NaN         NaN
185     70 %  contained       NaN         NaN         NaN          NaN         NaN
186    91229    tonnage    proven          kt         NaN          NaN  dump leach
187     0.28        NaN    proven         NaN      copper          NaN  dump leach
188      255  contained    proven          kt      copper          NaN  dump leach
189     70 %  contained    proven         NaN         NaN          NaN  dump leach
190     70 %        NaN    proven         NaN         NaN          NaN  dump leach
191   184028    tonnage  probable          kt         NaN          NaN         NaN
192     0.21        NaN  probable         NaN      copper          NaN         NaN
193      386  contained  probable          kt      copper          NaN         NaN
194     70 %  contained  probable         NaN         NaN          NaN         NaN
195     70 %        NaN  probable         NaN         NaN          NaN         NaN
196   275257    tonnage       NaN          kt         NaN          NaN         NaN
197     0.23        NaN       NaN         NaN      copper          NaN         NaN
198      641  contained       NaN          kt      copper          NaN         NaN
199     70 %  contained       NaN         NaN         NaN          NaN         NaN
200   310112    tonnage    proven          kt         NaN          NaN         NaN
201     0.34        NaN    proven         NaN      copper          NaN         NaN
202      124  contained    proven         ppm  molybdenum          NaN         NaN
203     1051  contained    proven          kt      copper          NaN         NaN
204       27  contained    proven          kt  molybdenum          NaN         NaN
205     70 %  contained    proven         NaN         NaN          NaN         NaN
206     70 %        NaN    proven         NaN         NaN          NaN         NaN
207   486958    tonnage  probable          kt         NaN          NaN         NaN
208     0.27        NaN  probable         NaN      copper          NaN         NaN
209      117  contained  probable         ppm  molybdenum          NaN         NaN
210     1326  contained  probable          kt      copper          NaN         NaN
211       35  contained  probable          kt  molybdenum          NaN         NaN
212     70 %  contained  probable         NaN         NaN          NaN         NaN
213     70 %        NaN  probable         NaN         NaN          NaN         NaN
214   797070    tonnage       NaN          kt         NaN          NaN         NaN
215     0.30        NaN       NaN         NaN      copper          NaN         NaN
216      120  contained       NaN         ppm  molybdenum          NaN         NaN
217     2377  contained       NaN          kt      copper          NaN         NaN
218       63  contained       NaN          kt  molybdenum          NaN         NaN
219     70 %  contained       NaN         NaN         NaN          NaN         NaN
220   291237    tonnage    proven          kt         NaN          NaN         NaN
221     0.25        NaN    proven         NaN      copper          NaN         NaN
222     0.14      grade    proven         g/t        gold          NaN         NaN
223      740  contained    proven          kt      copper          NaN         NaN
224     1311  contained    proven         koz        gold          NaN         NaN
225    100 %  contained    proven         NaN         NaN          NaN         NaN
226    100 %        NaN    proven         NaN         NaN          NaN         NaN
227   126092    tonnage  probable          kt         NaN     open pit         NaN
228     0.22        NaN  probable         NaN      copper     open pit         NaN
229     0.11      grade  probable         g/t        gold     open pit         NaN
230      274  contained  probable          kt      copper     open pit         NaN
231      430  contained  probable         koz        gold     open pit         NaN
232    100 %  contained  probable         NaN         NaN     open pit         NaN
233    100 %        NaN  probable         NaN         NaN     open pit         NaN
234   417329    tonnage       NaN          kt         NaN          NaN         NaN
235     0.24        NaN       NaN         NaN      copper          NaN         NaN
236     0.13      grade       NaN         g/t        gold          NaN         NaN
237     1013  contained       NaN          kt      copper          NaN         NaN
238     1741  contained       NaN         koz        gold          NaN         NaN

file:///home/ravi/work/mining/project/articles/February202618c1723.html
2

    value     metric     minetype   category commodity measurement
0    1.52    tonnage  underground   probable   arsenic         NaN
1    4.39        NaN  underground   probable   arsenic         g/t
2    0.21  contained  underground   probable   arsenic         NaN
3    2.63    tonnage  underground   probable   arsenic         NaN
4    4.24        NaN  underground   probable   arsenic         g/t
5    0.36  contained  underground   probable   arsenic         NaN
6    4.14    tonnage  underground  prov_prob   arsenic         NaN
7    4.29        NaN  underground  prov_prob   arsenic         g/t
8    0.57  contained  underground  prov_prob   arsenic         NaN
9    3.62    tonnage  underground   probable   arsenic         NaN
10   2.96        NaN  underground   probable   arsenic         g/t
11   0.34  contained  underground   probable   arsenic         NaN
12   3.62    tonnage  underground  prov_prob   arsenic         NaN
13   2.96        NaN  underground  prov_prob   arsenic         g/t
14   0.34  contained  underground  prov_prob   arsenic         NaN
15   4.00    tonnage  underground   probable   arsenic         NaN
16   3.39        NaN  underground   probable   arsenic         g/t
17   0.44  contained  underground   probable   arsenic         NaN
18   4.00    tonnage  underground  prov_prob   arsenic         NaN
19   3.39        NaN  underground  prov_prob   arsenic         g/t
20   0.44  contained  underground  prov_prob   arsenic         NaN
21   2.47    tonnage          NaN   probable   arsenic         NaN
22   1.23        NaN          NaN   probable   arsenic         g/t
23   0.10  contained          NaN   probable   arsenic         NaN
24   16.1    tonnage          NaN   probable   arsenic         NaN
25   1.62        NaN          NaN   probable   arsenic         g/t
26   0.84  contained          NaN   probable   arsenic         NaN
27   18.6    tonnage          NaN  prov_prob   arsenic         NaN
28   1.57        NaN          NaN  prov_prob   arsenic         g/t
29   0.94  contained          NaN  prov_prob   arsenic         NaN
30   3.99    tonnage          NaN   probable   arsenic         NaN
31   2.43        NaN          NaN   probable   arsenic         g/t
32   0.31  contained          NaN   probable   arsenic         NaN
33   26.3    tonnage          NaN   probable   arsenic         NaN
34   2.33        NaN          NaN   probable   arsenic         g/t
35   1.98  contained          NaN   probable   arsenic         NaN
36   30.3    tonnage          NaN  prov_prob   arsenic         NaN
37   2.35        NaN          NaN  prov_prob   arsenic         g/t
38   2.29  contained          NaN  prov_prob   arsenic         NaN
39   13.5    tonnage  underground   probable   arsenic         NaN
40   1.39        NaN  underground   probable   arsenic         g/t
41   0.60  contained  underground   probable   arsenic         NaN
42   14.7    tonnage  underground   probable   arsenic         NaN
43   0.85        NaN  underground   probable   arsenic         g/t
44   0.40  contained  underground   probable   arsenic         NaN
45   28.3    tonnage  underground  prov_prob   arsenic         NaN
46   1.11        NaN  underground  prov_prob   arsenic         g/t
47   1.01  contained  underground  prov_prob   arsenic         NaN
48   13.2    tonnage    stockpile   probable   arsenic         NaN
49   0.30        NaN    stockpile   probable   arsenic         g/t
50   0.13  contained    stockpile   probable   arsenic         NaN
51   13.2    tonnage    stockpile  prov_prob   arsenic         NaN
52   0.30        NaN    stockpile  prov_prob   arsenic         g/t
53   0.13  contained    stockpile  prov_prob   arsenic         NaN
54   26.7    tonnage          NaN   probable   arsenic         NaN
55   0.85        NaN          NaN   probable   arsenic         g/t
56   0.73  contained          NaN   probable   arsenic         NaN
57   14.7    tonnage          NaN   probable   arsenic         NaN
58   0.85        NaN          NaN   probable   arsenic         g/t
59   0.40  contained          NaN   probable   arsenic         NaN
60   41.5    tonnage          NaN  prov_prob   arsenic         NaN
61   0.85        NaN          NaN  prov_prob   arsenic         g/t
62   1.13  contained          NaN  prov_prob   arsenic         NaN
63   0.04    tonnage  underground   probable   arsenic         NaN
64   2.01        NaN  underground   probable   arsenic         g/t
65   0.00  contained  underground   probable   arsenic         NaN
66   2.57    tonnage  underground   probable   arsenic         NaN
67   1.90        NaN  underground   probable   arsenic         g/t
68   0.16  contained  underground   probable   arsenic         NaN
69   2.62    tonnage  underground  prov_prob   arsenic         NaN
70   1.90        NaN  underground  prov_prob   arsenic         g/t
71   0.16  contained  underground  prov_prob   arsenic         NaN
72   11.5    tonnage     open pit   probable   arsenic         NaN
73   0.55        NaN     open pit   probable   arsenic         g/t
74   0.20  contained     open pit   probable   arsenic         NaN
75   19.7    tonnage     open pit   probable   arsenic         NaN
76   0.64        NaN     open pit   probable   arsenic         g/t
77   0.40  contained     open pit   probable   arsenic         NaN
78   31.2    tonnage     open pit  prov_prob   arsenic         NaN
79   0.61        NaN     open pit  prov_prob   arsenic         g/t
80   0.61  contained     open pit  prov_prob   arsenic         NaN
81   11.5    tonnage          NaN   probable   arsenic         NaN
82   0.56        NaN          NaN   probable   arsenic         g/t
83   0.21  contained          NaN   probable   arsenic         NaN
84   22.3    tonnage          NaN   probable   arsenic         NaN
85   0.78        NaN          NaN   probable   arsenic         g/t
86   0.56  contained          NaN   probable   arsenic         NaN
87   33.8    tonnage          NaN  prov_prob   arsenic         NaN
88   0.71        NaN          NaN  prov_prob   arsenic         g/t
89   0.77  contained          NaN  prov_prob   arsenic         NaN
90   3.43    tonnage  underground   probable   arsenic         NaN
91   3.85        NaN  underground   probable   arsenic         g/t
92   0.42  contained  underground   probable   arsenic         NaN
93   3.43    tonnage  underground  prov_prob   arsenic         NaN
94   3.85        NaN  underground  prov_prob   arsenic         g/t
95   0.42  contained  underground  prov_prob   arsenic         NaN
96   4.10    tonnage          NaN   probable   arsenic         NaN
97   9.20        NaN          NaN   probable   arsenic         g/t
98   1.21  contained          NaN   probable   arsenic         NaN
99   4.10    tonnage          NaN  prov_prob   arsenic         NaN
100  9.20        NaN          NaN  prov_prob   arsenic         g/t
101  1.21  contained          NaN  prov_prob   arsenic         NaN
102  7.53    tonnage          NaN   probable   arsenic         NaN
103  6.76        NaN          NaN   probable   arsenic         g/t
104  1.64  contained          NaN   probable   arsenic         NaN
105  7.53    tonnage          NaN  prov_prob   arsenic         NaN
106  6.76        NaN          NaN  prov_prob   arsenic         g/t
107  1.64  contained          NaN  prov_prob   arsenic         NaN
108  42.3    tonnage          NaN   probable      gold         NaN
109  0.92        NaN          NaN   probable      gold         g/t
110  1.25  contained          NaN   probable      gold         NaN
111  70.9    tonnage          NaN   probable      gold         NaN
112  2.01        NaN          NaN   probable      gold         g/t
113  4.58  contained          NaN   probable      gold         NaN
114   113    tonnage          NaN  prov_prob      gold         NaN
115  1.60        NaN          NaN  prov_prob      gold         g/t
116  5.83  contained          NaN  prov_prob      gold         NaN
117  1.52    tonnage  underground   probable   arsenic         NaN
118   1.5        NaN  underground   probable   arsenic         g/t
119   0.1  contained  underground   probable   arsenic         NaN
120  2.63    tonnage  underground   probable   arsenic         NaN
121   1.8        NaN  underground   probable   arsenic         g/t
122   0.2  contained  underground   probable   arsenic         NaN
123  4.14    tonnage  underground  prov_prob   arsenic         NaN
124   1.7        NaN  underground  prov_prob   arsenic         g/t
125   0.2  contained  underground  prov_prob   arsenic         NaN
126  3.62    tonnage  underground   probable   arsenic         NaN
127   2.7        NaN  underground   probable   arsenic         g/t
128   0.3  contained  underground   probable   arsenic         NaN
129  3.62    tonnage  underground  prov_prob   arsenic         NaN
130   2.7        NaN  underground  prov_prob   arsenic         g/t
131   0.3  contained  underground  prov_prob   arsenic         NaN
132  4.00    tonnage  underground   probable   arsenic         NaN
133    11        NaN  underground   probable   arsenic         g/t
134   1.3  contained  underground   probable   arsenic         NaN
135  4.00    tonnage  underground  prov_prob   arsenic         NaN
136    11        NaN  underground  prov_prob   arsenic         g/t
137   1.3  contained  underground  prov_prob   arsenic         NaN
138  2.47    tonnage          NaN   probable   arsenic         NaN
139   2.1        NaN          NaN   probable   arsenic         g/t
140   0.2  contained          NaN   probable   arsenic         NaN
141  16.1    tonnage          NaN   probable   arsenic         NaN
142   2.3        NaN          NaN   probable   arsenic         g/t
143   1.2  contained          NaN   probable   arsenic         NaN
144  18.6    tonnage          NaN  prov_prob   arsenic         NaN
145   2.2        NaN          NaN  prov_prob   arsenic         g/t
146   1.3  contained          NaN  prov_prob   arsenic         NaN
147  3.99    tonnage          NaN   probable   arsenic         NaN
148   1.9        NaN          NaN   probable   arsenic         g/t
149   0.2  contained          NaN   probable   arsenic         NaN
150  26.3    tonnage          NaN   probable   arsenic         NaN
151   3.5        NaN          NaN   probable   arsenic         g/t
152   3.0  contained          NaN   probable   arsenic         NaN
153  30.3    tonnage          NaN  prov_prob   arsenic         NaN
154   3.3        NaN          NaN  prov_prob   arsenic         g/t
155   3.2  contained          NaN  prov_prob   arsenic         NaN
156  13.5    tonnage  underground   probable   arsenic         NaN
157   1.7        NaN  underground   probable   arsenic         g/t
158   0.7  contained  underground   probable   arsenic         NaN
159  14.7    tonnage  underground   probable   arsenic         NaN
160   1.3        NaN  underground   probable   arsenic         g/t
161   0.6  contained  underground   probable   arsenic         NaN
162  28.3    tonnage  underground  prov_prob   arsenic         NaN
163   1.5        NaN  underground  prov_prob   arsenic         g/t
164   1.4  contained  underground  prov_prob   arsenic         NaN
165  13.2    tonnage    stockpile   probable   arsenic         NaN
166   1.9        NaN    stockpile   probable   arsenic         g/t
167   0.8  contained    stockpile   probable   arsenic         NaN
168  13.2    tonnage    stockpile  prov_prob   arsenic         NaN
169   1.9        NaN    stockpile  prov_prob   arsenic         g/t
170   0.8  contained    stockpile  prov_prob   arsenic         NaN
171  26.7    tonnage          NaN   probable   arsenic         NaN
172   1.8        NaN          NaN   probable   arsenic         g/t
173   1.6  contained          NaN   probable   arsenic         NaN
174  14.7    tonnage          NaN   probable   arsenic         NaN
175   1.3        NaN          NaN   probable   arsenic         g/t
176   0.6  contained          NaN   probable   arsenic         NaN
177  41.5    tonnage          NaN  prov_prob   arsenic         NaN
178   1.7        NaN          NaN  prov_prob   arsenic         g/t
179   2.2  contained          NaN  prov_prob   arsenic         NaN
180  3.43    tonnage  underground   probable   arsenic         NaN
181    17        NaN  underground   probable   arsenic         g/t
182   1.9  contained  underground   probable   arsenic         NaN
183  3.43    tonnage  underground  prov_prob   arsenic         NaN
184    17        NaN  underground  prov_prob   arsenic         g/t
185   1.9  contained  underground  prov_prob   arsenic         NaN
186  4.10    tonnage          NaN   probable   arsenic         NaN
187    16        NaN          NaN   probable   arsenic         g/t
188   2.1  contained          NaN   probable   arsenic         NaN
189  4.10    tonnage          NaN  prov_prob   arsenic         NaN
190    16        NaN          NaN  prov_prob   arsenic         g/t
191   2.1  contained          NaN  prov_prob   arsenic         NaN
192  7.53    tonnage          NaN   probable   arsenic         NaN
193    17        NaN          NaN   probable   arsenic         g/t
194   4.0  contained          NaN   probable   arsenic         NaN
195  7.53    tonnage          NaN  prov_prob   arsenic         NaN
196    17        NaN          NaN  prov_prob   arsenic         g/t
197   4.0  contained          NaN  prov_prob   arsenic         NaN
198  30.7    tonnage          NaN   probable    silver         NaN
199   1.8        NaN          NaN   probable    silver         g/t
200   1.8  contained          NaN   probable    silver         NaN
201  48.6    tonnage          NaN   probable    silver         NaN
202   4.9        NaN          NaN   probable    silver         g/t
203   7.6  contained          NaN   probable    silver         NaN
204  79.3    tonnage          NaN  prov_prob    silver         NaN
205   3.7        NaN          NaN  prov_prob    silver         g/t
206   9.5  contained          NaN  prov_prob    silver         NaN
207  13.5    tonnage  underground   probable   arsenic         NaN
208  0.38        NaN  underground   probable   arsenic         g/t
209  0.05  contained  underground   probable   arsenic         NaN
210  14.7    tonnage  underground   probable   arsenic         NaN
211  0.31        NaN  underground   probable   arsenic         g/t
212  0.05  contained  underground   probable   arsenic         NaN
213  28.3    tonnage  underground  prov_prob   arsenic         NaN
214  0.35        NaN  underground  prov_prob   arsenic         g/t
215  0.10  contained  underground  prov_prob   arsenic         NaN
216  13.2    tonnage    stockpile   probable   arsenic         NaN
217  0.28        NaN    stockpile   probable   arsenic         g/t
218  0.04  contained    stockpile   probable   arsenic         NaN
219  13.2    tonnage    stockpile  prov_prob   arsenic         NaN
220  0.28        NaN    stockpile  prov_prob   arsenic         g/t
221  0.04  contained    stockpile  prov_prob   arsenic         NaN
222  26.7    tonnage          NaN   probable   arsenic         NaN
223  0.33        NaN          NaN   probable   arsenic         g/t
224  0.09  contained          NaN   probable   arsenic         NaN
225  14.7    tonnage          NaN   probable   arsenic         NaN
226  0.31        NaN          NaN   probable   arsenic         g/t
227  0.05  contained          NaN   probable   arsenic         NaN
228  41.5    tonnage          NaN  prov_prob   arsenic         NaN
229  0.32        NaN          NaN  prov_prob   arsenic         g/t
230  0.13  contained          NaN  prov_prob   arsenic         NaN
231  26.7    tonnage          NaN   probable    copper         NaN
232  0.33        NaN          NaN   probable    copper         g/t
233  0.09  contained          NaN   probable    copper         NaN
234  14.7    tonnage          NaN   probable    copper         NaN
235  0.31        NaN          NaN   probable    copper         g/t
236  0.05  contained          NaN   probable    copper         NaN
237  41.5    tonnage          NaN  prov_prob    copper         NaN
238  0.32        NaN          NaN  prov_prob    copper         g/t
239  0.13  contained          NaN  prov_prob    copper         NaN

file:///home/ravi/work/mining/project/articles/February202618c1723.html
3

     value     metric     minetype   category commodity measurement
0     1.98    tonnage  underground  indicated   arsenic         NaN
1     5.11        NaN  underground  indicated   arsenic         g/t
2     0.33  contained  underground  indicated   arsenic         NaN
3     2.76    tonnage  underground  indicated   arsenic         NaN
4     5.11        NaN  underground  indicated   arsenic         g/t
5     0.45  contained  underground  indicated   arsenic         NaN
6     4.74    tonnage  underground   meas_ind   arsenic         NaN
7     5.11        NaN  underground   meas_ind   arsenic         g/t
8     0.78  contained  underground   meas_ind   arsenic         NaN
9      0.5    tonnage  underground   meas_ind   arsenic         NaN
10     0.5    tonnage  underground  indicated   arsenic         NaN
11     2.7        NaN  underground  indicated   arsenic         g/t
12     0.0  contained  underground  indicated   arsenic         NaN
13    4.19    tonnage  underground  indicated   arsenic         NaN
14    3.38        NaN  underground  indicated   arsenic         g/t
15    0.45  contained  underground  indicated   arsenic         NaN
16    4.19    tonnage  underground   meas_ind   arsenic         NaN
17    3.38        NaN  underground   meas_ind   arsenic         g/t
18    0.45  contained  underground   meas_ind   arsenic         NaN
19     0.8    tonnage  underground   meas_ind   arsenic         NaN
20     0.8    tonnage  underground  indicated   arsenic         NaN
21     2.5        NaN  underground  indicated   arsenic         g/t
22     0.1  contained  underground  indicated   arsenic         NaN
23    4.07    tonnage  underground  indicated   arsenic         NaN
24    4.12        NaN  underground  indicated   arsenic         g/t
25    0.54  contained  underground  indicated   arsenic         NaN
26    4.07    tonnage  underground   meas_ind   arsenic         NaN
27    4.12        NaN  underground   meas_ind   arsenic         g/t
28    0.54  contained  underground   meas_ind   arsenic         NaN
29     1.2    tonnage  underground   meas_ind   arsenic         NaN
30     1.2    tonnage  underground  indicated   arsenic         NaN
31     2.9        NaN  underground  indicated   arsenic         g/t
32     0.1  contained  underground  indicated   arsenic         NaN
33    2.58    tonnage          NaN  indicated   arsenic         NaN
34    1.21        NaN          NaN  indicated   arsenic         g/t
35    0.10  contained          NaN  indicated   arsenic         NaN
36    16.1    tonnage          NaN  indicated   arsenic         NaN
37    1.64        NaN          NaN  indicated   arsenic         g/t
38    0.85  contained          NaN  indicated   arsenic         NaN
39    18.7    tonnage          NaN   meas_ind   arsenic         NaN
40    1.58        NaN          NaN   meas_ind   arsenic         g/t
41    0.95  contained          NaN   meas_ind   arsenic         NaN
42     0.6    tonnage          NaN   meas_ind   arsenic         NaN
43     0.6    tonnage          NaN  indicated   arsenic         NaN
44     0.9        NaN          NaN  indicated   arsenic         g/t
45     0.0  contained          NaN  indicated   arsenic         NaN
46    4.56    tonnage          NaN  indicated   arsenic         NaN
47    2.91        NaN          NaN  indicated   arsenic         g/t
48    0.43  contained          NaN  indicated   arsenic         NaN
49    27.1    tonnage          NaN  indicated   arsenic         NaN
50    2.63        NaN          NaN  indicated   arsenic         g/t
51    2.30  contained          NaN  indicated   arsenic         NaN
52    31.7    tonnage          NaN   meas_ind   arsenic         NaN
53    2.67        NaN          NaN   meas_ind   arsenic         g/t
54    2.72  contained          NaN   meas_ind   arsenic         NaN
55     3.1    tonnage          NaN   meas_ind   arsenic         NaN
56     3.1    tonnage          NaN  indicated   arsenic         NaN
57     2.4        NaN          NaN  indicated   arsenic         g/t
58     0.2  contained          NaN  indicated   arsenic         NaN
59    14.3    tonnage  underground  indicated   arsenic         NaN
60    1.53        NaN  underground  indicated   arsenic         g/t
61    0.71  contained  underground  indicated   arsenic         NaN
62    17.7    tonnage  underground  indicated   arsenic         NaN
63    0.89        NaN  underground  indicated   arsenic         g/t
64    0.51  contained  underground  indicated   arsenic         NaN
65    32.0    tonnage  underground   meas_ind   arsenic         NaN
66    1.18        NaN  underground   meas_ind   arsenic         g/t
67    1.21  contained  underground   meas_ind   arsenic         NaN
68     9.2    tonnage  underground   meas_ind   arsenic         NaN
69     9.2    tonnage  underground  indicated   arsenic         NaN
70     0.9        NaN  underground  indicated   arsenic         g/t
71     0.3  contained  underground  indicated   arsenic         NaN
72    13.2    tonnage    stockpile  indicated   arsenic         NaN
73    0.29        NaN    stockpile  indicated   arsenic         g/t
74    0.12  contained    stockpile  indicated   arsenic         NaN
75    13.2    tonnage    stockpile   meas_ind   arsenic         NaN
76    0.29        NaN    stockpile   meas_ind   arsenic         g/t
77    0.12  contained    stockpile   meas_ind   arsenic         NaN
78    27.5    tonnage          NaN  indicated   arsenic         NaN
79    0.94        NaN          NaN  indicated   arsenic         g/t
80    0.83  contained          NaN  indicated   arsenic         NaN
81    17.7    tonnage          NaN  indicated   arsenic         NaN
82    0.89        NaN          NaN  indicated   arsenic         g/t
83    0.51  contained          NaN  indicated   arsenic         NaN
84    45.2    tonnage          NaN   meas_ind   arsenic         NaN
85    0.92        NaN          NaN   meas_ind   arsenic         g/t
86    1.34  contained          NaN   meas_ind   arsenic         NaN
87     9.2    tonnage          NaN   meas_ind   arsenic         NaN
88     9.2    tonnage          NaN  indicated   arsenic         NaN
89     0.9        NaN          NaN  indicated   arsenic         g/t
90     0.3  contained          NaN  indicated   arsenic         NaN
91    0.08    tonnage  underground  indicated   arsenic         NaN
92    3.02        NaN  underground  indicated   arsenic         g/t
93    0.01  contained  underground  indicated   arsenic         NaN
94    6.37    tonnage  underground  indicated   arsenic         NaN
95    2.28        NaN  underground  indicated   arsenic         g/t
96    0.47  contained  underground  indicated   arsenic         NaN
97    6.45    tonnage  underground   meas_ind   arsenic         NaN
98    2.29        NaN  underground   meas_ind   arsenic         g/t
99    0.47  contained  underground   meas_ind   arsenic         NaN
100    2.4    tonnage  underground   meas_ind   arsenic         NaN
101    2.4    tonnage  underground  indicated   arsenic         NaN
102    1.8        NaN  underground  indicated   arsenic         g/t
103    0.1  contained  underground  indicated   arsenic         NaN
104   12.6    tonnage          NaN  indicated   arsenic         NaN
105   0.62        NaN          NaN  indicated   arsenic         g/t
106   0.25  contained          NaN  indicated   arsenic         NaN
107   35.7    tonnage          NaN  indicated   arsenic         NaN
108   0.67        NaN          NaN  indicated   arsenic         g/t
109   0.76  contained          NaN  indicated   arsenic         NaN
110   48.3    tonnage          NaN   meas_ind   arsenic         NaN
111   0.65        NaN          NaN   meas_ind   arsenic         g/t
112   1.01  contained          NaN   meas_ind   arsenic         NaN
113     25    tonnage          NaN   meas_ind   arsenic         NaN
114     25    tonnage          NaN  indicated   arsenic         NaN
115    0.7        NaN          NaN  indicated   arsenic         g/t
116    0.5  contained          NaN  indicated   arsenic         NaN
117   12.7    tonnage          NaN  indicated   arsenic         NaN
118   0.63        NaN          NaN  indicated   arsenic         g/t
119   0.26  contained          NaN  indicated   arsenic         NaN
120   42.1    tonnage          NaN  indicated   arsenic         NaN
121   0.91        NaN          NaN  indicated   arsenic         g/t
122   1.23  contained          NaN  indicated   arsenic         NaN
123   54.8    tonnage          NaN   meas_ind   arsenic         NaN
124   0.85        NaN          NaN   meas_ind   arsenic         g/t
125   1.49  contained          NaN   meas_ind   arsenic         NaN
126     27    tonnage          NaN   meas_ind   arsenic         NaN
127     27    tonnage          NaN  indicated   arsenic         NaN
128    0.8        NaN          NaN  indicated   arsenic         g/t
129    0.7  contained          NaN  indicated   arsenic         NaN
130   6.33    tonnage  underground  indicated   arsenic         NaN
131   5.24        NaN  underground  indicated   arsenic         g/t
132   1.07  contained  underground  indicated   arsenic         NaN
133   6.33    tonnage  underground   meas_ind   arsenic         NaN
134   5.24        NaN  underground   meas_ind   arsenic         g/t
135   1.07  contained  underground   meas_ind   arsenic         NaN
136    2.2    tonnage  underground   meas_ind   arsenic         NaN
137    2.2    tonnage  underground  indicated   arsenic         NaN
138    4.6        NaN  underground  indicated   arsenic         g/t
139    0.3  contained  underground  indicated   arsenic         NaN
140   2.63    tonnage          NaN  indicated   arsenic         NaN
141   17.3        NaN          NaN  indicated   arsenic         g/t
142   1.46  contained          NaN  indicated   arsenic         NaN
143   2.63    tonnage          NaN   meas_ind   arsenic         NaN
144   17.3        NaN          NaN   meas_ind   arsenic         g/t
145   1.46  contained          NaN   meas_ind   arsenic         NaN
146    2.9    tonnage          NaN   meas_ind   arsenic         NaN
147    2.9    tonnage          NaN  indicated   arsenic         NaN
148    8.5        NaN          NaN  indicated   arsenic         g/t
149    0.8  contained          NaN  indicated   arsenic         NaN
150   9.72    tonnage          NaN  indicated   arsenic         NaN
151   1.78        NaN          NaN  indicated   arsenic         g/t
152   0.56  contained          NaN  indicated   arsenic         NaN
153   9.72    tonnage          NaN   meas_ind   arsenic         NaN
154   1.78        NaN          NaN   meas_ind   arsenic         g/t
155   0.56  contained          NaN   meas_ind   arsenic         NaN
156    3.2    tonnage          NaN   meas_ind   arsenic         NaN
157    3.2    tonnage          NaN  indicated   arsenic         NaN
158    1.8        NaN          NaN  indicated   arsenic         g/t
159    0.2  contained          NaN  indicated   arsenic         NaN
160   18.7    tonnage          NaN  indicated   arsenic         NaN
161   5.13        NaN          NaN  indicated   arsenic         g/t
162   3.08  contained          NaN  indicated   arsenic         NaN
163   18.7    tonnage          NaN   meas_ind   arsenic         NaN
164   5.13        NaN          NaN   meas_ind   arsenic         g/t
165   3.08  contained          NaN   meas_ind   arsenic         NaN
166    8.3    tonnage          NaN   meas_ind   arsenic         NaN
167    8.3    tonnage          NaN  indicated   arsenic         NaN
168    4.9        NaN          NaN  indicated   arsenic         g/t
169    1.3  contained          NaN  indicated   arsenic         NaN
170   44.8    tonnage          NaN  indicated      gold         NaN
171   1.05        NaN          NaN  indicated      gold         g/t
172   1.51  contained          NaN  indicated      gold         NaN
173    106    tonnage          NaN  indicated      gold         NaN
174   2.10        NaN          NaN  indicated      gold         g/t
175   7.11  contained          NaN  indicated      gold         NaN
176    150    tonnage          NaN   meas_ind      gold         NaN
177   1.78        NaN          NaN   meas_ind      gold         g/t
178   8.63  contained          NaN   meas_ind      gold         NaN
179     48    tonnage          NaN   meas_ind      gold         NaN
180     48    tonnage          NaN  indicated      gold         NaN
181    1.6        NaN          NaN  indicated      gold         g/t
182    2.5  contained          NaN  indicated      gold         NaN
183   1.98    tonnage  underground  indicated   arsenic         NaN
184    1.9        NaN  underground  indicated   arsenic         g/t
185    0.1  contained  underground  indicated   arsenic         NaN
186   2.76    tonnage  underground  indicated   arsenic         NaN
187    2.1        NaN  underground  indicated   arsenic         g/t
188    0.2  contained  underground  indicated   arsenic         NaN
189   4.74    tonnage  underground   meas_ind   arsenic         NaN
190    2.0        NaN  underground   meas_ind   arsenic         g/t
191    0.3  contained  underground   meas_ind   arsenic         NaN
192    0.5    tonnage  underground   meas_ind   arsenic         NaN
193    0.5    tonnage  underground  indicated   arsenic         NaN
194    1.0        NaN  underground  indicated   arsenic         g/t
195    0.0  contained  underground  indicated   arsenic         NaN
196   4.19    tonnage  underground  indicated   arsenic         NaN
197    2.8        NaN  underground  indicated   arsenic         g/t
198    0.4  contained  underground  indicated   arsenic         NaN
199   4.19    tonnage  underground   meas_ind   arsenic         NaN
200    2.8        NaN  underground   meas_ind   arsenic         g/t
201    0.4  contained  underground   meas_ind   arsenic         NaN
202    0.8    tonnage  underground   meas_ind   arsenic         NaN
203    0.8    tonnage  underground  indicated   arsenic         NaN
204    2.1        NaN  underground  indicated   arsenic         g/t
205    0.1  contained  underground  indicated   arsenic         NaN
206   4.07    tonnage  underground  indicated   arsenic         NaN
207     12        NaN  underground  indicated   arsenic         g/t
208    1.6  contained  underground  indicated   arsenic         NaN
209   4.07    tonnage  underground   meas_ind   arsenic         NaN
210     12        NaN  underground   meas_ind   arsenic         g/t
211    1.6  contained  underground   meas_ind   arsenic         NaN
212    1.2    tonnage  underground   meas_ind   arsenic         NaN
213    1.2    tonnage  underground  indicated   arsenic         NaN
214    7.5        NaN  underground  indicated   arsenic         g/t
215    0.3  contained  underground  indicated   arsenic         NaN
216   2.58    tonnage          NaN  indicated   arsenic         NaN
217    2.5        NaN          NaN  indicated   arsenic         g/t
218    0.2  contained          NaN  indicated   arsenic         NaN
219  16 .1    tonnage          NaN  indicated   arsenic         NaN
220    2.5        NaN          NaN  indicated   arsenic         g/t
221    1.3  contained          NaN  indicated   arsenic         NaN
222   18.7    tonnage          NaN   meas_ind   arsenic         NaN
223    2.5        NaN          NaN   meas_ind   arsenic         g/t
224    1.5  contained          NaN   meas_ind   arsenic         NaN
225    0.6    tonnage          NaN   meas_ind   arsenic         NaN
226    0.6    tonnage          NaN  indicated   arsenic         NaN
227    2.4        NaN          NaN  indicated   arsenic         g/t
228    0.0  contained          NaN  indicated   arsenic         NaN
229   4.56    tonnage          NaN  indicated   arsenic         NaN
230    2.2        NaN          NaN  indicated   arsenic         g/t
231    0.3  contained          NaN  indicated   arsenic         NaN
232   27.1    tonnage          NaN  indicated   arsenic         NaN
233    4.0        NaN          NaN  indicated   arsenic         g/t
234    3.5  contained          NaN  indicated   arsenic         NaN
235   31.7    tonnage          NaN   meas_ind   arsenic         NaN
236    3.7        NaN          NaN   meas_ind   arsenic         g/t
237    3.8  contained          NaN   meas_ind   arsenic         NaN
238    3.1    tonnage          NaN   meas_ind   arsenic         NaN
239    3.1    tonnage          NaN  indicated   arsenic         NaN
240    4.0        NaN          NaN  indicated   arsenic         g/t
241    0.4  contained          NaN  indicated   arsenic         NaN
242  14 .3    tonnage  underground  indicated   arsenic         NaN
243    1.8        NaN  underground  indicated   arsenic         g/t
244    0.8  contained  underground  indicated   arsenic         NaN
245   17.7    tonnage  underground  indicated   arsenic         NaN
246    1.4        NaN  underground  indicated   arsenic         g/t
247    0.8  contained  underground  indicated   arsenic         NaN
248   32.0    tonnage  underground   meas_ind   arsenic         NaN
249    1.6        NaN  underground   meas_ind   arsenic         g/t
250    1.6  contained  underground   meas_ind   arsenic         NaN
251    9.2    tonnage  underground   meas_ind   arsenic         NaN
252    9.2    tonnage  underground  indicated   arsenic         NaN
253    1.2        NaN  underground  indicated   arsenic         g/t
254    0.4  contained  underground  indicated   arsenic         NaN
255  13 .2    tonnage    stockpile  indicated   arsenic         NaN
256    1.9        NaN    stockpile  indicated   arsenic         g/t
257    0.8  contained    stockpile  indicated   arsenic         NaN
258   13.2    tonnage    stockpile   meas_ind   arsenic         NaN
259    1.9        NaN    stockpile   meas_ind   arsenic         g/t
260    0.8  contained    stockpile   meas_ind   arsenic         NaN
261   27.5    tonnage          NaN  indicated   arsenic         NaN
262    1.8        NaN          NaN  indicated   arsenic         g/t
263    1.6  contained          NaN  indicated   arsenic         NaN
264   17.7    tonnage          NaN  indicated   arsenic         NaN
265    1.4        NaN          NaN  indicated   arsenic         g/t
266    0.8  contained          NaN  indicated   arsenic         NaN
267   45.2    tonnage          NaN   meas_ind   arsenic         NaN
268    1.7        NaN          NaN   meas_ind   arsenic         g/t
269    2.4  contained          NaN   meas_ind   arsenic         NaN
270    9.2    tonnage          NaN   meas_ind   arsenic         NaN
271    9.2    tonnage          NaN  indicated   arsenic         NaN
272    1.2        NaN          NaN  indicated   arsenic         g/t
273    0.4  contained          NaN  indicated   arsenic         NaN
274   6.33    tonnage  underground  indicated   arsenic         NaN
275     20        NaN  underground  indicated   arsenic         g/t
276    4.1  contained  underground  indicated   arsenic         NaN
277   6.33    tonnage  underground   meas_ind   arsenic         NaN
278     20        NaN  underground   meas_ind   arsenic         g/t
279    4.1  contained  underground   meas_ind   arsenic         NaN
280    2.2    tonnage  underground   meas_ind   arsenic         NaN
281    2.2    tonnage  underground  indicated   arsenic         NaN
282     24        NaN  underground  indicated   arsenic         g/t
283    1.7  contained  underground  indicated   arsenic         NaN
284   2.63    tonnage          NaN  indicated   arsenic         NaN
285     27        NaN          NaN  indicated   arsenic         g/t
286    2.3  contained          NaN  indicated   arsenic         NaN
287   2.63    tonnage          NaN   meas_ind   arsenic         NaN
288     27        NaN          NaN   meas_ind   arsenic         g/t
289    2.3  contained          NaN   meas_ind   arsenic         NaN
290    2.9    tonnage          NaN   meas_ind   arsenic         NaN
291    2.9    tonnage          NaN  indicated   arsenic         NaN
292     13        NaN          NaN  indicated   arsenic         g/t

file:///home/ravi/work/mining/project/articles/February202617c0698.html
1

    value   category     metric measurement  commodity
0    7854     proven        NaN         NaN        NaN
1    9.92     proven      grade         g/t       gold
2   11.76     proven      grade         g/t     silver
3    2506     proven  contained          oz       gold
4    2970     proven  contained          oz     silver
5    2970     proven  contained          oz     silver
6   15300   probable        NaN         NaN        NaN
7    5.70   probable      grade         g/t       gold
8   10.89   probable      grade         g/t     silver
9    2803   probable  contained          oz       gold
10   5358   probable  contained          oz     silver
11   5358   probable  contained          oz     silver
12  23154  prov_prob        NaN         NaN  phosphate
13   7.14  prov_prob      grade         g/t       gold
14  11.20  prov_prob      grade         g/t     silver
15   5309  prov_prob  contained          oz       gold
16   8328  prov_prob  contained          oz     silver
17   8328  prov_prob  contained          oz     silver
18   2505   probable        NaN         NaN        NaN
19   6.66   probable      grade         g/t       gold
20   6.94   probable      grade         g/t     silver
21    536   probable  contained          oz       gold
22    559   probable  contained          oz     silver
23    559   probable  contained          oz     silver
24   2505  prov_prob        NaN         NaN  phosphate
25   6.66  prov_prob      grade         g/t       gold
26   6.94  prov_prob      grade         g/t     silver
27    536  prov_prob  contained          oz       gold
28    559  prov_prob  contained          oz     silver
29    559  prov_prob  contained          oz     silver
30   7854     proven        NaN         NaN        NaN
31   9.92     proven      grade         g/t       gold
32  11.76     proven      grade         g/t     silver
33   2506     proven  contained          oz       gold
34   2970     proven  contained          oz     silver
35   2970     proven  contained          oz     silver
36  17805   probable        NaN         NaN        NaN
37   5.83   probable      grade         g/t       gold
38  10.34   probable      grade         g/t     silver
39   3339   probable  contained          oz       gold
40   5917   probable  contained          oz     silver
41   5917   probable  contained          oz     silver
42  25659  prov_prob        NaN         NaN  phosphate
43   7.09  prov_prob      grade         g/t       gold
44  10.77  prov_prob      grade         g/t     silver
45   5845  prov_prob  contained          oz       gold
46   8887  prov_prob  contained          oz     silver
47   8887  prov_prob  contained          oz     silver

file:///home/ravi/work/mining/project/articles/February202617c0698.html
6

    value   category     metric measurement commodity
0   10404   measured        NaN         NaN       NaN
1    9.48   measured      grade         g/t      gold
2   12.27   measured      grade         g/t    silver
3    3171   measured  contained          oz      gold
4    4105   measured  contained          oz    silver
5   19063  indicated        NaN         NaN       NaN
6    5.78  indicated      grade         g/t      gold
7   11.00  indicated      grade         g/t    silver
8    3542  indicated  contained          oz      gold
9    6740  indicated  contained          oz    silver
10  29467   meas_ind        NaN         NaN       NaN
11   7.09   meas_ind      grade         g/t      gold
12  11.45   meas_ind      grade         g/t    silver
13   6713   meas_ind  contained          oz      gold
14  10845   meas_ind  contained          oz    silver
15    831   inferred        NaN         NaN       NaN
16   4.83   inferred      grade         g/t      gold
17   8.48   inferred      grade         g/t    silver
18    129   inferred  contained          oz      gold
19    227   inferred  contained          oz    silver
20   3144  indicated        NaN         NaN       NaN
21   7.58  indicated      grade         g/t      gold
22   8.66  indicated      grade         g/t    silver
23    766  indicated  contained          oz      gold
24    875  indicated  contained          oz    silver
25   3144   meas_ind        NaN         NaN       NaN
26   7.58   meas_ind      grade         g/t      gold
27   8.66   meas_ind      grade         g/t    silver
28    766   meas_ind  contained          oz      gold
29    875   meas_ind  contained          oz    silver
30   7247   inferred        NaN         NaN       NaN
31   6.37   inferred      grade         g/t      gold
32  18.52   inferred      grade         g/t    silver
33   1484   inferred  contained          oz      gold
34   4314   inferred  contained          oz    silver
35   2166   inferred        NaN         NaN       NaN
36   6.01   inferred      grade         g/t      gold
37   7.61   inferred      grade         g/t    silver
38    418   inferred  contained          oz      gold
39    530   inferred  contained          oz    silver
40  10404   measured        NaN         NaN       NaN
41   9.48   measured      grade         g/t      gold
42  12.27   measured      grade         g/t    silver
43   3171   measured  contained          oz      gold
44   4105   measured  contained          oz    silver
45  22207  indicated        NaN         NaN       NaN
46   6.03  indicated      grade         g/t      gold
47  10.67  indicated      grade         g/t    silver
48   4309  indicated  contained          oz      gold
49   7615  indicated  contained          oz    silver
50  32611   meas_ind        NaN         NaN       NaN
51   7.13   meas_ind      grade         g/t      gold
52  11.18   meas_ind      grade         g/t    silver
53   7480   meas_ind  contained          oz      gold
54  11720   meas_ind  contained          oz    silver
55  10245   inferred        NaN         NaN       NaN
56   6.17   inferred      grade         g/t      gold
57  15.40   inferred      grade         g/t    silver
58   2031   inferred  contained          oz      gold
59   5071   inferred  contained          oz    silver

file:///home/ravi/work/mining/project/articles/February202617c8682.html
1

       value     metric   category measurement commodity
0   42707000    tonnage  indicated           t       NaN
1       1.26      grade  indicated         g/t      gold
2       0.95      grade  indicated         g/t      gold
3       0.12      grade  indicated         NaN  antimony
4    1736000  contained  indicated          oz       NaN
5    1308000  contained  indicated          oz      gold
6      51000  contained  indicated           t  antimony
7   34882000    tonnage   inferred           t       NaN
8       0.93      grade   inferred         g/t      gold
9       0.65      grade   inferred         g/t      gold
10      0.11      grade   inferred         NaN  antimony
11   1038000  contained   inferred          oz       NaN
12    732000  contained   inferred          oz      gold
13     37000  contained   inferred           t  antimony

file:///home/ravi/work/mining/project/articles/February202616c8642.html
1

    value     metric   category commodity measurement
0    71.6    tonnage     proven    copper         NaN
1     7.9      grade     proven    copper         g/t
2    18.2  contained     proven    copper         NaN
3    59.1    tonnage   probable    copper         NaN
4     9.6      grade   probable    copper         g/t
5    18.2  contained   probable    copper         NaN
6   130.6    tonnage        NaN    copper         NaN
7     8.7      grade        NaN    copper         g/t
8    36.4  contained        NaN    copper         NaN
9    16.2    tonnage     proven    copper         NaN
10   18.7      grade     proven    copper         g/t
11    9.7  contained     proven    copper         NaN
12   31.4    tonnage   probable    copper         NaN
13   19.4      grade   probable    copper         g/t
14   19.6  contained   probable    copper         NaN
15   47.6    tonnage        NaN    copper         NaN
16   19.2      grade        NaN    copper         g/t
17   29.3  contained        NaN    copper         NaN
18   87.8    tonnage     proven    copper         NaN
19    9.9      grade     proven    copper         g/t
20   27.9  contained     proven    copper         NaN
21   90.5    tonnage   probable    copper         NaN
22   13.0      grade   probable    copper         g/t
23   37.8  contained   probable    copper         NaN
24  178.2    tonnage        NaN    copper         NaN
25   11.5      grade        NaN    copper         g/t
26   65.7  contained        NaN    copper         NaN
27   28.7    tonnage   measured    copper         NaN
28    6.6      grade   measured    copper         g/t
29    6.1  contained   measured    copper         NaN
30   59.1    tonnage  indicated    copper         NaN
31    8.2      grade  indicated    copper         g/t
32   15.5  contained  indicated    copper         NaN
33   87.8    tonnage   measured    copper         NaN
34    7.7      grade   measured    copper         g/t
35   21.6  contained   measured    copper         NaN
36  256.8    tonnage   inferred    copper         NaN
37    8.9      grade   inferred    copper         g/t
38   73.7  contained   inferred    copper         NaN
39    4.7    tonnage   measured    copper         NaN
40   25.5      grade   measured    copper         g/t
41    3.9  contained   measured    copper         NaN
42   21.9    tonnage  indicated    copper         NaN
43   18.4      grade  indicated    copper         g/t
44   12.9  contained  indicated    copper         NaN
45   26.7    tonnage   measured    copper         NaN
46   19.6      grade   measured    copper         g/t
47   16.8  contained   measured    copper         NaN
48   69.3    tonnage   inferred    copper         NaN
49   16.2      grade   inferred    copper         g/t
50   36.2  contained   inferred    copper         NaN
51   33.4    tonnage   measured    copper         NaN
52    9.3      grade   measured    copper         g/t
53   10.0  contained   measured    copper         NaN
54   81.0    tonnage  indicated    copper         NaN
55   10.9      grade  indicated    copper         g/t
56   28.4  contained  indicated    copper         NaN
57  114.4    tonnage   measured    copper         NaN
58   10.4      grade   measured    copper         g/t
59   38.4  contained   measured    copper         NaN
60  326.2    tonnage   inferred    copper         NaN
61   10.5      grade   inferred    copper         g/t
62  109.9  contained   inferred    copper         NaN

file:///home/ravi/work/mining/project/articles/February202616c2981.html
7

     value   metric   category   oretype commodity measurement
0     1733  tonnage  indicated  sulphide       NaN         NaN
1     1733  tonnage  indicated  sulphide       NaN         NaN
2     1733  tonnage  indicated  sulphide       NaN         NaN
3     0.46      NaN  indicated  sulphide    copper         NaN
4     0.46      NaN  indicated  sulphide    copper         NaN
5     0.34      NaN  indicated  sulphide      gold         g/t
6     0.34      NaN  indicated  sulphide      gold         g/t
7      6.0      NaN  indicated  sulphide    silver         g/t
8     8031      NaN  indicated  sulphide    copper          kt
9     19.2      NaN  indicated  sulphide      gold         NaN
10     336      NaN  indicated  sulphide    silver         NaN
11    1733  tonnage   meas_ind       NaN       NaN         NaN
12    1733  tonnage   meas_ind       NaN       NaN         NaN
13    1733  tonnage   meas_ind       NaN       NaN         NaN
14    0.46      NaN   meas_ind       NaN    copper         NaN
15    0.46      NaN   meas_ind       NaN    copper         NaN
16    0.34      NaN   meas_ind       NaN      gold         g/t
17    0.34      NaN   meas_ind       NaN      gold         g/t
18     6.0      NaN   meas_ind       NaN    silver         g/t
19    8031      NaN   meas_ind       NaN    copper          kt
20    19.2      NaN   meas_ind       NaN      gold         NaN
21     336      NaN   meas_ind       NaN    silver         NaN
22    8721  tonnage   inferred       NaN       NaN         NaN
23    8721  tonnage   inferred       NaN       NaN         NaN
24    8721  tonnage   inferred       NaN       NaN         NaN
25    0.34      NaN   inferred       NaN    copper         NaN
26    0.34      NaN   inferred       NaN    copper         NaN
27    0.18      NaN   inferred       NaN      gold         g/t
28    0.18      NaN   inferred       NaN      gold         g/t
29     2.9      NaN   inferred       NaN    silver         g/t
30   29683      NaN   inferred       NaN    copper          kt
31    51.5      NaN   inferred       NaN      gold         NaN
32     823      NaN   inferred       NaN    silver         NaN
33     467  tonnage  indicated     oxide    copper         NaN
34     467  tonnage  indicated     oxide    copper         NaN
35     467  tonnage  indicated     oxide    copper         NaN
36    0.32      NaN  indicated     oxide    copper         NaN
37    0.32      NaN  indicated     oxide    copper         NaN
38    0.27      NaN  indicated     oxide    copper         g/t
39    0.27      NaN  indicated     oxide    copper         g/t
40     2.5      NaN  indicated     oxide    copper         g/t
41    1474      NaN  indicated     oxide    copper          kt
42     4.1      NaN  indicated     oxide    copper         NaN
43      38      NaN  indicated     oxide    copper         NaN
44     467  tonnage   meas_ind       NaN       NaN         NaN
45     467  tonnage   meas_ind       NaN       NaN         NaN
46     467  tonnage   meas_ind       NaN       NaN         NaN
47    0.32      NaN   meas_ind       NaN    copper         NaN
48    0.32      NaN   meas_ind       NaN    copper         NaN
49    0.27      NaN   meas_ind       NaN      gold         g/t
50    0.27      NaN   meas_ind       NaN      gold         g/t
51     2.5      NaN   meas_ind       NaN    silver         g/t
52    1474      NaN   meas_ind       NaN    copper          kt
53     4.1      NaN   meas_ind       NaN      gold         NaN
54      38      NaN   meas_ind       NaN    silver         NaN
55     431  tonnage   inferred       NaN       NaN         NaN
56     431  tonnage   inferred       NaN       NaN         NaN
57     431  tonnage   inferred       NaN       NaN         NaN
58    0.23      NaN   inferred       NaN    copper         NaN
59    0.23      NaN   inferred       NaN    copper         NaN
60    0.20      NaN   inferred       NaN      gold         g/t
61    0.20      NaN   inferred       NaN      gold         g/t
62     2.2      NaN   inferred       NaN    silver         g/t
63     982      NaN   inferred       NaN    copper          kt
64     2.7      NaN   inferred       NaN      gold         NaN
65      30      NaN   inferred       NaN    silver         NaN
66     301  tonnage  indicated     oxide      gold         NaN
67     301  tonnage  indicated     oxide      gold         NaN
68     301  tonnage  indicated     oxide      gold         NaN
69    0.25      NaN  indicated     oxide      gold         g/t
70    0.25      NaN  indicated     oxide      gold         g/t
71     2.7      NaN  indicated     oxide      gold         g/t
72     2.4      NaN  indicated     oxide      gold         NaN
73      26      NaN  indicated     oxide      gold         NaN
74     301  tonnage   meas_ind       NaN       NaN         NaN
75     301  tonnage   meas_ind       NaN       NaN         NaN
76     301  tonnage   meas_ind       NaN       NaN         NaN
77    0.25      NaN   meas_ind       NaN      gold         g/t
78    0.25      NaN   meas_ind       NaN      gold         g/t
79     2.7      NaN   meas_ind       NaN    silver         g/t
80     2.4      NaN   meas_ind       NaN      gold         NaN
81      26      NaN   meas_ind       NaN    silver         NaN
82     711  tonnage   inferred       NaN       NaN         NaN
83     711  tonnage   inferred       NaN       NaN         NaN
84     711  tonnage   inferred       NaN       NaN         NaN
85    0.18      NaN   inferred       NaN      gold         g/t
86    0.18      NaN   inferred       NaN      gold         g/t
87     3.0      NaN   inferred       NaN    silver         g/t
88     4.1      NaN   inferred       NaN      gold         NaN
89      69      NaN   inferred       NaN    silver         NaN
90      71  tonnage  indicated     oxide    silver         NaN
91      71  tonnage  indicated     oxide    silver         NaN
92      71  tonnage  indicated     oxide    silver         NaN
93    0.36      NaN  indicated     oxide    silver         NaN
94    0.36      NaN  indicated     oxide    silver         NaN
95    0.36      NaN  indicated     oxide    silver         g/t
96    0.36      NaN  indicated     oxide    silver         g/t
97   119.7      NaN  indicated     oxide    silver         g/t
98     254      NaN  indicated     oxide    silver          kt
99     0.8      NaN  indicated     oxide    silver         NaN
100    272      NaN  indicated     oxide    silver         NaN
101     71  tonnage   meas_ind       NaN       NaN         NaN
102     71  tonnage   meas_ind       NaN       NaN         NaN
103     71  tonnage   meas_ind       NaN       NaN         NaN
104   0.36      NaN   meas_ind       NaN    copper         NaN
105   0.36      NaN   meas_ind       NaN    copper         NaN
106   0.36      NaN   meas_ind       NaN      gold         g/t
107   0.36      NaN   meas_ind       NaN      gold         g/t
108  119.7      NaN   meas_ind       NaN    silver         g/t
109    254      NaN   meas_ind       NaN    copper          kt
110    0.8      NaN   meas_ind       NaN      gold         NaN
111    272      NaN   meas_ind       NaN    silver         NaN
112     95  tonnage   inferred       NaN       NaN         NaN
113     95  tonnage   inferred       NaN       NaN         NaN
114     95  tonnage   inferred       NaN       NaN         NaN
115   0.08      NaN   inferred       NaN    copper         NaN
116   0.08      NaN   inferred       NaN    copper         NaN
117   0.14      NaN   inferred       NaN      gold         g/t
118   0.14      NaN   inferred       NaN      gold         g/t
119   35.1      NaN   inferred       NaN    silver         g/t
120     75      NaN   inferred       NaN    copper          kt
121    0.4      NaN   inferred       NaN      gold         NaN
122    108      NaN   inferred       NaN    silver         NaN
123    648  tonnage   measured       NaN       NaN         NaN
124    648  tonnage   measured       NaN       NaN         NaN
125    648  tonnage   measured       NaN       NaN         NaN
126   0.33      NaN   measured       NaN    copper         NaN
127   0.33      NaN   measured       NaN    copper         NaN
128   0.25      NaN   measured       NaN      gold         g/t
129   0.25      NaN   measured       NaN      gold         g/t
130    1.2      NaN   measured       NaN    silver         g/t
131   2143      NaN   measured       NaN    copper          kt
132    5.2      NaN   measured       NaN      gold         NaN
133     25      NaN   measured       NaN    silver         NaN
134    961  tonnage  indicated       NaN       NaN         NaN
135    961  tonnage  indicated       NaN       NaN         NaN
136    961  tonnage  indicated       NaN       NaN         NaN
137   0.25      NaN  indicated       NaN    copper         NaN
138   0.25      NaN  indicated       NaN    copper         NaN
139   0.15      NaN  indicated       NaN      gold         g/t
140   0.15      NaN  indicated       NaN      gold         g/t
141    1.1      NaN  indicated       NaN    silver         g/t
142   2436      NaN  indicated       NaN    copper          kt
143    4.5      NaN  indicated       NaN      gold         NaN
144     33      NaN  indicated       NaN    silver         NaN
145   1609  tonnage   meas_ind       NaN       NaN         NaN
146   1609  tonnage   meas_ind       NaN       NaN         NaN
147   1609  tonnage   meas_ind       NaN       NaN         NaN
148   0.28      NaN   meas_ind       NaN    copper         NaN
149   0.28      NaN   meas_ind       NaN    copper         NaN
150   0.19      NaN   meas_ind       NaN      gold         g/t
151   0.19      NaN   meas_ind       NaN      gold         g/t
152    1.1      NaN   meas_ind       NaN    silver         g/t
153   4579      NaN   meas_ind       NaN    copper          kt
154    9.7      NaN   meas_ind       NaN      gold         NaN
155     58      NaN   meas_ind       NaN    silver         NaN
156    683  tonnage   inferred       NaN       NaN         NaN
157    683  tonnage   inferred       NaN       NaN         NaN
158    683  tonnage   inferred       NaN       NaN         NaN
159   0.22      NaN   inferred       NaN    copper         NaN
160   0.22      NaN   inferred       NaN    copper         NaN
161   0.11      NaN   inferred       NaN      gold         g/t
162   0.11      NaN   inferred       NaN      gold         g/t
163    1.0      NaN   inferred       NaN    silver         g/t
164   1515      NaN   inferred       NaN    copper          kt
165    2.5      NaN   inferred       NaN      gold         NaN
166     22      NaN   inferred       NaN    silver         NaN
167    648  tonnage   measured       NaN       NaN         NaN
168    648  tonnage   measured       NaN       NaN         NaN
169    648  tonnage   measured       NaN       NaN         NaN
170   0.33      NaN   measured       NaN    copper         NaN
171   0.33      NaN   measured       NaN    copper         NaN
172   0.25      NaN   measured       NaN      gold         g/t
173   0.25      NaN   measured       NaN      gold         g/t
174    1.2      NaN   measured       NaN    silver         g/t
175   2143      NaN   measured       NaN    copper          kt
176    5.2      NaN   measured       NaN      gold         NaN
177     25      NaN   measured       NaN    silver         NaN
178   3533  tonnage  indicated       NaN       NaN         NaN
179   3533  tonnage  indicated       NaN       NaN         NaN
180   3533  tonnage  indicated       NaN       NaN         NaN
181   0.34      NaN  indicated       NaN    copper         NaN
182   0.34      NaN  indicated       NaN    copper         NaN
183   0.27      NaN  indicated       NaN      gold         g/t
184   0.27      NaN  indicated       NaN      gold         g/t
185    6.2      NaN  indicated       NaN    silver         g/t
186  12195      NaN  indicated       NaN    copper          kt
187   30.9      NaN  indicated       NaN      gold         NaN
188    704      NaN  indicated       NaN    silver         NaN
189   4181  tonnage   meas_ind       NaN       NaN         NaN
190   4181  tonnage   meas_ind       NaN       NaN         NaN
191   4181  tonnage   meas_ind       NaN       NaN         NaN
192   0.34      NaN   meas_ind       NaN    copper         NaN
193   0.34      NaN   meas_ind       NaN    copper         NaN
194   0.27      NaN   meas_ind       NaN      gold         g/t
195   0.27      NaN   meas_ind       NaN      gold         g/t
196    5.4      NaN   meas_ind       NaN    silver         g/t
197  14338      NaN   meas_ind       NaN    copper          kt
198   36.1      NaN   meas_ind       NaN      gold         NaN
199    729      NaN   meas_ind       NaN    silver         NaN
200  10641  tonnage   inferred       NaN       NaN         NaN
201  10641  tonnage   inferred       NaN       NaN         NaN
202  10641  tonnage   inferred       NaN       NaN         NaN
203   0.30      NaN   inferred       NaN    copper         NaN
204   0.30      NaN   inferred       NaN    copper         NaN
205   0.18      NaN   inferred       NaN      gold         g/t
206   0.18      NaN   inferred       NaN      gold         g/t
207    3.1      NaN   inferred       NaN    silver         g/t
208  32255      NaN   inferred       NaN    copper          kt
209   61.3      NaN   inferred       NaN      gold         NaN
210   1051      NaN   inferred       NaN    silver         NaN

file:///home/ravi/work/mining/project/articles/February202612c9957.html
3

     value     metric  category measurement commodity         minetype
0      746  contained  meas_ind          oz      gold              NaN
1     3.59      grade  meas_ind         g/t      gold              NaN
2      265  contained  inferred          oz      gold              NaN
3     6.03      grade  inferred         g/t      gold              NaN
4     1506  contained  meas_ind          oz      gold              NaN
5     1.93      grade  meas_ind         g/t      gold              NaN
6     1127  contained  inferred          oz      gold              NaN
7     3.00      grade  inferred         g/t      gold              NaN
8     2251  contained  meas_ind          oz      gold              NaN
9     2.28      grade  meas_ind         g/t      gold              NaN
10    1392  contained  inferred          oz      gold              NaN
11    3.32      grade  inferred         g/t      gold              NaN
12     118  contained  inferred          oz      gold              NaN
13    0.73      grade  inferred         g/t      gold              NaN
14      63  contained  meas_ind          oz      gold              NaN
15    0.51      grade  meas_ind         g/t      gold              NaN
16     376  contained  inferred          oz      gold              NaN
17    1.56      grade  inferred         g/t      gold              NaN
18     614  contained  meas_ind          oz      gold              NaN
19    1.27      grade  meas_ind         g/t      gold              NaN
20     410  contained  inferred          oz      gold              NaN
21    1.11      grade  inferred         g/t      gold              NaN
22     236  contained  meas_ind          oz      gold              NaN
23    1.63      grade  meas_ind         g/t      gold              NaN
24    1445  contained  inferred          oz      gold              NaN
25    2.23      grade  inferred         g/t      gold              NaN
26    2976  contained  meas_ind          oz      gold              NaN
27    1.92      grade  meas_ind         g/t      gold              NaN
28    3835  contained  inferred          oz      gold              NaN
29    1.89      grade  inferred         g/t      gold              NaN
30     230  contained  meas_ind          oz      gold              NaN
31    1.42      grade  meas_ind         g/t      gold              NaN
32    7372  contained  inferred          oz      gold              NaN
33    2.43      grade  inferred         g/t      gold              NaN
34    4120  contained  meas_ind          oz      gold              NaN
35    1.67      grade  meas_ind         g/t      gold              NaN
36   13556  contained  inferred          oz      gold              NaN
37    2.09      grade  inferred         g/t      gold              NaN
38    1727  contained  meas_ind          oz      gold              NaN
39    1.60      grade  meas_ind         g/t      gold              NaN
40     842  contained  inferred          oz      gold              NaN
41    1.46      grade  inferred         g/t      gold              NaN
42       2  contained  meas_ind          oz      gold              NaN
43    0.38      grade  meas_ind         g/t      gold              NaN
44      50  contained  inferred          oz      gold              NaN
45    1.60      grade  inferred         g/t      gold              NaN
46     318  contained  inferred          oz      gold              NaN
47    3.24      grade  inferred         g/t      gold              NaN
48     667  contained  meas_ind          oz      gold              NaN
49    2.19      grade  meas_ind         g/t      gold              NaN
50     312  contained  inferred          oz      gold              NaN
51    2.48      grade  inferred         g/t      gold              NaN
52   17157  contained  meas_ind          oz      gold              NaN
53    0.79      grade  meas_ind         g/t      gold              NaN
54    6168  contained  inferred          oz      gold              NaN
55    1.73      grade  inferred         g/t      gold              NaN
56     534  contained  meas_ind          oz      gold              NaN
57    5.80      grade  meas_ind         g/t      gold              NaN
58     136  contained  inferred          oz      gold              NaN
59    4.35      grade  inferred         g/t      gold              NaN
60   17691  contained  meas_ind          oz      gold              NaN
61    0.81      grade  meas_ind         g/t      gold              NaN
62    6304  contained  inferred          oz      gold              NaN
63    1.75      grade  inferred         g/t      gold              NaN
64     656  contained  meas_ind          oz      gold              NaN
65    6.38      grade  meas_ind         g/t      gold              NaN
66    1226  contained  inferred          oz      gold              NaN
67    7.00      grade  inferred         g/t      gold              NaN
68       8  contained  meas_ind          oz      gold  surface (other)
69    4.02      grade  meas_ind         g/t      gold  surface (other)
70      40  contained  inferred          oz      gold  surface (other)
71    3.99      grade  inferred         g/t      gold  surface (other)
72      17  contained  meas_ind          oz      gold              NaN
73    2.53      grade  meas_ind         g/t      gold              NaN
74      34  contained  inferred          oz      gold              NaN
75    3.40      grade  inferred         g/t      gold              NaN
76     681  contained  meas_ind          oz      gold              NaN
77    6.10      grade  meas_ind         g/t      gold              NaN
78    1299  contained  inferred          oz      gold              NaN
79    6.66      grade  inferred         g/t      gold              NaN
80     349  contained  meas_ind          oz      gold              NaN
81    2.77      grade  meas_ind         g/t      gold              NaN
82     107  contained  inferred          oz      gold              NaN
83    3.84      grade  inferred         g/t      gold              NaN
84     495  contained  meas_ind          oz      gold              NaN
85    2.03      grade  meas_ind         g/t      gold              NaN
86     391  contained  inferred          oz      gold              NaN
87    4.12      grade  inferred         g/t      gold              NaN
88     817  contained  meas_ind          oz      gold              NaN
89    2.30      grade  meas_ind         g/t      gold              NaN
90    2211  contained  inferred          oz      gold              NaN
91    2.85      grade  inferred         g/t      gold              NaN
92    2298  contained  meas_ind          oz      gold              NaN
93    0.54      grade  meas_ind         g/t      gold              NaN
94     856  contained  meas_ind          oz      gold              NaN
95    2.15      grade  meas_ind         g/t      gold              NaN
96      14  contained  inferred          oz      gold              NaN
97    3.59      grade  inferred         g/t      gold              NaN
98    1699  contained  meas_ind          oz      gold              NaN
99    4.52      grade  meas_ind         g/t      gold              NaN
100   1310  contained  inferred          oz      gold              NaN
101   4.48      grade  inferred         g/t      gold              NaN
102   1336  contained  meas_ind          oz      gold              NaN
103   3.65      grade  meas_ind         g/t      gold              NaN
104    783  contained  inferred          oz      gold              NaN
105   4.10      grade  inferred         g/t      gold              NaN
106   2244  contained  meas_ind          oz      gold              NaN
107   3.39      grade  meas_ind         g/t      gold              NaN
108   2478  contained  inferred          oz      gold              NaN
109   5.23      grade  inferred         g/t      gold              NaN
110   2217  contained  meas_ind          oz      gold              NaN
111   4.61      grade  meas_ind         g/t      gold              NaN
112   3246  contained  inferred          oz      gold              NaN
113   5.98      grade  inferred         g/t      gold              NaN
114   1377  contained  meas_ind          oz      gold              NaN
115   3.77      grade  meas_ind         g/t      gold              NaN
116   1795  contained  inferred          oz      gold              NaN
117   4.19      grade  inferred         g/t      gold              NaN
118   1455  contained  meas_ind          oz      gold              NaN
119   2.15      grade  meas_ind         g/t      gold              NaN
120   1512  contained  inferred          oz      gold              NaN
121   2.47      grade  inferred         g/t      gold              NaN
122   2048  contained  meas_ind          oz      gold              NaN
123   2.83      grade  meas_ind         g/t      gold              NaN
124    977  contained  inferred          oz      gold              NaN
125   4.62      grade  inferred         g/t      gold              NaN
126    176  contained  meas_ind          oz      gold              NaN
127   1.27      grade  meas_ind         g/t      gold              NaN
128   1005  contained  inferred          oz      gold              NaN
129   1.98      grade  inferred         g/t      gold              NaN
130    916  contained  meas_ind          oz      gold              NaN
131   2.01      grade  meas_ind         g/t      gold              NaN
132     93  contained  inferred          oz      gold              NaN
133   1.87      grade  inferred         g/t      gold              NaN
134     89  contained  meas_ind          oz      gold              NaN
135   0.52      grade  meas_ind         g/t      gold              NaN
136    361  contained  meas_ind          oz      gold              NaN
137   0.58      grade  meas_ind         g/t      gold              NaN
138      4  contained  inferred          oz      gold              NaN
139   0.52      grade  inferred         g/t      gold              NaN
140    287  contained  meas_ind          oz      gold              NaN
141   0.77      grade  meas_ind         g/t      gold              NaN
142     26  contained  inferred          oz      gold              NaN
143   0.63      grade  inferred         g/t      gold              NaN
144    335  contained  meas_ind          oz      gold              NaN
145   1.24      grade  meas_ind         g/t      gold              NaN
146    349  contained  inferred          oz      gold              NaN
147   1.12      grade  inferred         g/t      gold              NaN
148     20  contained  meas_ind          oz      gold              NaN
149   0.19      grade  meas_ind         g/t      gold              NaN
150     10  contained  inferred          oz      gold              NaN
151   0.13      grade  inferred         g/t      gold              NaN
152    563  contained  meas_ind          oz      gold              NaN
153   0.91      grade  meas_ind         g/t      gold              NaN
154   1433  contained  inferred          oz      gold              NaN
155   2.36      grade  inferred         g/t      gold              NaN
156  47076  contained  meas_ind          oz      gold              NaN
157   1.22      grade  meas_ind         g/t      gold              NaN
158  41815  contained  inferred          oz      gold              NaN
159   2.49      grade  inferred         g/t      gold              NaN

file:///home/ravi/work/mining/project/articles/February202612c9957.html
13

       value   category commodity measurement   metric
0       2469     proven   arsenic         NaN      NaN
1       4.65     proven   arsenic         g/t      NaN
2        369     proven   arsenic          oz  tonnage
3       8158   probable   arsenic         NaN  tonnage
4       6.06   probable   arsenic         g/t      NaN
5       1590   probable   arsenic          oz  tonnage
6      10627  prov_prob   arsenic         NaN  tonnage
7       5.73  prov_prob   arsenic         g/t      NaN
8       1959  prov_prob   arsenic          oz  tonnage
9       94.4  prov_prob   arsenic         NaN      NaN
10      6405     proven   arsenic         NaN      NaN
11      2.02     proven   arsenic         g/t      NaN
12       415     proven   arsenic          oz  tonnage
13      6800   probable   arsenic         NaN  tonnage
14      2.17   probable   arsenic         g/t      NaN
15       474   probable   arsenic          oz  tonnage
16     13205  prov_prob   arsenic         NaN  tonnage
17      2.09  prov_prob   arsenic         g/t      NaN
18       889  prov_prob   arsenic          oz  tonnage
19      94.5  prov_prob   arsenic         NaN      NaN
20      8874     proven   arsenic         NaN      NaN
21      2.75     proven   arsenic         g/t      NaN
22       784     proven   arsenic          oz  tonnage
23     14959   probable   arsenic         NaN  tonnage
24      4.29   probable   arsenic         g/t      NaN
25      2064   probable   arsenic          oz  tonnage
26     23832  prov_prob   arsenic         NaN  tonnage
27      3.72  prov_prob   arsenic         g/t      NaN
28      2848  prov_prob   arsenic          oz  tonnage
29     36896     proven   arsenic         NaN      NaN
30      0.50     proven   arsenic         g/t      NaN
31       597     proven   arsenic          oz  tonnage
32     21697   probable   arsenic         NaN  tonnage
33      1.22   probable   arsenic         g/t      NaN
34       852   probable   arsenic          oz  tonnage
35     58594  prov_prob   arsenic         NaN  tonnage
36      0.77  prov_prob   arsenic         g/t      NaN
37      1449  prov_prob   arsenic          oz  tonnage
38      88.8  prov_prob   arsenic         NaN      NaN
39     51618   probable   arsenic         NaN  tonnage
40      0.95   probable   arsenic         g/t      NaN
41      1577   probable   arsenic          oz  tonnage
42     51618  prov_prob   arsenic         NaN  tonnage
43      0.95  prov_prob   arsenic         g/t      NaN
44      1577  prov_prob   arsenic          oz  tonnage
45      90.0  prov_prob   arsenic         NaN      NaN
46        29     proven   arsenic         NaN      NaN
47      2.37     proven   arsenic         g/t      NaN
48         2     proven   arsenic          oz  tonnage
49      4758   probable   arsenic         NaN  tonnage
50      2.12   probable   arsenic         g/t      NaN
51       325   probable   arsenic          oz  tonnage
52      4787  prov_prob   arsenic         NaN  tonnage
53      2.12  prov_prob   arsenic         g/t      NaN
54       327  prov_prob   arsenic          oz  tonnage
55      95.0  prov_prob   arsenic         NaN      NaN
56     54943   probable   arsenic         NaN  tonnage
57      3.23   probable   arsenic         g/t      NaN
58      5699   probable   arsenic          oz  tonnage
59     54943  prov_prob   arsenic         NaN  tonnage
60      3.23  prov_prob   arsenic         g/t      NaN
61      5699  prov_prob   arsenic          oz  tonnage
62      94.4  prov_prob   arsenic         NaN      NaN
63        29     proven   arsenic         NaN      NaN
64      2.37     proven   arsenic         g/t      NaN
65         2     proven   arsenic          oz  tonnage
66     59701   probable   arsenic         NaN  tonnage
67      3.14   probable   arsenic         g/t      NaN
68      6024   probable   arsenic          oz  tonnage
69     59730  prov_prob   arsenic         NaN  tonnage
70      3.14  prov_prob   arsenic         g/t      NaN
71      6026  prov_prob   arsenic          oz  tonnage
72     36925     proven   arsenic         NaN      NaN
73      0.50     proven   arsenic         g/t      NaN
74       599     proven   arsenic          oz  tonnage
75    133016   probable   arsenic         NaN  tonnage
76      1.98   probable   arsenic         g/t      NaN
77      8453   probable   arsenic          oz  tonnage
78    169941  prov_prob   arsenic         NaN  tonnage
79      1.66  prov_prob   arsenic         g/t      NaN
80      9052  prov_prob   arsenic          oz  tonnage
81      6255     proven   arsenic         NaN      NaN
82      1.48     proven   arsenic         g/t      NaN
83       298     proven   arsenic          oz  tonnage
84      9065   probable   arsenic         NaN  tonnage
85      1.68   probable   arsenic         g/t      NaN
86       488   probable   arsenic          oz  tonnage
87     15320  prov_prob   arsenic         NaN  tonnage
88      1.60  prov_prob   arsenic         g/t      NaN
89       786  prov_prob   arsenic          oz  tonnage
90      85.9  prov_prob   arsenic         NaN      NaN
91       969     proven   arsenic         NaN      NaN
92      0.82     proven   arsenic         g/t      NaN
93        26     proven   arsenic          oz  tonnage
94      2807   probable   arsenic         NaN  tonnage
95      0.96   probable   arsenic         g/t      NaN
96        86   probable   arsenic          oz  tonnage
97      3777  prov_prob   arsenic         NaN  tonnage
98      0.92  prov_prob   arsenic         g/t      NaN
99       112  prov_prob   arsenic          oz  tonnage
100     77.6  prov_prob   arsenic         NaN      NaN
101     7225     proven   arsenic         NaN      NaN
102     1.39     proven   arsenic         g/t      NaN
103      324     proven   arsenic          oz  tonnage
104    11872   probable   arsenic         NaN  tonnage
105     1.51   probable   arsenic         g/t      NaN
106      575   probable   arsenic          oz  tonnage
107    19097  prov_prob   arsenic         NaN  tonnage
108     1.46  prov_prob   arsenic         g/t      NaN
109      898  prov_prob   arsenic          oz  tonnage
110    14757   probable   arsenic         NaN  tonnage
111     2.90   probable   arsenic         g/t      NaN
112     1377   probable   arsenic          oz  tonnage
113    14757  prov_prob   arsenic         NaN  tonnage
114     2.90  prov_prob   arsenic         g/t      NaN
115     1377  prov_prob   arsenic          oz  tonnage
116     89.7  prov_prob   arsenic         NaN      NaN
117    53023     proven   arsenic         NaN      NaN
118     1.00     proven   arsenic         g/t      NaN
119     1707     proven   arsenic          oz  tonnage
120   174603   probable   arsenic         NaN  tonnage
121     2.22   probable   arsenic         g/t      NaN
122    12468   probable   arsenic          oz  tonnage
123   227626  prov_prob   arsenic         NaN  tonnage
124     1.94  prov_prob   arsenic         g/t      NaN
125    14175  prov_prob   arsenic          oz  tonnage
126    66690     proven   arsenic         g/t      NaN
127     1.08     proven   arsenic         g/t      NaN
128     2313     proven   arsenic         g/t  tonnage
129   434448   probable   arsenic         g/t  tonnage
130     0.90   probable   arsenic         g/t      NaN
131    12641   probable   arsenic         g/t  tonnage
132   501138  prov_prob   arsenic         g/t  tonnage
133     0.93  prov_prob   arsenic         g/t      NaN
134    14954  prov_prob   arsenic         g/t  tonnage
135     88.4  prov_prob   arsenic         g/t      NaN
136    53681     proven   arsenic         g/t      NaN
137     0.42     proven   arsenic         g/t      NaN
138      722     proven   arsenic         g/t  tonnage
139   243242   probable   arsenic         g/t  tonnage
140     0.37   probable   arsenic         g/t      NaN
141     2899   probable   arsenic         g/t  tonnage
142   296923  prov_prob   arsenic         g/t  tonnage
143     0.38  prov_prob   arsenic         g/t      NaN
144     3621  prov_prob   arsenic         g/t  tonnage
145     88.4  prov_prob   arsenic         g/t      NaN
146   120371     proven   arsenic         NaN      NaN
147     0.78     proven   arsenic         g/t      NaN
148     3035     proven   arsenic          oz  tonnage
149   677690   probable   arsenic         NaN  tonnage
150     0.71   probable   arsenic         g/t      NaN
151    15540   probable   arsenic          oz  tonnage
152   798061  prov_prob   arsenic         NaN  tonnage
153     0.72  prov_prob   arsenic         g/t      NaN
154    18575  prov_prob   arsenic          oz  tonnage
155      612     proven   arsenic         NaN      NaN
156    10.43     proven   arsenic         g/t      NaN
157      205     proven   arsenic          oz  tonnage
158     6013   probable   arsenic         NaN  tonnage
159     8.68   probable   arsenic         g/t      NaN
160     1678   probable   arsenic          oz  tonnage
161     6625  prov_prob   arsenic         NaN  tonnage
162     8.84  prov_prob   arsenic         g/t      NaN
163     1883  prov_prob   arsenic          oz  tonnage
164     95.9  prov_prob   arsenic         NaN      NaN
165        3     proven   arsenic         NaN      NaN
166     2.11     proven   arsenic         g/t      NaN
167        0     proven   arsenic          oz  tonnage
168       80   probable   arsenic         NaN  tonnage
169     3.91   probable   arsenic         g/t      NaN
170       10   probable   arsenic          oz  tonnage
171       84  prov_prob   arsenic         NaN  tonnage
172     3.84  prov_prob   arsenic         g/t      NaN
173       10  prov_prob   arsenic          oz  tonnage
174     93.5  prov_prob   arsenic         NaN      NaN
175      126     proven   arsenic         NaN      NaN
176     4.35     proven   arsenic         g/t      NaN
177       18     proven   arsenic          oz  tonnage
178     1975   probable   arsenic         NaN  tonnage
179     4.54   probable   arsenic         g/t      NaN
180      288   probable   arsenic          oz  tonnage
181     2101  prov_prob   arsenic         NaN  tonnage
182     4.53  prov_prob   arsenic         g/t      NaN
183      306  prov_prob   arsenic          oz  tonnage
184     93.5  prov_prob   arsenic         NaN      NaN
185      742     proven   arsenic         NaN      NaN
186     9.36     proven   arsenic         g/t      NaN
187      223     proven   arsenic          oz  tonnage
188     8068   probable   arsenic         NaN  tonnage
189     7.62   probable   arsenic         g/t      NaN
190     1976   probable   arsenic          oz  tonnage
191     8810  prov_prob   arsenic         NaN  tonnage
192     7.77  prov_prob   arsenic         g/t      NaN
193     2200  prov_prob   arsenic          oz  tonnage
194     3235   probable   arsenic         NaN  tonnage
195     1.82   probable   arsenic         g/t      NaN
196      189   probable   arsenic          oz  tonnage
197     3235  prov_prob   arsenic         NaN  tonnage
198     1.82  prov_prob   arsenic         g/t      NaN
199      189  prov_prob   arsenic          oz  tonnage
200     95.5  prov_prob   arsenic         NaN      NaN
201    19946   probable   arsenic         NaN  tonnage
202     4.02   probable   arsenic         g/t      NaN
203     2579   probable   arsenic          oz  tonnage
204    19946  prov_prob   arsenic         NaN  tonnage
205     4.02  prov_prob   arsenic         g/t      NaN
206     2579  prov_prob   arsenic          oz  tonnage
207     95.5  prov_prob   arsenic         NaN      NaN
208    23181   probable   arsenic         NaN  tonnage
209     3.71   probable   arsenic         g/t      NaN
210     2768   probable   arsenic          oz  tonnage
211    23181  prov_prob   arsenic         NaN  tonnage
212     3.71  prov_prob   arsenic         g/t      NaN
213     2768  prov_prob   arsenic          oz  tonnage
214   123473   probable   arsenic         NaN  tonnage
215     0.84   probable   arsenic         g/t      NaN
216     3323   probable   arsenic          oz  tonnage
217   123473  prov_prob   arsenic         NaN  tonnage
218     0.84  prov_prob   arsenic         g/t      NaN
219     3323  prov_prob   arsenic          oz  tonnage
220     89.8  prov_prob   arsenic         NaN      NaN
221   121113     proven   arsenic         NaN      NaN
222     0.84     proven   arsenic         g/t      NaN
223     3258     proven   arsenic          oz  tonnage
224   832412   probable   arsenic         NaN  tonnage
225     0.88   probable   arsenic         g/t      NaN
226    23607   probable   arsenic          oz  tonnage
227   953524  prov_prob   arsenic         NaN  tonnage
228     0.88  prov_prob   arsenic         g/t      NaN
229    26865  prov_prob   arsenic          oz  tonnage
230     8048     proven   arsenic         NaN      NaN
231     1.26     proven   arsenic         g/t      NaN
232      327     proven   arsenic          oz  tonnage
233     7364   probable   arsenic         NaN  tonnage
234     3.17   probable   arsenic         g/t      NaN
235      750   probable   arsenic          oz  tonnage
236    15412  prov_prob   arsenic         NaN  tonnage
237     2.17  prov_prob   arsenic         g/t      NaN
238     1077  prov_prob   arsenic          oz  tonnage
239     90.5  prov_prob   arsenic         NaN      NaN
240       81     proven   arsenic         NaN      NaN
241     4.22     proven   arsenic         g/t      NaN
242       11     proven   arsenic          oz  tonnage
243     2221   probable   arsenic         NaN  tonnage
244     5.12   probable   arsenic         g/t      NaN
245      366   probable   arsenic          oz  tonnage
246     2302  prov_prob   arsenic         NaN  tonnage
247     5.09  prov_prob   arsenic         g/t      NaN
248      377  prov_prob   arsenic          oz  tonnage
249     90.5  prov_prob   arsenic         NaN      NaN
250     8129     proven   arsenic         NaN      NaN
251     1.29     proven   arsenic         g/t      NaN
252      338     proven   arsenic          oz  tonnage
253     9585   probable   arsenic         NaN  tonnage
254     3.62   probable   arsenic         g/t      NaN
255     1116   probable   arsenic          oz  tonnage
256    17714  prov_prob   arsenic         NaN  tonnage
257     2.55  prov_prob   arsenic         g/t      NaN
258     1454  prov_prob   arsenic          oz  tonnage
259     1142     proven   arsenic         NaN      NaN
260     4.24     proven   arsenic         g/t      NaN
261      156     proven   arsenic          oz  tonnage
262     4291   probable   arsenic         NaN  tonnage
263     3.64   probable   arsenic         g/t      NaN
264      503   probable   arsenic          oz  tonnage
265     5433  prov_prob   arsenic         NaN  tonnage
266     3.77  prov_prob   arsenic         g/t      NaN
267      658  prov_prob   arsenic          oz  tonnage
268     96.0  prov_prob   arsenic         NaN      NaN
269     2962     proven   arsenic         NaN      NaN
270     6.32     proven   arsenic         g/t      NaN
271      602     proven   arsenic          oz  tonnage
272    13680   probable   arsenic         NaN  tonnage
273     5.37   probable   arsenic         g/t      NaN
274     2362   probable   arsenic          oz  tonnage
275    16642  prov_prob   arsenic         NaN  tonnage
276     5.54  prov_prob   arsenic         g/t      NaN
277     2964  prov_prob   arsenic          oz  tonnage
278     96.0  prov_prob   arsenic         NaN      NaN
279     4104     proven   arsenic         NaN      NaN
280     5.74     proven   arsenic         g/t      NaN
281      757     proven   arsenic          oz  tonnage
282    17971   probable   arsenic         NaN  tonnage
283     4.96   probable   arsenic         g/t      NaN
284     2864   probable   arsenic          oz  tonnage
285    22075  prov_prob   arsenic         NaN  tonnage
286     5.10  prov_prob   arsenic         g/t      NaN
287     3622  prov_prob   arsenic          oz  tonnage
288       93     proven   arsenic         NaN      NaN
289     6.77     proven   arsenic         g/t      NaN
290       20     proven   arsenic          oz  tonnage
291    16086   probable   arsenic         NaN  tonnage
292     6.53   probable   arsenic         g/t      NaN
293     3376   probable   arsenic          oz  tonnage
294    16178  prov_prob   arsenic         NaN  tonnage
295     6.53  prov_prob   arsenic         g/t      NaN
296     3396  prov_prob   arsenic          oz  tonnage
297     87.5  prov_prob   arsenic         NaN      NaN
298    12325     proven   arsenic         NaN      NaN
299     2.82     proven   arsenic         g/t      NaN
300     1116     proven   arsenic          oz  tonnage
301    43642   probable   arsenic         NaN  tonnage
302     5.24   probable   arsenic         g/t      NaN
303     7356   probable   arsenic          oz  tonnage
304    55967  prov_prob   arsenic         NaN  tonnage
305     4.71  prov_prob   arsenic         g/t      NaN
306     8472  prov_prob   arsenic          oz  tonnage
307      887     proven   arsenic         NaN      NaN
308     5.41     proven   arsenic         g/t      NaN
309      154     proven   arsenic          oz  tonnage
310     9516   probable   arsenic         NaN  tonnage
311     4.95   probable   arsenic         g/t      NaN
312     1516   probable   arsenic          oz  tonnage
313    10403  prov_prob   arsenic         NaN  tonnage
314     4.99  prov_prob   arsenic         g/t      NaN
315     1670  prov_prob   arsenic          oz  tonnage
316     92.0  prov_prob   arsenic         NaN      NaN
317      887     proven   arsenic         NaN      NaN
318     5.41     proven   arsenic         g/t      NaN
319      154     proven   arsenic          oz  tonnage
320     9516   probable   arsenic         NaN  tonnage
321     4.95   probable   arsenic         g/t      NaN
322     1516   probable   arsenic          oz  tonnage
323    10403  prov_prob   arsenic         NaN  tonnage
324     4.99  prov_prob   arsenic         g/t      NaN
325     1670  prov_prob   arsenic          oz  tonnage
326      931     proven   arsenic         NaN      NaN
327     4.66     proven   arsenic         g/t      NaN
328      140     proven   arsenic          oz  tonnage
329    23818   probable   arsenic         NaN  tonnage
330     4.15   probable   arsenic         g/t      NaN
331     3179   probable   arsenic          oz  tonnage
332    24749  prov_prob   arsenic         NaN  tonnage
333     4.17  prov_prob   arsenic         g/t      NaN
334     3319  prov_prob   arsenic          oz  tonnage
335     86.0  prov_prob   arsenic         NaN      NaN
336      931     proven   arsenic         NaN      NaN
337     4.66     proven   arsenic         g/t      NaN
338      140     proven   arsenic          oz  tonnage
339    23818   probable   arsenic         NaN  tonnage
340     4.15   probable   arsenic         g/t      NaN
341     3179   probable   arsenic          oz  tonnage
342    24749  prov_prob   arsenic         NaN  tonnage
343     4.17  prov_prob   arsenic         g/t      NaN
344     3319  prov_prob   arsenic          oz  tonnage
345       26     proven   arsenic         NaN      NaN
346     0.60     proven   arsenic         g/t      NaN
347        1     proven   arsenic          oz  tonnage
348     1629   probable   arsenic         NaN  tonnage
349     1.00   probable   arsenic         g/t      NaN
350       53   probable   arsenic          oz  tonnage
351     1656  prov_prob   arsenic         NaN  tonnage
352     1.00  prov_prob   arsenic         g/t      NaN
353       53  prov_prob   arsenic          oz  tonnage
354     93.6  prov_prob   arsenic         NaN      NaN
355      633     proven   arsenic         NaN      NaN
356     2.06     proven   arsenic         g/t      NaN
357       42     proven   arsenic          oz  tonnage
358     2374   probable   arsenic         NaN  tonnage
359     2.29   probable   arsenic         g/t      NaN
360      175   probable   arsenic          oz  tonnage
361     3007  prov_prob   arsenic         NaN  tonnage

file:///home/ravi/work/mining/project/articles/February202612c9957.html
15

       value   metric   category commodity measurement         minetype
0       6457  tonnage  indicated   arsenic         NaN              NaN
1       3.59      NaN  indicated   arsenic         g/t              NaN
2        746  tonnage  indicated   arsenic          oz              NaN
3       6457  tonnage   meas_ind   arsenic         NaN              NaN
4       3.59      NaN   meas_ind   arsenic         g/t              NaN
5        746  tonnage   meas_ind   arsenic          oz              NaN
6       1366  tonnage   inferred   arsenic         NaN              NaN
7       6.03      NaN   inferred   arsenic         g/t              NaN
8        265  tonnage   inferred   arsenic          oz              NaN
9      24207  tonnage  indicated   arsenic         NaN              NaN
10      1.93      NaN  indicated   arsenic         g/t              NaN
11      1506  tonnage  indicated   arsenic          oz              NaN
12     24207  tonnage   meas_ind   arsenic         NaN              NaN
13      1.93      NaN   meas_ind   arsenic         g/t              NaN
14      1506  tonnage   meas_ind   arsenic          oz              NaN
15     11677  tonnage   inferred   arsenic         NaN              NaN
16      3.00      NaN   inferred   arsenic         g/t              NaN
17      1127  tonnage   inferred   arsenic          oz              NaN
18     30664  tonnage  indicated   arsenic         NaN              NaN
19      2.28      NaN  indicated   arsenic         g/t              NaN
20      2251  tonnage  indicated   arsenic          oz              NaN
21     30664  tonnage   meas_ind   arsenic         NaN              NaN
22      2.28      NaN   meas_ind   arsenic         g/t              NaN
23      2251  tonnage   meas_ind   arsenic          oz              NaN
24     13043  tonnage   inferred   arsenic         NaN              NaN
25      3.32      NaN   inferred   arsenic         g/t              NaN
26      1392  tonnage   inferred   arsenic          oz              NaN
27      5011  tonnage   inferred   arsenic         NaN              NaN
28      0.73      NaN   inferred   arsenic         g/t              NaN
29       118  tonnage   inferred   arsenic          oz              NaN
30      3875  tonnage  indicated   arsenic         NaN              NaN
31      0.51      NaN  indicated   arsenic         g/t              NaN
32        63  tonnage  indicated   arsenic          oz              NaN
33      3875  tonnage   meas_ind   arsenic         NaN              NaN
34      0.51      NaN   meas_ind   arsenic         g/t              NaN
35        63  tonnage   meas_ind   arsenic          oz              NaN
36      2956  tonnage   inferred   arsenic         NaN              NaN
37      0.66      NaN   inferred   arsenic         g/t              NaN
38        63  tonnage   inferred   arsenic          oz              NaN
39      4544  tonnage   inferred   arsenic         NaN              NaN
40      2.14      NaN   inferred   arsenic         g/t              NaN
41       313  tonnage   inferred   arsenic          oz              NaN
42     14794  tonnage  indicated   arsenic         NaN              NaN
43      1.22      NaN  indicated   arsenic         g/t              NaN
44       582  tonnage  indicated   arsenic          oz              NaN
45     14794  tonnage   meas_ind   arsenic         NaN              NaN
46      1.22      NaN   meas_ind   arsenic         g/t              NaN
47       582  tonnage   meas_ind   arsenic          oz              NaN
48     11272  tonnage   inferred   arsenic         NaN              NaN
49      1.08      NaN   inferred   arsenic         g/t              NaN
50       390  tonnage   inferred   arsenic          oz              NaN
51       296  tonnage  indicated   arsenic         NaN              NaN
52      3.36      NaN  indicated   arsenic         g/t              NaN
53        32  tonnage  indicated   arsenic          oz              NaN
54       296  tonnage   meas_ind   arsenic         NaN              NaN
55      3.36      NaN   meas_ind   arsenic         g/t              NaN
56        32  tonnage   meas_ind   arsenic          oz              NaN
57       183  tonnage   inferred   arsenic         NaN              NaN
58      3.37      NaN   inferred   arsenic         g/t              NaN
59        20  tonnage   inferred   arsenic          oz              NaN
60      4493  tonnage  indicated   arsenic         NaN              NaN
61      1.63      NaN  indicated   arsenic         g/t              NaN
62       236  tonnage  indicated   arsenic          oz              NaN
63      4493  tonnage   meas_ind   arsenic         NaN              NaN
64      1.63      NaN   meas_ind   arsenic         g/t              NaN
65       236  tonnage   meas_ind   arsenic          oz              NaN
66     20176  tonnage   inferred   arsenic         NaN              NaN
67      2.23      NaN   inferred   arsenic         g/t              NaN
68      1445  tonnage   inferred   arsenic          oz              NaN
69     48216  tonnage  indicated   arsenic         NaN              NaN
70      1.92      NaN  indicated   arsenic         g/t              NaN
71      2976  tonnage  indicated   arsenic          oz              NaN
72     48216  tonnage   meas_ind   arsenic         NaN              NaN
73      1.92      NaN   meas_ind   arsenic         g/t              NaN
74      2976  tonnage   meas_ind   arsenic          oz              NaN
75     63275  tonnage   inferred   arsenic         NaN              NaN
76      1.89      NaN   inferred   arsenic         g/t              NaN
77      3835  tonnage   inferred   arsenic          oz              NaN
78      5048  tonnage  indicated   arsenic         NaN              NaN
79      1.42      NaN  indicated   arsenic         g/t              NaN
80       230  tonnage  indicated   arsenic          oz              NaN
81      5048  tonnage   meas_ind   arsenic         NaN              NaN
82      1.42      NaN   meas_ind   arsenic         g/t              NaN
83       230  tonnage   meas_ind   arsenic          oz              NaN
84     94278  tonnage   inferred   arsenic         NaN              NaN
85      2.43      NaN   inferred   arsenic         g/t              NaN
86      7372  tonnage   inferred   arsenic          oz              NaN
87     57757  tonnage  indicated   arsenic         NaN              NaN
88      1.85      NaN  indicated   arsenic         g/t              NaN
89      3442  tonnage  indicated   arsenic          oz              NaN
90     57757  tonnage   meas_ind   arsenic         NaN              NaN
91      1.85      NaN   meas_ind   arsenic         g/t              NaN
92      3442  tonnage   meas_ind   arsenic          oz              NaN
93    177729  tonnage   inferred   arsenic         NaN              NaN
94      2.21      NaN   inferred   arsenic         g/t              NaN
95     12652  tonnage   inferred   arsenic          oz              NaN
96     76723  tonnage  indicated   arsenic         NaN              NaN
97      1.67      NaN  indicated   arsenic         g/t              NaN
98      4120  tonnage  indicated   arsenic          oz              NaN
99     76723  tonnage   meas_ind   arsenic         NaN              NaN
100     1.67      NaN   meas_ind   arsenic         g/t              NaN
101     4120  tonnage   meas_ind   arsenic          oz              NaN
102   201694  tonnage   inferred   arsenic         NaN              NaN
103     2.09      NaN   inferred   arsenic         g/t              NaN
104    13556  tonnage   inferred   arsenic          oz              NaN
105    12360  tonnage   measured   arsenic         NaN              NaN
106     1.86      NaN   measured   arsenic         g/t              NaN
107      739  tonnage   measured   arsenic          oz              NaN
108    21245  tonnage  indicated   arsenic         NaN              NaN
109     1.45      NaN  indicated   arsenic         g/t              NaN
110      988  tonnage  indicated   arsenic          oz              NaN
111    33604  tonnage   meas_ind   arsenic         NaN              NaN
112     1.60      NaN   meas_ind   arsenic         g/t              NaN
113     1727  tonnage   meas_ind   arsenic          oz              NaN
114    17951  tonnage   inferred   arsenic         NaN              NaN
115     1.46      NaN   inferred   arsenic         g/t              NaN
116      842  tonnage   inferred   arsenic          oz              NaN
117      130  tonnage  indicated   arsenic         NaN              NaN
118     0.38      NaN  indicated   arsenic         g/t              NaN
119        2  tonnage  indicated   arsenic          oz              NaN
120      130  tonnage   meas_ind   arsenic         NaN              NaN
121     0.38      NaN   meas_ind   arsenic         g/t              NaN
122        2  tonnage   meas_ind   arsenic          oz              NaN
123      966  tonnage   inferred   arsenic         NaN              NaN
124     1.60      NaN   inferred   arsenic         g/t              NaN
125       50  tonnage   inferred   arsenic          oz              NaN
126    12360  tonnage   measured   arsenic         NaN              NaN
127     1.86      NaN   measured   arsenic         g/t              NaN
128      739  tonnage   measured   arsenic          oz              NaN
129    21374  tonnage  indicated   arsenic         NaN              NaN
130     1.44      NaN  indicated   arsenic         g/t              NaN
131      989  tonnage  indicated   arsenic          oz              NaN
132    33734  tonnage   meas_ind   arsenic         NaN              NaN
133     1.59      NaN   meas_ind   arsenic         g/t              NaN
134     1728  tonnage   meas_ind   arsenic          oz              NaN
135    18917  tonnage   inferred   arsenic         NaN              NaN
136     1.47      NaN   inferred   arsenic         g/t              NaN
137      892  tonnage   inferred   arsenic          oz              NaN
138     3052  tonnage   inferred   arsenic         NaN              NaN
139     3.24      NaN   inferred   arsenic         g/t              NaN
140      318  tonnage   inferred   arsenic          oz              NaN
141     9479  tonnage  indicated   arsenic         NaN              NaN
142     2.19      NaN  indicated   arsenic         g/t              NaN
143      667  tonnage  indicated   arsenic          oz              NaN
144     9479  tonnage   meas_ind   arsenic         NaN              NaN
145     2.19      NaN   meas_ind   arsenic         g/t              NaN
146      667  tonnage   meas_ind   arsenic          oz              NaN
147     3911  tonnage   inferred   arsenic         NaN              NaN
148     2.48      NaN   inferred   arsenic         g/t              NaN
149      312  tonnage   inferred   arsenic          oz              NaN
150    12360  tonnage   measured   arsenic         NaN              NaN
151     1.86      NaN   measured   arsenic         g/t              NaN
152      739  tonnage   measured   arsenic          oz              NaN
153   138241  tonnage  indicated   arsenic         NaN              NaN
154     1.81      NaN  indicated   arsenic         g/t              NaN
155     8027  tonnage  indicated   arsenic          oz              NaN
156   150601  tonnage   meas_ind   arsenic         NaN              NaN
157     1.81      NaN   meas_ind   arsenic         g/t              NaN
158     8766  tonnage   meas_ind   arsenic          oz              NaN
159   240618  tonnage   inferred   arsenic         NaN              NaN
160     2.13      NaN   inferred   arsenic         g/t              NaN
161    16469  tonnage   inferred   arsenic          oz              NaN
162    35300  tonnage   measured   arsenic         NaN              NaN
163     1.16      NaN   measured   arsenic         g/t              NaN
164     1312  tonnage   measured   arsenic          oz              NaN
165   587007  tonnage  indicated   arsenic         NaN              NaN
166     0.66      NaN  indicated   arsenic         g/t              NaN
167    12373  tonnage  indicated   arsenic          oz              NaN
168   622307  tonnage   meas_ind   arsenic         NaN              NaN
169     0.68      NaN   meas_ind   arsenic         g/t              NaN
170    13685  tonnage   meas_ind   arsenic          oz              NaN
171    51442  tonnage   inferred   arsenic         NaN              NaN
172     1.38      NaN   inferred   arsenic         g/t              NaN
173     2290  tonnage   inferred   arsenic          oz              NaN
174    52924  tonnage  indicated   arsenic         NaN              NaN
175     2.04      NaN  indicated   arsenic         g/t              NaN
176     3472  tonnage  indicated   arsenic          oz              NaN
177    52924  tonnage   meas_ind   arsenic         NaN              NaN
178     2.04      NaN   meas_ind   arsenic         g/t              NaN
179     3472  tonnage   meas_ind   arsenic          oz              NaN
180    59549  tonnage   inferred   arsenic         NaN              NaN
181     2.03      NaN   inferred   arsenic         g/t              NaN
182     3878  tonnage   inferred   arsenic          oz              NaN
183     2868  tonnage  indicated   arsenic         NaN              NaN
184     5.80      NaN  indicated   arsenic         g/t              NaN
185      534  tonnage  indicated   arsenic          oz              NaN
186     2868  tonnage   meas_ind   arsenic         NaN              NaN
187     5.80      NaN   meas_ind   arsenic         g/t              NaN
188      534  tonnage   meas_ind   arsenic          oz              NaN
189      973  tonnage   inferred   arsenic         NaN              NaN
190     4.35      NaN   inferred   arsenic         g/t              NaN
191      136  tonnage   inferred   arsenic          oz              NaN
192    35300  tonnage   measured   arsenic         NaN              NaN
193     1.16      NaN   measured   arsenic         g/t              NaN
194     1312  tonnage   measured   arsenic          oz              NaN
195   642798  tonnage  indicated   arsenic         NaN              NaN
196     0.79      NaN  indicated   arsenic         g/t              NaN
197    16379  tonnage  indicated   arsenic          oz              NaN
198   678098  tonnage   meas_ind   arsenic         NaN              NaN
199     0.81      NaN   meas_ind   arsenic         g/t              NaN
200    17691  tonnage   meas_ind   arsenic          oz              NaN
201   111964  tonnage   inferred   arsenic         NaN              NaN
202     1.75      NaN   inferred   arsenic         g/t              NaN
203     6304  tonnage   inferred   arsenic          oz              NaN
204      379  tonnage   measured   arsenic         NaN              NaN
205    10.30      NaN   measured   arsenic         g/t              NaN
206      125  tonnage   measured   arsenic          oz              NaN
207     2818  tonnage  indicated   arsenic         NaN              NaN
208     5.85      NaN  indicated   arsenic         g/t              NaN
209      530  tonnage  indicated   arsenic          oz              NaN
210     3197  tonnage   meas_ind   arsenic         NaN              NaN
211     6.38      NaN   meas_ind   arsenic         g/t              NaN
212      656  tonnage   meas_ind   arsenic          oz              NaN
213     5448  tonnage   inferred   arsenic         NaN              NaN
214     7.00      NaN   inferred   arsenic         g/t              NaN
215     1226  tonnage   inferred   arsenic          oz              NaN
216       59  tonnage  indicated   arsenic         NaN  surface (other)
217     4.02      NaN  indicated   arsenic         g/t  surface (other)
218        8  tonnage  indicated   arsenic          oz  surface (other)
219       59  tonnage   meas_ind   arsenic         NaN  surface (other)
220     4.02      NaN   meas_ind   arsenic         g/t  surface (other)
221        8  tonnage   meas_ind   arsenic          oz  surface (other)
222      309  tonnage   inferred   arsenic         NaN  surface (other)
223     3.99      NaN   inferred   arsenic         g/t  surface (other)
224       40  tonnage   inferred   arsenic          oz  surface (other)
225      212  tonnage  indicated   arsenic         NaN              NaN
226     2.53      NaN  indicated   arsenic         g/t              NaN
227       17  tonnage  indicated   arsenic          oz              NaN
228      212  tonnage   meas_ind   arsenic         NaN              NaN
229     2.53      NaN   meas_ind   arsenic         g/t              NaN
230       17  tonnage   meas_ind   arsenic          oz              NaN
231      308  tonnage   inferred   arsenic         NaN              NaN
232     3.40      NaN   inferred   arsenic         g/t              NaN
233       34  tonnage   inferred   arsenic          oz              NaN
234      379  tonnage   measured   arsenic         NaN              NaN
235    10.30      NaN   measured   arsenic         g/t              NaN
236      125  tonnage   measured   arsenic          oz              NaN
237     3090  tonnage  indicated   arsenic         NaN              NaN
238     5.59      NaN  indicated   arsenic         g/t              NaN
239      555  tonnage  indicated   arsenic          oz              NaN
240     3469  tonnage   meas_ind   arsenic         NaN              NaN
241     6.10      NaN   meas_ind   arsenic         g/t              NaN
242      681  tonnage   meas_ind   arsenic          oz              NaN
243     6066  tonnage   inferred   arsenic         NaN              NaN
244     6.66      NaN   inferred   arsenic         g/t              NaN
245     1299  tonnage   inferred   arsenic          oz              NaN
246    12364  tonnage  indicated   arsenic         NaN              NaN
247     2.15      NaN  indicated   arsenic         g/t              NaN
248      856  tonnage  indicated   arsenic          oz              NaN
249    12364  tonnage   meas_ind   arsenic         NaN              NaN
250     2.15      NaN   meas_ind   arsenic         g/t              NaN
251      856  tonnage   meas_ind   arsenic          oz              NaN
252      122  tonnage   inferred   arsenic         NaN              NaN
253     3.59      NaN   inferred   arsenic         g/t              NaN
254       14  tonnage   inferred   arsenic          oz              NaN
255     5806  tonnage   measured   arsenic         NaN              NaN
256     4.29      NaN   measured   arsenic         g/t              NaN
257      800  tonnage   measured   arsenic          oz              NaN
258     5884  tonnage  indicated   arsenic         NaN              NaN
259     4.75      NaN  indicated   arsenic         g/t              NaN
260      898  tonnage  indicated   arsenic          oz              NaN
261    11690  tonnage   meas_ind   arsenic         NaN              NaN
262     4.52      NaN   meas_ind   arsenic         g/t              NaN
263     1699  tonnage   meas_ind   arsenic          oz              NaN
264     9097  tonnage   inferred   arsenic         NaN              NaN
265     4.48      NaN   inferred   arsenic         g/t              NaN
266     1310  tonnage   inferred   arsenic          oz              NaN
267     3919  tonnage  indicated   arsenic         NaN              NaN
268     2.77      NaN  indicated   arsenic         g/t              NaN
269      349  tonnage  indicated   arsenic          oz              NaN
270     3919  tonnage   meas_ind   arsenic         NaN              NaN
271     2.77      NaN   meas_ind   arsenic         g/t              NaN
272      349  tonnage   meas_ind   arsenic          oz              NaN
273      867  tonnage   inferred   arsenic         NaN              NaN
274     3.84      NaN   inferred   arsenic         g/t              NaN
275      107  tonnage   inferred   arsenic          oz              NaN

file:///home/ravi/work/mining/project/articles/February202612c4626.html
13

      value   metric   category commodity measurement
0    212796  tonnage     proven   arsenic         NaN
1      0.98    grade     proven   arsenic         g/t
2      6731      NaN     proven      gold          oz
3    215249  tonnage     proven   arsenic         NaN
4      0.93    grade     proven   arsenic         g/t
5      6433      NaN     proven      gold          oz
6   1116755  tonnage   probable   arsenic         NaN
7      1.36    grade   probable   arsenic         g/t
8     48711      NaN   probable      gold          oz
9   1061639  tonnage   probable   arsenic         NaN
10     1.40    grade   probable   arsenic         g/t
11    47852      NaN   probable      gold          oz
12  1329551  tonnage  prov_prob   arsenic         NaN
13     1.30    grade  prov_prob   arsenic         g/t
14    55442      NaN  prov_prob      gold          oz
15  1276888  tonnage  prov_prob   arsenic         NaN
16     1.32    grade  prov_prob   arsenic         g/t
17    54284      NaN  prov_prob      gold          oz
18   113254  tonnage   measured   arsenic         NaN
19     1.28    grade   measured   arsenic         g/t
20     4656      NaN   measured      gold          oz
21   111028  tonnage   measured   arsenic         NaN
22     1.23    grade   measured   arsenic         g/t
23     4397      NaN   measured      gold          oz
24  1086470  tonnage  indicated   arsenic         NaN
25     1.21    grade  indicated   arsenic         g/t
26    42420      NaN  indicated      gold          oz
27  1056019  tonnage  indicated   arsenic         NaN
28     1.14    grade  indicated   arsenic         g/t
29    38553      NaN  indicated      gold          oz
30   10.0 %      NaN  indicated      gold         NaN
31  1199724  tonnage   meas_ind   arsenic         NaN
32     1.22    grade   meas_ind   arsenic         g/t
33    47076      NaN   meas_ind      gold          oz
34  1167047  tonnage   meas_ind   arsenic         NaN
35     1.14    grade   meas_ind   arsenic         g/t
36    42950      NaN   meas_ind      gold          oz
37   522289  tonnage   inferred   arsenic         NaN
38     2.49    grade   inferred   arsenic         g/t
39    41815      NaN   inferred      gold          oz
40   451483  tonnage   inferred   arsenic         NaN
41     2.49    grade   inferred   arsenic         g/t
42    36208      NaN   inferred      gold          oz
43   15.5 %      NaN   inferred      gold         NaN

file:///home/ravi/work/mining/project/articles/February202612c4626.html
16

      value   metric   category commodity measurement
0     59730  tonnage  prov_prob   arsenic         NaN
1      3.14    grade  prov_prob   arsenic         g/t
2      6026      NaN  prov_prob      gold          oz
3      2757  tonnage  prov_prob   arsenic         NaN
4      2.22    grade  prov_prob   arsenic         g/t
5       197      NaN  prov_prob      gold          oz
6      5829      NaN  prov_prob      gold          oz
7     57757  tonnage   meas_ind   arsenic         NaN
8      1.85    grade   meas_ind   arsenic         g/t
9      3442      NaN   meas_ind      gold          oz
10    64202  tonnage   meas_ind   arsenic         NaN
11     2.99    grade   meas_ind   arsenic         g/t
12     6165      NaN   meas_ind      gold          oz
13  (2,723)      NaN   meas_ind      gold          oz
14   177729  tonnage   inferred   arsenic         NaN
15     2.21    grade   inferred   arsenic         g/t
16    12652      NaN   inferred      gold          oz
17   132442  tonnage   inferred   arsenic         NaN
18     2.17    grade   inferred   arsenic         g/t
19     9233      NaN   inferred      gold          oz
20     3419      NaN   inferred      gold          oz

file:///home/ravi/work/mining/project/articles/February202612c4626.html
18

     value   metric  category commodity measurement
0    85800  tonnage  meas_ind   arsenic         NaN
1     2.00    grade  meas_ind   arsenic         g/t
2     5500      NaN  meas_ind      gold          oz
3    19000  tonnage  meas_ind   arsenic         NaN
4     1.94    grade  meas_ind   arsenic         g/t
5     1200      NaN  meas_ind      gold          oz
6     4300      NaN  meas_ind      gold          oz
7    89800  tonnage  inferred   arsenic         NaN
8     2.02    grade  inferred   arsenic         g/t
9     5800      NaN  inferred      gold          oz
10  107700  tonnage  inferred   arsenic         NaN
11    2.05    grade  inferred   arsenic         g/t
12    7100      NaN  inferred      gold          oz
13   -1300      NaN  inferred      gold          oz

file:///home/ravi/work/mining/project/articles/February202612c4626.html
19

    value   metric   category commodity measurement
0   16178  tonnage  prov_prob   arsenic         NaN
1    6.53    grade  prov_prob   arsenic         g/t
2    3396      NaN  prov_prob      gold          oz
3   16212  tonnage  prov_prob   arsenic         NaN
4    6.52    grade  prov_prob   arsenic         g/t
5    3398      NaN  prov_prob      gold          oz
6      -2      NaN  prov_prob      gold          oz
7   14946  tonnage   meas_ind   arsenic         NaN
8    4.61    grade   meas_ind   arsenic         g/t
9    2217      NaN   meas_ind      gold          oz
10  14689  tonnage   meas_ind   arsenic         NaN
11   4.54    grade   meas_ind   arsenic         g/t
12   2143      NaN   meas_ind      gold          oz
13     73      NaN   meas_ind      gold          oz
14  16868  tonnage   inferred   arsenic         NaN
15   5.98    grade   inferred   arsenic         g/t
16   3246      NaN   inferred      gold          oz
17  12232  tonnage   inferred   arsenic         NaN
18   5.44    grade   inferred   arsenic         g/t
19   2312      NaN   inferred      gold          oz
20    934      NaN   inferred      gold          oz

file:///home/ravi/work/mining/project/articles/February202612c4626.html
20

     value   metric measurement commodity  category
0   123473  tonnage         NaN       NaN       NaN
1     0.84    grade         g/t       NaN       NaN
2     3323      NaN          oz      gold       NaN
3   133367  tonnage         NaN       NaN  meas_ind
4     0.54    grade         g/t       NaN  meas_ind
5     2298      NaN          oz      gold  meas_ind
6    24053  tonnage         NaN       NaN  meas_ind
7     3.30    grade         g/t       NaN  meas_ind
8     2555      NaN          oz      gold  meas_ind
9     9219  tonnage         NaN       NaN  inferred
10    4.47    grade         g/t       NaN  inferred
11    1324      NaN          oz      gold  inferred
12   21009  tonnage         NaN       NaN  meas_ind
13    2.15    grade         g/t       NaN  meas_ind
14    1455      NaN          oz      gold  meas_ind
15   19062  tonnage         NaN       NaN  inferred
16    2.47    grade         g/t       NaN  inferred
17    1512      NaN          oz      gold  inferred

file:///home/ravi/work/mining/project/articles/February202612c4626.html
77

       value   category commodity measurement   metric
0       2469     proven   arsenic         NaN      NaN
1       4.65     proven   arsenic         g/t      NaN
2        369     proven   arsenic          oz  tonnage
3       8158   probable   arsenic         NaN  tonnage
4       6.06   probable   arsenic         g/t      NaN
5       1590   probable   arsenic          oz  tonnage
6      10627  prov_prob   arsenic         NaN  tonnage
7       5.73  prov_prob   arsenic         g/t      NaN
8       1959  prov_prob   arsenic          oz  tonnage
9       94.4  prov_prob   arsenic         NaN      NaN
10      6405     proven   arsenic         NaN      NaN
11      2.02     proven   arsenic         g/t      NaN
12       415     proven   arsenic          oz  tonnage
13      6800   probable   arsenic         NaN  tonnage
14      2.17   probable   arsenic         g/t      NaN
15       474   probable   arsenic          oz  tonnage
16     13205  prov_prob   arsenic         NaN  tonnage
17      2.09  prov_prob   arsenic         g/t      NaN
18       889  prov_prob   arsenic          oz  tonnage
19      94.5  prov_prob   arsenic         NaN      NaN
20      8874     proven   arsenic         NaN      NaN
21      2.75     proven   arsenic         g/t      NaN
22       784     proven   arsenic          oz  tonnage
23     14959   probable   arsenic         NaN  tonnage
24      4.29   probable   arsenic         g/t      NaN
25      2064   probable   arsenic          oz  tonnage
26     23832  prov_prob   arsenic         NaN  tonnage
27      3.72  prov_prob   arsenic         g/t      NaN
28      2848  prov_prob   arsenic          oz  tonnage
29     36896     proven   arsenic         NaN      NaN
30      0.50     proven   arsenic         g/t      NaN
31       597     proven   arsenic          oz  tonnage
32     21697   probable   arsenic         NaN  tonnage
33      1.22   probable   arsenic         g/t      NaN
34       852   probable   arsenic          oz  tonnage
35     58594  prov_prob   arsenic         NaN  tonnage
36      0.77  prov_prob   arsenic         g/t      NaN
37      1449  prov_prob   arsenic          oz  tonnage
38      88.8  prov_prob   arsenic         NaN      NaN
39     51618   probable   arsenic         NaN  tonnage
40      0.95   probable   arsenic         g/t      NaN
41      1577   probable   arsenic          oz  tonnage
42     51618  prov_prob   arsenic         NaN  tonnage
43      0.95  prov_prob   arsenic         g/t      NaN
44      1577  prov_prob   arsenic          oz  tonnage
45      90.0  prov_prob   arsenic         NaN      NaN
46        29     proven   arsenic         NaN      NaN
47      2.37     proven   arsenic         g/t      NaN
48         2     proven   arsenic          oz  tonnage
49      4758   probable   arsenic         NaN  tonnage
50      2.12   probable   arsenic         g/t      NaN
51       325   probable   arsenic          oz  tonnage
52      4787  prov_prob   arsenic         NaN  tonnage
53      2.12  prov_prob   arsenic         g/t      NaN
54       327  prov_prob   arsenic          oz  tonnage
55      95.0  prov_prob   arsenic         NaN      NaN
56     54943   probable   arsenic         NaN  tonnage
57      3.23   probable   arsenic         g/t      NaN
58      5699   probable   arsenic          oz  tonnage
59     54943  prov_prob   arsenic         NaN  tonnage
60      3.23  prov_prob   arsenic         g/t      NaN
61      5699  prov_prob   arsenic          oz  tonnage
62      94.4  prov_prob   arsenic         NaN      NaN
63        29     proven   arsenic         NaN      NaN
64      2.37     proven   arsenic         g/t      NaN
65         2     proven   arsenic          oz  tonnage
66     59701   probable   arsenic         NaN  tonnage
67      3.14   probable   arsenic         g/t      NaN
68      6024   probable   arsenic          oz  tonnage
69     59730  prov_prob   arsenic         NaN  tonnage
70      3.14  prov_prob   arsenic         g/t      NaN
71      6026  prov_prob   arsenic          oz  tonnage
72     36925     proven   arsenic         NaN      NaN
73      0.50     proven   arsenic         g/t      NaN
74       599     proven   arsenic          oz  tonnage
75    133016   probable   arsenic         NaN  tonnage
76      1.98   probable   arsenic         g/t      NaN
77      8453   probable   arsenic          oz  tonnage
78    169941  prov_prob   arsenic         NaN  tonnage
79      1.66  prov_prob   arsenic         g/t      NaN
80      9052  prov_prob   arsenic          oz  tonnage
81      6255     proven   arsenic         NaN      NaN
82      1.48     proven   arsenic         g/t      NaN
83       298     proven   arsenic          oz  tonnage
84      9065   probable   arsenic         NaN  tonnage
85      1.68   probable   arsenic         g/t      NaN
86       488   probable   arsenic          oz  tonnage
87     15320  prov_prob   arsenic         NaN  tonnage
88      1.60  prov_prob   arsenic         g/t      NaN
89       786  prov_prob   arsenic          oz  tonnage
90      85.9  prov_prob   arsenic         NaN      NaN
91       969     proven   arsenic         NaN      NaN
92      0.82     proven   arsenic         g/t      NaN
93        26     proven   arsenic          oz  tonnage
94      2807   probable   arsenic         NaN  tonnage
95      0.96   probable   arsenic         g/t      NaN
96        86   probable   arsenic          oz  tonnage
97      3777  prov_prob   arsenic         NaN  tonnage
98      0.92  prov_prob   arsenic         g/t      NaN
99       112  prov_prob   arsenic          oz  tonnage
100     77.6  prov_prob   arsenic         NaN      NaN
101     7225     proven   arsenic         NaN      NaN
102     1.39     proven   arsenic         g/t      NaN
103      324     proven   arsenic          oz  tonnage
104    11872   probable   arsenic         NaN  tonnage
105     1.51   probable   arsenic         g/t      NaN
106      575   probable   arsenic          oz  tonnage
107    19097  prov_prob   arsenic         NaN  tonnage
108     1.46  prov_prob   arsenic         g/t      NaN
109      898  prov_prob   arsenic          oz  tonnage
110    14757   probable   arsenic         NaN  tonnage
111     2.90   probable   arsenic         g/t      NaN
112     1377   probable   arsenic          oz  tonnage
113    14757  prov_prob   arsenic         NaN  tonnage
114     2.90  prov_prob   arsenic         g/t      NaN
115     1377  prov_prob   arsenic          oz  tonnage
116     89.7  prov_prob   arsenic         NaN      NaN
117    53023     proven   arsenic         NaN      NaN
118     1.00     proven   arsenic         g/t      NaN
119     1707     proven   arsenic          oz  tonnage
120   174603   probable   arsenic         NaN  tonnage
121     2.22   probable   arsenic         g/t      NaN
122    12468   probable   arsenic          oz  tonnage
123   227626  prov_prob   arsenic         NaN  tonnage
124     1.94  prov_prob   arsenic         g/t      NaN
125    14175  prov_prob   arsenic          oz  tonnage
126    66690     proven   arsenic         g/t      NaN
127     1.08     proven   arsenic         g/t      NaN
128     2313     proven   arsenic         g/t  tonnage
129   434448   probable   arsenic         g/t  tonnage
130     0.90   probable   arsenic         g/t      NaN
131    12641   probable   arsenic         g/t  tonnage
132   501138  prov_prob   arsenic         g/t  tonnage
133     0.93  prov_prob   arsenic         g/t      NaN
134    14954  prov_prob   arsenic         g/t  tonnage
135     88.4  prov_prob   arsenic         g/t      NaN
136    53681     proven   arsenic         g/t      NaN
137     0.42     proven   arsenic         g/t      NaN
138      722     proven   arsenic         g/t  tonnage
139   243242   probable   arsenic         g/t  tonnage
140     0.37   probable   arsenic         g/t      NaN
141     2899   probable   arsenic         g/t  tonnage
142   296923  prov_prob   arsenic         g/t  tonnage
143     0.38  prov_prob   arsenic         g/t      NaN
144     3621  prov_prob   arsenic         g/t  tonnage
145     88.4  prov_prob   arsenic         g/t      NaN
146   120371     proven   arsenic         NaN      NaN
147     0.78     proven   arsenic         g/t      NaN
148     3035     proven   arsenic          oz  tonnage
149   677690   probable   arsenic         NaN  tonnage
150     0.71   probable   arsenic         g/t      NaN
151    15540   probable   arsenic          oz  tonnage
152   798061  prov_prob   arsenic         NaN  tonnage
153     0.72  prov_prob   arsenic         g/t      NaN
154    18575  prov_prob   arsenic          oz  tonnage
155      612     proven   arsenic         NaN      NaN
156    10.43     proven   arsenic         g/t      NaN
157      205     proven   arsenic          oz  tonnage
158     6013   probable   arsenic         NaN  tonnage
159     8.68   probable   arsenic         g/t      NaN
160     1678   probable   arsenic          oz  tonnage
161     6625  prov_prob   arsenic         NaN  tonnage
162     8.84  prov_prob   arsenic         g/t      NaN
163     1883  prov_prob   arsenic          oz  tonnage
164     95.9  prov_prob   arsenic         NaN      NaN
165        3     proven   arsenic         NaN      NaN
166     2.11     proven   arsenic         g/t      NaN
167        0     proven   arsenic          oz  tonnage
168       80   probable   arsenic         NaN  tonnage
169     3.91   probable   arsenic         g/t      NaN
170       10   probable   arsenic          oz  tonnage
171       84  prov_prob   arsenic         NaN  tonnage
172     3.84  prov_prob   arsenic         g/t      NaN
173       10  prov_prob   arsenic          oz  tonnage
174     93.5  prov_prob   arsenic         NaN      NaN
175      126     proven   arsenic         NaN      NaN
176     4.35     proven   arsenic         g/t      NaN
177       18     proven   arsenic          oz  tonnage
178     1975   probable   arsenic         NaN  tonnage
179     4.54   probable   arsenic         g/t      NaN
180      288   probable   arsenic          oz  tonnage
181     2101  prov_prob   arsenic         NaN  tonnage
182     4.53  prov_prob   arsenic         g/t      NaN
183      306  prov_prob   arsenic          oz  tonnage
184     93.5  prov_prob   arsenic         NaN      NaN
185      742     proven   arsenic         NaN      NaN
186     9.36     proven   arsenic         g/t      NaN
187      223     proven   arsenic          oz  tonnage
188     8068   probable   arsenic         NaN  tonnage
189     7.62   probable   arsenic         g/t      NaN
190     1976   probable   arsenic          oz  tonnage
191     8810  prov_prob   arsenic         NaN  tonnage
192     7.77  prov_prob   arsenic         g/t      NaN
193     2200  prov_prob   arsenic          oz  tonnage
194     3235   probable   arsenic         NaN  tonnage
195     1.82   probable   arsenic         g/t      NaN
196      189   probable   arsenic          oz  tonnage
197     3235  prov_prob   arsenic         NaN  tonnage
198     1.82  prov_prob   arsenic         g/t      NaN
199      189  prov_prob   arsenic          oz  tonnage
200     95.5  prov_prob   arsenic         NaN      NaN
201    19946   probable   arsenic         NaN  tonnage
202     4.02   probable   arsenic         g/t      NaN
203     2579   probable   arsenic          oz  tonnage
204    19946  prov_prob   arsenic         NaN  tonnage
205     4.02  prov_prob   arsenic         g/t      NaN
206     2579  prov_prob   arsenic          oz  tonnage
207     95.5  prov_prob   arsenic         NaN      NaN
208    23181   probable   arsenic         NaN  tonnage
209     3.71   probable   arsenic         g/t      NaN
210     2768   probable   arsenic          oz  tonnage
211    23181  prov_prob   arsenic         NaN  tonnage
212     3.71  prov_prob   arsenic         g/t      NaN
213     2768  prov_prob   arsenic          oz  tonnage
214   123473   probable   arsenic         NaN  tonnage
215     0.84   probable   arsenic         g/t      NaN
216     3323   probable   arsenic          oz  tonnage
217   123473  prov_prob   arsenic         NaN  tonnage
218     0.84  prov_prob   arsenic         g/t      NaN
219     3323  prov_prob   arsenic          oz  tonnage
220     89.8  prov_prob   arsenic         NaN      NaN
221   121113     proven   arsenic         NaN      NaN
222     0.84     proven   arsenic         g/t      NaN
223     3258     proven   arsenic          oz  tonnage
224   832412   probable   arsenic         NaN  tonnage
225     0.88   probable   arsenic         g/t      NaN
226    23607   probable   arsenic          oz  tonnage
227   953524  prov_prob   arsenic         NaN  tonnage
228     0.88  prov_prob   arsenic         g/t      NaN
229    26865  prov_prob   arsenic          oz  tonnage
230     8048     proven   arsenic         NaN      NaN
231     1.26     proven   arsenic         g/t      NaN
232      327     proven   arsenic          oz  tonnage
233     7364   probable   arsenic         NaN  tonnage
234     3.17   probable   arsenic         g/t      NaN
235      750   probable   arsenic          oz  tonnage
236    15412  prov_prob   arsenic         NaN  tonnage
237     2.17  prov_prob   arsenic         g/t      NaN
238     1077  prov_prob   arsenic          oz  tonnage
239     90.5  prov_prob   arsenic         NaN      NaN
240       81     proven   arsenic         NaN      NaN
241     4.22     proven   arsenic         g/t      NaN
242       11     proven   arsenic          oz  tonnage
243     2221   probable   arsenic         NaN  tonnage
244     5.12   probable   arsenic         g/t      NaN
245      366   probable   arsenic          oz  tonnage
246     2302  prov_prob   arsenic         NaN  tonnage
247     5.09  prov_prob   arsenic         g/t      NaN
248      377  prov_prob   arsenic          oz  tonnage
249     90.5  prov_prob   arsenic         NaN      NaN
250     8129     proven   arsenic         NaN      NaN
251     1.29     proven   arsenic         g/t      NaN
252      338     proven   arsenic          oz  tonnage
253     9585   probable   arsenic         NaN  tonnage
254     3.62   probable   arsenic         g/t      NaN
255     1116   probable   arsenic          oz  tonnage
256    17714  prov_prob   arsenic         NaN  tonnage
257     2.55  prov_prob   arsenic         g/t      NaN
258     1454  prov_prob   arsenic          oz  tonnage
259     1142     proven   arsenic         NaN      NaN
260     4.24     proven   arsenic         g/t      NaN
261      156     proven   arsenic          oz  tonnage
262     4291   probable   arsenic         NaN  tonnage
263     3.64   probable   arsenic         g/t      NaN
264      503   probable   arsenic          oz  tonnage
265     5433  prov_prob   arsenic         NaN  tonnage
266     3.77  prov_prob   arsenic         g/t      NaN
267      658  prov_prob   arsenic          oz  tonnage
268     96.0  prov_prob   arsenic         NaN      NaN
269     2962     proven   arsenic         NaN      NaN
270     6.32     proven   arsenic         g/t      NaN
271      602     proven   arsenic          oz  tonnage
272    13680   probable   arsenic         NaN  tonnage
273     5.37   probable   arsenic         g/t      NaN
274     2362   probable   arsenic          oz  tonnage
275    16642  prov_prob   arsenic         NaN  tonnage
276     5.54  prov_prob   arsenic         g/t      NaN
277     2964  prov_prob   arsenic          oz  tonnage
278     96.0  prov_prob   arsenic         NaN      NaN
279     4104     proven   arsenic         NaN      NaN
280     5.74     proven   arsenic         g/t      NaN
281      757     proven   arsenic          oz  tonnage
282    17971   probable   arsenic         NaN  tonnage
283     4.96   probable   arsenic         g/t      NaN
284     2864   probable   arsenic          oz  tonnage
285    22075  prov_prob   arsenic         NaN  tonnage
286     5.10  prov_prob   arsenic         g/t      NaN
287     3622  prov_prob   arsenic          oz  tonnage
288       93     proven   arsenic         NaN      NaN
289     6.77     proven   arsenic         g/t      NaN
290       20     proven   arsenic          oz  tonnage
291    16086   probable   arsenic         NaN  tonnage
292     6.53   probable   arsenic         g/t      NaN
293     3376   probable   arsenic          oz  tonnage
294    16178  prov_prob   arsenic         NaN  tonnage
295     6.53  prov_prob   arsenic         g/t      NaN
296     3396  prov_prob   arsenic          oz  tonnage
297     87.5  prov_prob   arsenic         NaN      NaN
298    12325     proven   arsenic         NaN      NaN
299     2.82     proven   arsenic         g/t      NaN
300     1116     proven   arsenic          oz  tonnage
301    43642   probable   arsenic         NaN  tonnage
302     5.24   probable   arsenic         g/t      NaN
303     7356   probable   arsenic          oz  tonnage
304    55967  prov_prob   arsenic         NaN  tonnage
305     4.71  prov_prob   arsenic         g/t      NaN
306     8472  prov_prob   arsenic          oz  tonnage
307      887     proven   arsenic         NaN      NaN
308     5.41     proven   arsenic         g/t      NaN
309      154     proven   arsenic          oz  tonnage
310     9516   probable   arsenic         NaN  tonnage
311     4.95   probable   arsenic         g/t      NaN
312     1516   probable   arsenic          oz  tonnage
313    10403  prov_prob   arsenic         NaN  tonnage
314     4.99  prov_prob   arsenic         g/t      NaN
315     1670  prov_prob   arsenic          oz  tonnage
316     92.0  prov_prob   arsenic         NaN      NaN
317      887     proven   arsenic         NaN      NaN
318     5.41     proven   arsenic         g/t      NaN
319      154     proven   arsenic          oz  tonnage
320     9516   probable   arsenic         NaN  tonnage
321     4.95   probable   arsenic         g/t      NaN
322     1516   probable   arsenic          oz  tonnage
323    10403  prov_prob   arsenic         NaN  tonnage
324     4.99  prov_prob   arsenic         g/t      NaN
325     1670  prov_prob   arsenic          oz  tonnage
326      931     proven   arsenic         NaN      NaN
327     4.66     proven   arsenic         g/t      NaN
328      140     proven   arsenic          oz  tonnage
329    23818   probable   arsenic         NaN  tonnage
330     4.15   probable   arsenic         g/t      NaN
331     3179   probable   arsenic          oz  tonnage
332    24749  prov_prob   arsenic         NaN  tonnage
333     4.17  prov_prob   arsenic         g/t      NaN
334     3319  prov_prob   arsenic          oz  tonnage
335     86.0  prov_prob   arsenic         NaN      NaN
336      931     proven   arsenic         NaN      NaN
337     4.66     proven   arsenic         g/t      NaN
338      140     proven   arsenic          oz  tonnage
339    23818   probable   arsenic         NaN  tonnage
340     4.15   probable   arsenic         g/t      NaN
341     3179   probable   arsenic          oz  tonnage
342    24749  prov_prob   arsenic         NaN  tonnage
343     4.17  prov_prob   arsenic         g/t      NaN
344     3319  prov_prob   arsenic          oz  tonnage
345       26     proven   arsenic         NaN      NaN
346     0.60     proven   arsenic         g/t      NaN
347        1     proven   arsenic          oz  tonnage
348     1629   probable   arsenic         NaN  tonnage
349     1.00   probable   arsenic         g/t      NaN
350       53   probable   arsenic          oz  tonnage
351     1656  prov_prob   arsenic         NaN  tonnage
352     1.00  prov_prob   arsenic         g/t      NaN
353       53  prov_prob   arsenic          oz  tonnage
354     93.6  prov_prob   arsenic         NaN      NaN
355      633     proven   arsenic         NaN      NaN
356     2.06     proven   arsenic         g/t      NaN
357       42     proven   arsenic          oz  tonnage
358     2374   probable   arsenic         NaN  tonnage
359     2.29   probable   arsenic         g/t      NaN
360      175   probable   arsenic          oz  tonnage
361     3007  prov_prob   arsenic         NaN  tonnage

file:///home/ravi/work/mining/project/articles/February202612c4626.html
79

       value   metric   category commodity measurement         minetype
0       6457  tonnage  indicated   arsenic         NaN              NaN
1       3.59      NaN  indicated   arsenic         g/t              NaN
2        746  tonnage  indicated   arsenic          oz              NaN
3       6457  tonnage   meas_ind   arsenic         NaN              NaN
4       3.59      NaN   meas_ind   arsenic         g/t              NaN
5        746  tonnage   meas_ind   arsenic          oz              NaN
6       1366  tonnage   inferred   arsenic         NaN              NaN
7       6.03      NaN   inferred   arsenic         g/t              NaN
8        265  tonnage   inferred   arsenic          oz              NaN
9      24207  tonnage  indicated   arsenic         NaN              NaN
10      1.93      NaN  indicated   arsenic         g/t              NaN
11      1506  tonnage  indicated   arsenic          oz              NaN
12     24207  tonnage   meas_ind   arsenic         NaN              NaN
13      1.93      NaN   meas_ind   arsenic         g/t              NaN
14      1506  tonnage   meas_ind   arsenic          oz              NaN
15     11677  tonnage   inferred   arsenic         NaN              NaN
16      3.00      NaN   inferred   arsenic         g/t              NaN
17      1127  tonnage   inferred   arsenic          oz              NaN
18     30664  tonnage  indicated   arsenic         NaN              NaN
19      2.28      NaN  indicated   arsenic         g/t              NaN
20      2251  tonnage  indicated   arsenic          oz              NaN
21     30664  tonnage   meas_ind   arsenic         NaN              NaN
22      2.28      NaN   meas_ind   arsenic         g/t              NaN
23      2251  tonnage   meas_ind   arsenic          oz              NaN
24     13043  tonnage   inferred   arsenic         NaN              NaN
25      3.32      NaN   inferred   arsenic         g/t              NaN
26      1392  tonnage   inferred   arsenic          oz              NaN
27      5011  tonnage   inferred   arsenic         NaN              NaN
28      0.73      NaN   inferred   arsenic         g/t              NaN
29       118  tonnage   inferred   arsenic          oz              NaN
30      3875  tonnage  indicated   arsenic         NaN              NaN
31      0.51      NaN  indicated   arsenic         g/t              NaN
32        63  tonnage  indicated   arsenic          oz              NaN
33      3875  tonnage   meas_ind   arsenic         NaN              NaN
34      0.51      NaN   meas_ind   arsenic         g/t              NaN
35        63  tonnage   meas_ind   arsenic          oz              NaN
36      2956  tonnage   inferred   arsenic         NaN              NaN
37      0.66      NaN   inferred   arsenic         g/t              NaN
38        63  tonnage   inferred   arsenic          oz              NaN
39      4544  tonnage   inferred   arsenic         NaN              NaN
40      2.14      NaN   inferred   arsenic         g/t              NaN
41       313  tonnage   inferred   arsenic          oz              NaN
42     14794  tonnage  indicated   arsenic         NaN              NaN
43      1.22      NaN  indicated   arsenic         g/t              NaN
44       582  tonnage  indicated   arsenic          oz              NaN
45     14794  tonnage   meas_ind   arsenic         NaN              NaN
46      1.22      NaN   meas_ind   arsenic         g/t              NaN
47       582  tonnage   meas_ind   arsenic          oz              NaN
48     11272  tonnage   inferred   arsenic         NaN              NaN
49      1.08      NaN   inferred   arsenic         g/t              NaN
50       390  tonnage   inferred   arsenic          oz              NaN
51       296  tonnage  indicated   arsenic         NaN              NaN
52      3.36      NaN  indicated   arsenic         g/t              NaN
53        32  tonnage  indicated   arsenic          oz              NaN
54       296  tonnage   meas_ind   arsenic         NaN              NaN
55      3.36      NaN   meas_ind   arsenic         g/t              NaN
56        32  tonnage   meas_ind   arsenic          oz              NaN
57       183  tonnage   inferred   arsenic         NaN              NaN
58      3.37      NaN   inferred   arsenic         g/t              NaN
59        20  tonnage   inferred   arsenic          oz              NaN
60      4493  tonnage  indicated   arsenic         NaN              NaN
61      1.63      NaN  indicated   arsenic         g/t              NaN
62       236  tonnage  indicated   arsenic          oz              NaN
63      4493  tonnage   meas_ind   arsenic         NaN              NaN
64      1.63      NaN   meas_ind   arsenic         g/t              NaN
65       236  tonnage   meas_ind   arsenic          oz              NaN
66     20176  tonnage   inferred   arsenic         NaN              NaN
67      2.23      NaN   inferred   arsenic         g/t              NaN
68      1445  tonnage   inferred   arsenic          oz              NaN
69     48216  tonnage  indicated   arsenic         NaN              NaN
70      1.92      NaN  indicated   arsenic         g/t              NaN
71      2976  tonnage  indicated   arsenic          oz              NaN
72     48216  tonnage   meas_ind   arsenic         NaN              NaN
73      1.92      NaN   meas_ind   arsenic         g/t              NaN
74      2976  tonnage   meas_ind   arsenic          oz              NaN
75     63275  tonnage   inferred   arsenic         NaN              NaN
76      1.89      NaN   inferred   arsenic         g/t              NaN
77      3835  tonnage   inferred   arsenic          oz              NaN
78      5048  tonnage  indicated   arsenic         NaN              NaN
79      1.42      NaN  indicated   arsenic         g/t              NaN
80       230  tonnage  indicated   arsenic          oz              NaN
81      5048  tonnage   meas_ind   arsenic         NaN              NaN
82      1.42      NaN   meas_ind   arsenic         g/t              NaN
83       230  tonnage   meas_ind   arsenic          oz              NaN
84     94278  tonnage   inferred   arsenic         NaN              NaN
85      2.43      NaN   inferred   arsenic         g/t              NaN
86      7372  tonnage   inferred   arsenic          oz              NaN
87     57757  tonnage  indicated   arsenic         NaN              NaN
88      1.85      NaN  indicated   arsenic         g/t              NaN
89      3442  tonnage  indicated   arsenic          oz              NaN
90     57757  tonnage   meas_ind   arsenic         NaN              NaN
91      1.85      NaN   meas_ind   arsenic         g/t              NaN
92      3442  tonnage   meas_ind   arsenic          oz              NaN
93    177729  tonnage   inferred   arsenic         NaN              NaN
94      2.21      NaN   inferred   arsenic         g/t              NaN
95     12652  tonnage   inferred   arsenic          oz              NaN
96     76723  tonnage  indicated   arsenic         NaN              NaN
97      1.67      NaN  indicated   arsenic         g/t              NaN
98      4120  tonnage  indicated   arsenic          oz              NaN
99     76723  tonnage   meas_ind   arsenic         NaN              NaN
100     1.67      NaN   meas_ind   arsenic         g/t              NaN
101     4120  tonnage   meas_ind   arsenic          oz              NaN
102   201694  tonnage   inferred   arsenic         NaN              NaN
103     2.09      NaN   inferred   arsenic         g/t              NaN
104    13556  tonnage   inferred   arsenic          oz              NaN
105    12360  tonnage   measured   arsenic         NaN              NaN
106     1.86      NaN   measured   arsenic         g/t              NaN
107      739  tonnage   measured   arsenic          oz              NaN
108    21245  tonnage  indicated   arsenic         NaN              NaN
109     1.45      NaN  indicated   arsenic         g/t              NaN
110      988  tonnage  indicated   arsenic          oz              NaN
111    33604  tonnage   meas_ind   arsenic         NaN              NaN
112     1.60      NaN   meas_ind   arsenic         g/t              NaN
113     1727  tonnage   meas_ind   arsenic          oz              NaN
114    17951  tonnage   inferred   arsenic         NaN              NaN
115     1.46      NaN   inferred   arsenic         g/t              NaN
116      842  tonnage   inferred   arsenic          oz              NaN
117      130  tonnage  indicated   arsenic         NaN              NaN
118     0.38      NaN  indicated   arsenic         g/t              NaN
119        2  tonnage  indicated   arsenic          oz              NaN
120      130  tonnage   meas_ind   arsenic         NaN              NaN
121     0.38      NaN   meas_ind   arsenic         g/t              NaN
122        2  tonnage   meas_ind   arsenic          oz              NaN
123      966  tonnage   inferred   arsenic         NaN              NaN
124     1.60      NaN   inferred   arsenic         g/t              NaN
125       50  tonnage   inferred   arsenic          oz              NaN
126    12360  tonnage   measured   arsenic         NaN              NaN
127     1.86      NaN   measured   arsenic         g/t              NaN
128      739  tonnage   measured   arsenic          oz              NaN
129    21374  tonnage  indicated   arsenic         NaN              NaN
130     1.44      NaN  indicated   arsenic         g/t              NaN
131      989  tonnage  indicated   arsenic          oz              NaN
132    33734  tonnage   meas_ind   arsenic         NaN              NaN
133     1.59      NaN   meas_ind   arsenic         g/t              NaN
134     1728  tonnage   meas_ind   arsenic          oz              NaN
135    18917  tonnage   inferred   arsenic         NaN              NaN
136     1.47      NaN   inferred   arsenic         g/t              NaN
137      892  tonnage   inferred   arsenic          oz              NaN
138     3052  tonnage   inferred   arsenic         NaN              NaN
139     3.24      NaN   inferred   arsenic         g/t              NaN
140      318  tonnage   inferred   arsenic          oz              NaN
141     9479  tonnage  indicated   arsenic         NaN              NaN
142     2.19      NaN  indicated   arsenic         g/t              NaN
143      667  tonnage  indicated   arsenic          oz              NaN
144     9479  tonnage   meas_ind   arsenic         NaN              NaN
145     2.19      NaN   meas_ind   arsenic         g/t              NaN
146      667  tonnage   meas_ind   arsenic          oz              NaN
147     3911  tonnage   inferred   arsenic         NaN              NaN
148     2.48      NaN   inferred   arsenic         g/t              NaN
149      312  tonnage   inferred   arsenic          oz              NaN
150    12360  tonnage   measured   arsenic         NaN              NaN
151     1.86      NaN   measured   arsenic         g/t              NaN
152      739  tonnage   measured   arsenic          oz              NaN
153   138241  tonnage  indicated   arsenic         NaN              NaN
154     1.81      NaN  indicated   arsenic         g/t              NaN
155     8027  tonnage  indicated   arsenic          oz              NaN
156   150601  tonnage   meas_ind   arsenic         NaN              NaN
157     1.81      NaN   meas_ind   arsenic         g/t              NaN
158     8766  tonnage   meas_ind   arsenic          oz              NaN
159   240618  tonnage   inferred   arsenic         NaN              NaN
160     2.13      NaN   inferred   arsenic         g/t              NaN
161    16469  tonnage   inferred   arsenic          oz              NaN
162    35300  tonnage   measured   arsenic         NaN              NaN
163     1.16      NaN   measured   arsenic         g/t              NaN
164     1312  tonnage   measured   arsenic          oz              NaN
165   587007  tonnage  indicated   arsenic         NaN              NaN
166     0.66      NaN  indicated   arsenic         g/t              NaN
167    12373  tonnage  indicated   arsenic          oz              NaN
168   622307  tonnage   meas_ind   arsenic         NaN              NaN
169     0.68      NaN   meas_ind   arsenic         g/t              NaN
170    13685  tonnage   meas_ind   arsenic          oz              NaN
171    51442  tonnage   inferred   arsenic         NaN              NaN
172     1.38      NaN   inferred   arsenic         g/t              NaN
173     2290  tonnage   inferred   arsenic          oz              NaN
174    52924  tonnage  indicated   arsenic         NaN              NaN
175     2.04      NaN  indicated   arsenic         g/t              NaN
176     3472  tonnage  indicated   arsenic          oz              NaN
177    52924  tonnage   meas_ind   arsenic         NaN              NaN
178     2.04      NaN   meas_ind   arsenic         g/t              NaN
179     3472  tonnage   meas_ind   arsenic          oz              NaN
180    59549  tonnage   inferred   arsenic         NaN              NaN
181     2.03      NaN   inferred   arsenic         g/t              NaN
182     3878  tonnage   inferred   arsenic          oz              NaN
183     2868  tonnage  indicated   arsenic         NaN              NaN
184     5.80      NaN  indicated   arsenic         g/t              NaN
185      534  tonnage  indicated   arsenic          oz              NaN
186     2868  tonnage   meas_ind   arsenic         NaN              NaN
187     5.80      NaN   meas_ind   arsenic         g/t              NaN
188      534  tonnage   meas_ind   arsenic          oz              NaN
189      973  tonnage   inferred   arsenic         NaN              NaN
190     4.35      NaN   inferred   arsenic         g/t              NaN
191      136  tonnage   inferred   arsenic          oz              NaN
192    35300  tonnage   measured   arsenic         NaN              NaN
193     1.16      NaN   measured   arsenic         g/t              NaN
194     1312  tonnage   measured   arsenic          oz              NaN
195   642798  tonnage  indicated   arsenic         NaN              NaN
196     0.79      NaN  indicated   arsenic         g/t              NaN
197    16379  tonnage  indicated   arsenic          oz              NaN
198   678098  tonnage   meas_ind   arsenic         NaN              NaN
199     0.81      NaN   meas_ind   arsenic         g/t              NaN
200    17691  tonnage   meas_ind   arsenic          oz              NaN
201   111964  tonnage   inferred   arsenic         NaN              NaN
202     1.75      NaN   inferred   arsenic         g/t              NaN
203     6304  tonnage   inferred   arsenic          oz              NaN
204      379  tonnage   measured   arsenic         NaN              NaN
205    10.30      NaN   measured   arsenic         g/t              NaN
206      125  tonnage   measured   arsenic          oz              NaN
207     2818  tonnage  indicated   arsenic         NaN              NaN
208     5.85      NaN  indicated   arsenic         g/t              NaN
209      530  tonnage  indicated   arsenic          oz              NaN
210     3197  tonnage   meas_ind   arsenic         NaN              NaN
211     6.38      NaN   meas_ind   arsenic         g/t              NaN
212      656  tonnage   meas_ind   arsenic          oz              NaN
213     5448  tonnage   inferred   arsenic         NaN              NaN
214     7.00      NaN   inferred   arsenic         g/t              NaN
215     1226  tonnage   inferred   arsenic          oz              NaN
216       59  tonnage  indicated   arsenic         NaN  surface (other)
217     4.02      NaN  indicated   arsenic         g/t  surface (other)
218        8  tonnage  indicated   arsenic          oz  surface (other)
219       59  tonnage   meas_ind   arsenic         NaN  surface (other)
220     4.02      NaN   meas_ind   arsenic         g/t  surface (other)
221        8  tonnage   meas_ind   arsenic          oz  surface (other)
222      309  tonnage   inferred   arsenic         NaN  surface (other)
223     3.99      NaN   inferred   arsenic         g/t  surface (other)
224       40  tonnage   inferred   arsenic          oz  surface (other)
225      212  tonnage  indicated   arsenic         NaN              NaN
226     2.53      NaN  indicated   arsenic         g/t              NaN
227       17  tonnage  indicated   arsenic          oz              NaN
228      212  tonnage   meas_ind   arsenic         NaN              NaN
229     2.53      NaN   meas_ind   arsenic         g/t              NaN
230       17  tonnage   meas_ind   arsenic          oz              NaN
231      308  tonnage   inferred   arsenic         NaN              NaN
232     3.40      NaN   inferred   arsenic         g/t              NaN
233       34  tonnage   inferred   arsenic          oz              NaN
234      379  tonnage   measured   arsenic         NaN              NaN
235    10.30      NaN   measured   arsenic         g/t              NaN
236      125  tonnage   measured   arsenic          oz              NaN
237     3090  tonnage  indicated   arsenic         NaN              NaN
238     5.59      NaN  indicated   arsenic         g/t              NaN
239      555  tonnage  indicated   arsenic          oz              NaN
240     3469  tonnage   meas_ind   arsenic         NaN              NaN
241     6.10      NaN   meas_ind   arsenic         g/t              NaN
242      681  tonnage   meas_ind   arsenic          oz              NaN
243     6066  tonnage   inferred   arsenic         NaN              NaN
244     6.66      NaN   inferred   arsenic         g/t              NaN
245     1299  tonnage   inferred   arsenic          oz              NaN
246    12364  tonnage  indicated   arsenic         NaN              NaN
247     2.15      NaN  indicated   arsenic         g/t              NaN
248      856  tonnage  indicated   arsenic          oz              NaN
249    12364  tonnage   meas_ind   arsenic         NaN              NaN
250     2.15      NaN   meas_ind   arsenic         g/t              NaN
251      856  tonnage   meas_ind   arsenic          oz              NaN
252      122  tonnage   inferred   arsenic         NaN              NaN
253     3.59      NaN   inferred   arsenic         g/t              NaN
254       14  tonnage   inferred   arsenic          oz              NaN
255     5806  tonnage   measured   arsenic         NaN              NaN
256     4.29      NaN   measured   arsenic         g/t              NaN
257      800  tonnage   measured   arsenic          oz              NaN
258     5884  tonnage  indicated   arsenic         NaN              NaN
259     4.75      NaN  indicated   arsenic         g/t              NaN
260      898  tonnage  indicated   arsenic          oz              NaN
261    11690  tonnage   meas_ind   arsenic         NaN              NaN
262     4.52      NaN   meas_ind   arsenic         g/t              NaN
263     1699  tonnage   meas_ind   arsenic          oz              NaN
264     9097  tonnage   inferred   arsenic         NaN              NaN
265     4.48      NaN   inferred   arsenic         g/t              NaN
266     1310  tonnage   inferred   arsenic          oz              NaN
267     3919  tonnage  indicated   arsenic         NaN              NaN
268     2.77      NaN  indicated   arsenic         g/t              NaN
269      349  tonnage  indicated   arsenic          oz              NaN
270     3919  tonnage   meas_ind   arsenic         NaN              NaN
271     2.77      NaN   meas_ind   arsenic         g/t              NaN
272      349  tonnage   meas_ind   arsenic          oz              NaN
273      867  tonnage   inferred   arsenic         NaN              NaN
274     3.84      NaN   inferred   arsenic         g/t              NaN
275      107  tonnage   inferred   arsenic          oz              NaN

file:///home/ravi/work/mining/project/articles/February202611c7224.html
1

    value metric  category measurement commodity
0      63  grade  measured         g/t      gold
1    0.93  grade       NaN         g/t      gold
2    1.14    NaN       NaN         g/t      gold
3      24  grade  measured         NaN      gold
4    1.78  grade       NaN         g/t      gold
5      39    NaN  measured         NaN      gold
6    1.53    NaN       NaN         g/t      gold
7      70  grade  measured         g/t      gold
8    1.42  grade       NaN         g/t      gold
9    1.23    NaN       NaN         g/t      gold
10     37  grade  measured         NaN      gold
11   2.21  grade       NaN         g/t      gold
12     52    NaN  measured         NaN      gold
13   1.49    NaN       NaN         g/t      gold
14     64  grade  measured         g/t      gold
15   1.54  grade       NaN         g/t      gold
16   1.07    NaN       NaN         g/t      gold
17     43  grade  measured         NaN      gold
18   2.06  grade       NaN         g/t      gold
19     41    NaN  measured         NaN      gold
20   1.35    NaN       NaN         g/t      gold
21     66  grade  measured         g/t      gold
22   1.02  grade       NaN         g/t      gold
23   1.18    NaN       NaN         g/t      gold
24     41  grade  measured         NaN      gold
25   1.42  grade       NaN         g/t      gold
26     41    NaN  measured         NaN      gold
27   1.65    NaN       NaN         g/t      gold
28     64  grade  measured         g/t      gold
29   1.17  grade       NaN         g/t      gold
30   2.22    NaN       NaN         g/t      gold
31     35  grade  measured         NaN      gold
32   2.06  grade       NaN         g/t      gold
33     51    NaN  measured         NaN      gold
34   2.63    NaN       NaN         g/t      gold
35     64  grade  measured         g/t      gold
36   0.92  grade       NaN         g/t      gold
37   1.23    NaN       NaN         g/t      gold
38     15  grade  measured         NaN      gold
39   2.22  grade       NaN         g/t      gold
40     46    NaN  measured         NaN      gold
41   1.58    NaN       NaN         g/t      gold
42     63  grade  measured         g/t      gold
43   0.99  grade       NaN         g/t      gold
44   1.51    NaN       NaN         g/t      gold
45     31  grade  measured         NaN      gold
46   1.47  grade       NaN         g/t      gold
47     46    NaN  measured         NaN      gold
48   1.93    NaN       NaN         g/t      gold
49     62  grade  measured         g/t      gold
50   0.90  grade       NaN         g/t      gold
51   0.95    NaN       NaN         g/t      gold
52     11  grade  measured         NaN      gold
53   2.78  grade       NaN         g/t      gold
54     36    NaN  measured         NaN      gold
55   1.24    NaN       NaN         g/t      gold
56     63  grade  measured         g/t      gold
57   0.89  grade       NaN         g/t      gold
58   1.00    NaN       NaN         g/t      gold
59     31  grade  measured         NaN      gold
60   1.32  grade       NaN         g/t      gold
61     36    NaN  measured         NaN      gold
62   1.45    NaN       NaN         g/t      gold
63     66  grade  measured         g/t      gold
64   1.08  grade       NaN         g/t      gold
65   1.14    NaN       NaN         g/t      gold
66     31  grade  measured         NaN      gold
67   1.86  grade       NaN         g/t      gold
68     41    NaN  measured         NaN      gold
69   1.52    NaN       NaN         g/t      gold
70     66  grade  measured         g/t      gold
71   0.74  grade       NaN         g/t      gold
72   1.20    NaN       NaN         g/t      gold
73     25  grade  measured         NaN      gold
74   1.24  grade       NaN         g/t      gold
75     46    NaN  measured         NaN      gold
76   1.45    NaN       NaN         g/t      gold
77     65  grade  measured         g/t      gold
78   1.42  grade       NaN         g/t      gold
79   0.92    NaN       NaN         g/t      gold
80     26  grade  measured         NaN      gold
81   2.92  grade       NaN         g/t      gold
82     41    NaN  measured         NaN      gold
83   1.22    NaN       NaN         g/t      gold
84     64  grade  measured         g/t      gold
85   2.54  grade       NaN         g/t      gold
86   0.92    NaN       NaN         g/t      gold
87     36  grade  measured         NaN      gold
88   4.16  grade       NaN         g/t      gold
89     46    NaN  measured         NaN      gold
90   1.07    NaN       NaN         g/t      gold
91     65  grade  measured         g/t      gold
92   1.75  grade       NaN         g/t      gold
93   1.51    NaN       NaN         g/t      gold
94     51  grade  measured         NaN      gold
95   2.13  grade       NaN         g/t      gold
96     46    NaN  measured         NaN      gold
97   1.97    NaN       NaN         g/t      gold
98     62  grade  measured         g/t      gold
99   0.90  grade       NaN         g/t      gold
100  1.41    NaN       NaN         g/t      gold
101    25  grade  measured         NaN      gold
102  1.58  grade       NaN         g/t      gold
103    51    NaN  measured         NaN      gold
104  1.61    NaN       NaN         g/t      gold
105    66  grade  measured         g/t      gold
106  0.91  grade       NaN         g/t      gold
107  1.25    NaN       NaN         g/t      gold
108    31  grade  measured         NaN      gold
109  1.47  grade       NaN         g/t      gold
110    51    NaN  measured         NaN      gold
111  1.48    NaN       NaN         g/t      gold
112    66  grade  measured         g/t      gold
113  0.71  grade       NaN         g/t      gold
114  1.07    NaN       NaN         g/t      gold
115    25  grade  measured         NaN      gold
116  1.09  grade       NaN         g/t      gold
117    46    NaN  measured         NaN      gold
118  1.27    NaN       NaN         g/t      gold
119    66  grade  measured         g/t      gold
120  1.46  grade       NaN         g/t      gold
121  1.15    NaN       NaN         g/t      gold
122    36  grade  measured         NaN      gold
123  2.32  grade       NaN         g/t      gold
124    51    NaN  measured         NaN      gold
125  1.32    NaN       NaN         g/t      gold
126    64  grade  measured         g/t      gold
127  0.84  grade       NaN         g/t      gold
128  1.72    NaN       NaN         g/t      gold
129    31  grade  measured         NaN      gold
130  1.32  grade       NaN         g/t      gold
131    51    NaN  measured         NaN      gold
132  1.99    NaN       NaN         g/t      gold
133    64  grade  measured         g/t      gold
134  0.93  grade       NaN         g/t      gold
135  1.55    NaN       NaN         g/t      gold
136    31  grade  measured         NaN      gold
137  1.56  grade       NaN         g/t      gold
138    41    NaN  measured         NaN      gold
139  2.16    NaN       NaN         g/t      gold
140    65  grade  measured         g/t      gold
141  1.60  grade       NaN         g/t      gold
142  1.37    NaN       NaN         g/t      gold
143    35  grade  measured         NaN      gold
144  2.57  grade       NaN         g/t      gold
145    55    NaN  measured         NaN      gold
146  1.51    NaN       NaN         g/t      gold
147    64  grade  measured         g/t      gold
148  1.39  grade       NaN         g/t      gold
149  1.59    NaN       NaN         g/t      gold
150    43  grade  measured         NaN      gold
151  1.78  grade       NaN         g/t      gold
152    64    NaN  measured         NaN      gold
153  1.59    NaN       NaN         g/t      gold
154    66  grade  measured         g/t      gold
155  0.81  grade       NaN         g/t      gold
156  1.45    NaN       NaN         g/t      gold
157    25  grade  measured         NaN      gold
158  1.32  grade       NaN         g/t      gold
159    51    NaN  measured         NaN      gold
160  1.70    NaN       NaN         g/t      gold
161    66  grade  measured         g/t      gold
162  2.02  grade       NaN         g/t      gold
163  1.64    NaN       NaN         g/t      gold
164    50  grade  measured         NaN      gold
165  2.60  grade       NaN         g/t      gold
166    61    NaN  measured         NaN      gold
167  1.71    NaN       NaN         g/t      gold
168    66  grade  measured         g/t      gold
169  3.09  grade       NaN         g/t      gold
170  2.08    NaN       NaN         g/t      gold
171    51  grade  measured         NaN      gold
172  3.83  grade       NaN         g/t      gold
173    51    NaN  measured         NaN      gold
174  2.55    NaN       NaN         g/t      gold
175    66  grade  measured         g/t      gold
176  0.93  grade       NaN         g/t      gold
177  1.00    NaN       NaN         g/t      gold
178    35  grade  measured         NaN      gold
179  1.29  grade       NaN         g/t      gold
180    51    NaN  measured         NaN      gold
181  1.13    NaN       NaN         g/t      gold
182    66  grade  measured         g/t      gold
183  1.40  grade       NaN         g/t      gold
184  2.01    NaN       NaN         g/t      gold
185    56  grade  measured         NaN      gold
186  1.53  grade       NaN         g/t      gold
187    56    NaN  measured         NaN      gold
188  2.25    NaN       NaN         g/t      gold
189    66  grade  measured         g/t      gold
190  1.50  grade       NaN         g/t      gold
191  1.84    NaN       NaN         g/t      gold
192    45  grade  measured         NaN      gold
193  1.93  grade       NaN         g/t      gold
194    61    NaN  measured         NaN      gold
195  1.93    NaN       NaN         g/t      gold
196    66  grade  measured         g/t      gold
197  1.51  grade       NaN         g/t      gold
198  1.38    NaN       NaN         g/t      gold
199    45  grade  measured         NaN      gold
200  1.96  grade       NaN         g/t      gold
201    66    NaN  measured         NaN      gold
202  1.38    NaN       NaN         g/t      gold
203    66  grade  measured         g/t      gold
204  1.21  grade       NaN         g/t      gold
205  1.49    NaN       NaN         g/t      gold
206    35  grade  measured         NaN      gold
207  1.85  grade       NaN         g/t      gold
208    56    NaN  measured         NaN      gold
209  1.64    NaN       NaN         g/t      gold
210    66  grade  measured         g/t      gold
211  1.92  grade       NaN         g/t      gold
212  1.24    NaN       NaN         g/t      gold
213    56  grade  measured         NaN      gold
214  2.14  grade       NaN         g/t      gold
215    61    NaN  measured         NaN      gold
216  1.28    NaN       NaN         g/t      gold
217    66  grade  measured         g/t      gold
218  4.25  grade       NaN         g/t      gold
219  1.98    NaN       NaN         g/t      gold
220    56  grade  measured         NaN      gold
221  4.92  grade       NaN         g/t      gold
222    56    NaN  measured         NaN      gold
223  2.23    NaN       NaN         g/t      gold
224    66  grade  measured         g/t      gold
225  2.25  grade       NaN         g/t      gold
226  2.17    NaN       NaN         g/t      gold
227    61  grade  measured         NaN      gold
228  2.37  grade       NaN         g/t      gold
229    61    NaN  measured         NaN      gold
230  2.31    NaN       NaN         g/t      gold
231    66  grade  measured         g/t      gold
232  3.02  grade       NaN         g/t      gold
233  1.52    NaN       NaN         g/t      gold
234    51  grade  measured         NaN      gold
235  3.80  grade       NaN         g/t      gold
236    41    NaN  measured         NaN      gold
237  2.00    NaN       NaN         g/t      gold
238    66  grade  measured         g/t      gold
239  1.51  grade       NaN         g/t      gold
240  1.16    NaN       NaN         g/t      gold
241    40  grade  measured         NaN      gold
242  2.11  grade       NaN         g/t      gold
243    50    NaN  measured         NaN      gold
244  1.29    NaN       NaN         g/t      gold
245    66  grade  measured         g/t      gold
246  1.24  grade       NaN         g/t      gold
247  0.90    NaN       NaN         g/t      gold
248    45  grade  measured         NaN      gold
249  1.54  grade       NaN         g/t      gold
250    36    NaN  measured         NaN      gold
251  1.21    NaN       NaN         g/t      gold
252  2355  grade  measured         g/t      gold
253  1.47  grade       NaN         g/t      gold
254  1.40    NaN       NaN         g/t      gold
255  1358  grade  measured         NaN      gold
256  2.21  grade       NaN         g/t      gold
257  1788    NaN  measured         NaN      gold
258  1.68    NaN       NaN         g/t      gold

file:///home/ravi/work/mining/project/articles/February202610c0112.html
17

     value   category commodity     minetype measurement     metric
0  3516000  indicated      gold  underground         g/t    tonnage
1     4.41  indicated      gold  underground         g/t      grade
2   499000  indicated      gold  underground         g/t  contained
3  5490000   inferred      gold  underground         g/t    tonnage
4     3.65   inferred      gold  underground         g/t      grade
5   644000   inferred      gold  underground         g/t  contained

KeyError: ['metric', 'category']

In [101]:
test = pd.read_html("/home/ravi/work/mining/project/articles/February202618c1164.html")

In [107]:
test[4].to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n      <th>3</th>\n      <th>4</th>\n      <th>5</th>\n      <th>6</th>\n      <th>7</th>\n      <th>8</th>\n      <th>9</th>\n      <th>10</th>\n      <th>11</th>\n      <th>12</th>\n      <th>13</th>\n      <th>14</th>\n      <th>15</th>\n      <th>16</th>\n      <th>17</th>\n      <th>18</th>\n      <th>19</th>\n      <th>20</th>\n      <th>21</th>\n      <th>22</th>\n      <th>23</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>Mineral Resources (100% basis,\xa0inclusive of Reserves)</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Grade</td>\n      <td>Grade</td>\n      <td>Grade</td>\n      <td>Grade</td>\n      <td>Grade</td>\n      <td>Grade</td>\n      <td>Grade</td>\n      <td>Grade</td>\n      <td>NaN</td>\n      <td>Contained Metal</td>\n      <td>Contained Metal</td>\n      <td>Contained Metal</td>\n      <td>Contained Metal</td>\n      <td>Contained Metal</td>\n      <td>Contained Metal</td>\n      <td>Contained Metal</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Site</td>\n      <td>Site</td>\n      <td>Category</td>\n      <td>Category</td>\n      <td>Tonnes kt</td>\n      <td>Tonnes kt</td>\n      <td>Tonnes kt</td>\n      <td>Cu %</td>\n      <td>Au g/t</td>\n      <td>Au g/t</td>\n      <td>Ag g/t</td>\n      <td>Ag g/t</td>\n      <td>Mo ppm</td>\n      <td>Mo ppm</td>\n      <td>Mo ppm</td>\n      <td>NaN</td>\n      <td>Cu kt</td>\n      <td>Cu kt</td>\n      <td>Au Koz</td>\n      <td>Au Koz</td>\n      <td>Ag Koz</td>\n      <td>Mo kt</td>\n      <td>Interest %</td>\n      <td>Interest %</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Candelaria</td>\n      <td>Candelaria</td>\n      <td>Measured</td>\n      <td>Measured</td>\n      <td>487110</td>\n      <td>487110</td>\n      <td>487110</td>\n      <td>0.40</td>\n      <td>0.10</td>\n      <td>0.10</td>\n      <td>1.36</td>\n      <td>1.36</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>1948</td>\n      <td>1948</td>\n      <td>1519</td>\n      <td>1519</td>\n      <td>21236</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Open Pit</td>\n      <td>Open Pit</td>\n      <td>Indicated</td>\n      <td>Indicated</td>\n      <td>65339</td>\n      <td>65339</td>\n      <td>65339</td>\n      <td>0.26</td>\n      <td>0.07</td>\n      <td>0.07</td>\n      <td>1.02</td>\n      <td>1.02</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>170</td>\n      <td>170</td>\n      <td>151</td>\n      <td>151</td>\n      <td>2147</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>M&amp;I</td>\n      <td>M&amp;I</td>\n      <td>552449</td>\n      <td>552449</td>\n      <td>552449</td>\n      <td>0.38</td>\n      <td>0.09</td>\n      <td>0.09</td>\n      <td>1.32</td>\n      <td>1.32</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>2118</td>\n      <td>2118</td>\n      <td>1670</td>\n      <td>1670</td>\n      <td>23383</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Inferred</td>\n      <td>Inferred</td>\n      <td>11489</td>\n      <td>11489</td>\n      <td>11489</td>\n      <td>0.19</td>\n      <td>0.05</td>\n      <td>0.05</td>\n      <td>0.86</td>\n      <td>0.86</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>21</td>\n      <td>21</td>\n      <td>20</td>\n      <td>20</td>\n      <td>316</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>La Espanola</td>\n      <td>La Espanola</td>\n      <td>Measured</td>\n      <td>Measured</td>\n      <td>64297</td>\n      <td>64297</td>\n      <td>64297</td>\n      <td>0.38</td>\n      <td>0.08</td>\n      <td>0.08</td>\n      <td>0.33</td>\n      <td>0.33</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>242</td>\n      <td>242</td>\n      <td>161</td>\n      <td>161</td>\n      <td>684</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Indicated</td>\n      <td>Indicated</td>\n      <td>97599</td>\n      <td>97599</td>\n      <td>97599</td>\n      <td>0.31</td>\n      <td>0.06</td>\n      <td>0.06</td>\n      <td>0.31</td>\n      <td>0.31</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>305</td>\n      <td>305</td>\n      <td>182</td>\n      <td>182</td>\n      <td>960</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>M&amp;I</td>\n      <td>M&amp;I</td>\n      <td>161896</td>\n      <td>161896</td>\n      <td>161896</td>\n      <td>0.34</td>\n      <td>0.07</td>\n      <td>0.07</td>\n      <td>0.32</td>\n      <td>0.32</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>548</td>\n      <td>548</td>\n      <td>343</td>\n      <td>343</td>\n      <td>1644</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Inferred</td>\n      <td>Inferred</td>\n      <td>43677</td>\n      <td>43677</td>\n      <td>43677</td>\n      <td>0.28</td>\n      <td>0.05</td>\n      <td>0.05</td>\n      <td>0.25</td>\n      <td>0.25</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>122</td>\n      <td>122</td>\n      <td>66</td>\n      <td>66</td>\n      <td>355</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Underground</td>\n      <td>Underground</td>\n      <td>Measured</td>\n      <td>Measured</td>\n      <td>192402</td>\n      <td>192402</td>\n      <td>192402</td>\n      <td>0.86</td>\n      <td>0.20</td>\n      <td>0.20</td>\n      <td>3.57</td>\n      <td>3.57</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>1655</td>\n      <td>1655</td>\n      <td>1250</td>\n      <td>1250</td>\n      <td>22090</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Indicated</td>\n      <td>Indicated</td>\n      <td>259416</td>\n      <td>259416</td>\n      <td>259416</td>\n      <td>0.77</td>\n      <td>0.17</td>\n      <td>0.17</td>\n      <td>3.14</td>\n      <td>3.14</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>2000</td>\n      <td>2000</td>\n      <td>1418</td>\n      <td>1418</td>\n      <td>26189</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>M&amp;I</td>\n      <td>M&amp;I</td>\n      <td>451818</td>\n      <td>451818</td>\n      <td>451818</td>\n      <td>0.81</td>\n      <td>0.18</td>\n      <td>0.18</td>\n      <td>3.32</td>\n      <td>3.32</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>3655</td>\n      <td>3655</td>\n      <td>2667</td>\n      <td>2667</td>\n      <td>48279</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Inferred</td>\n      <td>Inferred</td>\n      <td>48782</td>\n      <td>48782</td>\n      <td>48782</td>\n      <td>0.72</td>\n      <td>0.15</td>\n      <td>0.15</td>\n      <td>2.01</td>\n      <td>2.01</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>349</td>\n      <td>349</td>\n      <td>234</td>\n      <td>234</td>\n      <td>3156</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Stockpile</td>\n      <td>Stockpile</td>\n      <td>Measured</td>\n      <td>Measured</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Indicated</td>\n      <td>Indicated</td>\n      <td>86187</td>\n      <td>86187</td>\n      <td>86187</td>\n      <td>0.29</td>\n      <td>0.09</td>\n      <td>0.09</td>\n      <td>1.20</td>\n      <td>1.20</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>246</td>\n      <td>246</td>\n      <td>238</td>\n      <td>238</td>\n      <td>3325</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>M&amp;I</td>\n      <td>M&amp;I</td>\n      <td>86187</td>\n      <td>86187</td>\n      <td>86187</td>\n      <td>0.29</td>\n      <td>0.09</td>\n      <td>0.09</td>\n      <td>1.20</td>\n      <td>1.20</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>246</td>\n      <td>246</td>\n      <td>238</td>\n      <td>238</td>\n      <td>3325</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Inferred</td>\n      <td>Inferred</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Ojos del Salado</td>\n      <td>Ojos del Salado</td>\n      <td>Measured</td>\n      <td>Measured</td>\n      <td>51494</td>\n      <td>51494</td>\n      <td>51494</td>\n      <td>0.94</td>\n      <td>0.22</td>\n      <td>0.22</td>\n      <td>1.96</td>\n      <td>1.96</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>484</td>\n      <td>484</td>\n      <td>364</td>\n      <td>364</td>\n      <td>3245</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>Underground</td>\n      <td>Underground</td>\n      <td>Indicated</td>\n      <td>Indicated</td>\n      <td>53888</td>\n      <td>53888</td>\n      <td>53888</td>\n      <td>0.83</td>\n      <td>0.18</td>\n      <td>0.18</td>\n      <td>1.96</td>\n      <td>1.96</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>448</td>\n      <td>448</td>\n      <td>315</td>\n      <td>315</td>\n      <td>3401</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>M&amp;I</td>\n      <td>M&amp;I</td>\n      <td>105382</td>\n      <td>105382</td>\n      <td>105382</td>\n      <td>0.88</td>\n      <td>0.20</td>\n      <td>0.20</td>\n      <td>1.96</td>\n      <td>1.96</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>932</td>\n      <td>932</td>\n      <td>680</td>\n      <td>680</td>\n      <td>6646</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Inferred</td>\n      <td>Inferred</td>\n      <td>23963</td>\n      <td>23963</td>\n      <td>23963</td>\n      <td>0.89</td>\n      <td>0.18</td>\n      <td>0.18</td>\n      <td>2.48</td>\n      <td>2.48</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>213</td>\n      <td>213</td>\n      <td>142</td>\n      <td>142</td>\n      <td>1908</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Measured</td>\n      <td>Measured</td>\n      <td>795303</td>\n      <td>795303</td>\n      <td>795303</td>\n      <td>0.54</td>\n      <td>0.13</td>\n      <td>0.13</td>\n      <td>1.85</td>\n      <td>1.85</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>4329</td>\n      <td>4329</td>\n      <td>3294</td>\n      <td>3294</td>\n      <td>47255</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>Candelaria</td>\n      <td>Candelaria</td>\n      <td>Indicated</td>\n      <td>Indicated</td>\n      <td>562429</td>\n      <td>562429</td>\n      <td>562429</td>\n      <td>0.56</td>\n      <td>0.13</td>\n      <td>0.13</td>\n      <td>1.99</td>\n      <td>1.99</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>3170</td>\n      <td>3170</td>\n      <td>2305</td>\n      <td>2305</td>\n      <td>36022</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>Total</td>\n      <td>Total</td>\n      <td>M&amp;I</td>\n      <td>M&amp;I</td>\n      <td>1357732</td>\n      <td>1357732</td>\n      <td>1357732</td>\n      <td>0.55</td>\n      <td>0.13</td>\n      <td>0.13</td>\n      <td>1.91</td>\n      <td>1.91</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>7499</td>\n      <td>7499</td>\n      <td>5599</td>\n      <td>5599</td>\n      <td>83277</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Inferred</td>\n      <td>Inferred</td>\n      <td>127911</td>\n      <td>127911</td>\n      <td>127911</td>\n      <td>0.55</td>\n      <td>0.11</td>\n      <td>0.11</td>\n      <td>1.39</td>\n      <td>1.39</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>705</td>\n      <td>705</td>\n      <td>461</td>\n      <td>461</td>\n      <td>5735</td>\n      <td>-</td>\n      <td>80\xa0%</td>\n      <td>80\xa0%</td>\n    </tr>\n    <tr>\n      <th>27</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>Caserones</td>\n      <td>Caserones</td>\n      <td>Measured</td>\n      <td>Measured</td>\n      <td>357020</td>\n      <td>357020</td>\n      <td>357020</td>\n      <td>0.34</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>102</td>\n      <td>102</td>\n      <td>102</td>\n      <td>NaN</td>\n      <td>1196</td>\n      <td>1196</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>36</td>\n      <td>70\xa0%</td>\n      <td>70\xa0%</td>\n    </tr>\n    <tr>\n      <th>29</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Indicated</td>\n      <td>Indicated</td>\n      <td>938920</td>\n      <td>938920</td>\n      <td>938920</td>\n      <td>0.26</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>89</td>\n      <td>89</td>\n      <td>89</td>\n      <td>NaN</td>\n      <td>2404</td>\n      <td>2404</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>84</td>\n      <td>70\xa0%</td>\n      <td>70\xa0%</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>M&amp;I</td>\n      <td>M&amp;I</td>\n      <td>1295940</td>\n      <td>1295940</td>\n      <td>1295940</td>\n      <td>0.28</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>93</td>\n      <td>93</td>\n      <td>93</td>\n      <td>NaN</td>\n      <td>3600</td>\n      <td>3600</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>120</td>\n      <td>70\xa0%</td>\n      <td>70\xa0%</td>\n    </tr>\n    <tr>\n      <th>31</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Inferred</td>\n      <td>Inferred</td>\n      <td>74766</td>\n      <td>74766</td>\n      <td>74766</td>\n      <td>0.20</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>53</td>\n      <td>53</td>\n      <td>53</td>\n      <td>NaN</td>\n      <td>147</td>\n      <td>147</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>4</td>\n      <td>70\xa0%</td>\n      <td>70\xa0%</td>\n    </tr>\n    <tr>\n      <th>32</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>33</th>\n      <td>Chapada</td>\n      <td>Chapada</td>\n      <td>Measured</td>\n      <td>Measured</td>\n      <td>407226</td>\n      <td>407226</td>\n      <td>407226</td>\n      <td>0.25</td>\n      <td>0.13</td>\n      <td>0.13</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>NaN</td>\n      <td>1026</td>\n      <td>1026</td>\n      <td>1702</td>\n      <td>1702</td>\n      <td>-</td>\n      <td>-</td>\n      <td>100\xa0%</td>\n      <td>100\xa0%</td>\n    </tr>\n    <tr>\n      <th>34</th>\n      <td>Open Pit</td>\n      <td>Open Pit</td>\n      <td>Indicated</td>\n      <td>Indicated</td>\n      <td>457264</td>\n      <td>457264</td>\n      <td>457264</td>\n      <td>0.21</td>\n      <td>0.11</td>\n      <td>0.11</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n

In [ ]:
import importlib
from project_name_tagger import train_ner
importlib.reload(train_ner)
from project_name_tagger.train_ner import load_data


data = load_data('data.csv')

In [11]:
import pickle

with open("ner_train_data.pkl", 'wb') as f:
    pickle.dump(data, f)

In [1]:
import importlib
from project_name_tagger import train_ner
importlib.reload(train_ner)
from project_name_tagger.train_ner import train_project_ner_sm
import pickle
import spacy
spacy.require_cpu()

with open("ner_train_data.pkl", 'rb') as f:
    data = pickle.load(f)

model = train_project_ner_sm(data)

Train size: 4264, Dev size: 1066

/home/ravi/work/mining/project/.venvgpu/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/ravi/work/mining/project/.venvgpu/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

Iter 1/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(1543266.2)}

/home/ravi/work/mining/project/.venvgpu/lib/python3.10/site-packages/spacy/pipeline/attributeruler.py:137: UserWarning: [W036] The component 'matcher' does not have any patterns defined.
  matches = self.matcher(doc, allow_missing=True, as_spans=False)
/home/ravi/work/mining/project/.venvgpu/lib/python3.10/site-packages/spacy/pipeline/lemmatizer.py:188: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)

Validation (dev) score at epoch 1: 0.0 F-score
Iter 2/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(77860.07)}
Validation (dev) score at epoch 2: 0.0 F-score
Iter 3/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(73146.45)}
Validation (dev) score at epoch 3: 0.0 F-score
Iter 4/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(70974.28)}
Validation (dev) score at epoch 4: 0.0 F-score
Iter 5/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(67928.76)}
Validation (dev) score at epoch 5: 0.0009432182607055273 F-score
Iter 6/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(66515.96)}
Validation (dev) score at epoch 6: 0.019097061277463613 F-score
Iter 7/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(64710.176)}
Validation (dev) score at epoch 7: 0.05141388174807198 F-score
Iter 8/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(63679.875)}
Validation (dev) score at epoch 8: 0.08413098236775818 F-score
Iter 9/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(63365.227)}
Validation (dev) score at epoch 9: 0.08431902669820886 F-score
Iter 10/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(62071.355)}
Validation (dev) score at epoch 10: 0.08549747048903879 F-score
Iter 11/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(61425.77)}
Validation (dev) score at epoch 11: 0.07245503829274588 F-score
Iter 12/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(60468.445)}
Validation (dev) score at epoch 12: 0.08367917337172864 F-score
Iter 13/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(59835.418)}
Validation (dev) score at epoch 13: 0.13179012345679014 F-score
New best model saved with F-score: 0.13179012345679014
Iter 14/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(59449.95)}
Validation (dev) score at epoch 14: 0.09411176813525442 F-score
Iter 15/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(58765.773)}
Validation (dev) score at epoch 15: 0.11821875248944476 F-score
Iter 16/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(58086.977)}
Validation (dev) score at epoch 16: 0.1332507931594831 F-score
New best model saved with F-score: 0.1332507931594831
Iter 17/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(58165.04)}
Validation (dev) score at epoch 17: 0.1272727272727273 F-score
Iter 18/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(57247.91)}
Validation (dev) score at epoch 18: 0.14996254681647941 F-score
New best model saved with F-score: 0.14996254681647941
Iter 19/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(57549.453)}
Validation (dev) score at epoch 19: 0.14236824093086925 F-score
Iter 20/20 Losses: {'tok2vec': 0.0, 'tagger': 0.0, 'parser': 0.0, 'ner': np.float32(56760.133)}
Validation (dev) score at epoch 20: 0.15562130177514794 F-score
New best model saved with F-score: 0.15562130177514794

In [ ]:
# import spacy
nlp = spacy.load("model_project_only")

In [1]:
from html_processor import get_article

try:
    with open("articles/July202508c9439.html", "r") as file:
        title, provider, published_date, body = get_article(
            file.read(), redact_tables=True, convert_to_text=True
        )
except:
    pass
text = f"TITLE: {title}, PROVIDER: {provider}, PUBLISHED_DATE: {published_date}, BODY: {body}"
doc = nlp(text)
doc.ents

NameError: name 'nlp' is not defined

In [45]:
body = f"""SilverRock Mining Ltd. has released an updated mineral resource estimate for its flagship Eagle Ridge Project, located in the heart of the Iron Valley mining district. The new estimate, prepared by independent consultants, highlights a substantial increase in both indicated and inferred resources.

According to the report, the Eagle Ridge deposit now contains an estimated 2.5 million ounces of gold equivalent in the indicated category and an additional 1.1 million ounces in the inferred category. This marks a 30% increase from the previous estimate released last year.

“We are extremely encouraged by these results,” said SilverRock CEO, Maria Thompson. “The updated resource estimate confirms Eagle Ridge as one of the most promising undeveloped gold projects in the region. Our ongoing drilling program continues to intersect high-grade mineralization, and we anticipate further growth in the resource base.”

The resource estimate is based on over 120,000 meters of drilling completed to date. The company plans to continue exploration at Eagle Ridge, with a focus on expanding the high-grade zones and testing new targets within the 15,000-hectare property.

SilverRock Mining also holds interests in the nearby Granite Peak and Willow Creek projectskj, both of which are undergoing early-stage exploration.

The company will host a conference call with investors and analysts next week to discuss the results and outline next steps for the Eagle Ridge Project.

"""
text = f"TITLE: {""}, PROVIDER: {""}, PUBLISHED_DATE: {""}, BODY: {body}"

In [46]:
doc = nlp(text)
doc.ents

(Eagle Ridge Project,
 Iron Valley,
 Eagle Ridge deposit,
 Eagle Ridge,
 Eagle Ridge Project)

In [1]:
from project_name_tagger.train_ner import make_spacy_dataset

dataset = make_spacy_dataset("data.csv")

  0%|          | 0/8000 [00:00<?, ?it/s]

In [5]:
import importlib
from project_name_tagger import train_ner
importlib.reload(train_ner)

In [11]:
from project_name_tagger.train_ner import to_jsonl

dataset = [x for x in dataset if x[0] != '']

In [29]:
import spacy
from spacy.tokens import DocBin

def to_spacy(data, out):
    nlp = spacy.blank("en")
    doc_bin = DocBin()
    
    for text, entities in data:
        doc = nlp.make_doc(text)
        ents = []
        for start, end, label in entities:
            span = doc.char_span(start, end, label=label)
            if span is not None:
                ents.append(span)
        doc.ents = ents
        doc_bin.add(doc)
    
    doc_bin.to_disk(out)

In [51]:
with_p = [s for s in dataset if len(s[1]) > 0]
without_p = [s for s in dataset if len(s[1]) == 0]

In [52]:
random.shuffle(without_p)

In [53]:
balanced = with_p + without_p[:len(with_p)]

In [54]:
import random
dev_ratio = 0.2
random.shuffle(balanced)
split = int(len(balanced) * (1 - dev_ratio))
train_data = balanced[:split]
dev_data = balanced[split:]

to_jsonl(train_data, "project_name_tagger/train.jsonl")
to_jsonl(dev_data, "project_name_tagger/dev.jsonl")

In [57]:
to_spacy(train_data, 'project_name_tagger/train.spacy')

In [59]:
balanced

[('(5)\xa0 \xa0\xa0Mineral Reserves may be subject to legal, political, environmental and other risks and uncertainties',
  []),
 ('Early warning reports in respect of the foregoing will be filed by Agnico Eagle in accordance with applicable securities laws',
  [(67, 79, 'PROJECT')]),
 ('support the mining sector;', []),
 ('Canada Nickel provides investors with leverage to nickel in low political risk jurisdictions',
  [(0, 13, 'PROJECT')]),
 ('("RNR"), owner of the Aguablanca Ni-Cu Project in Spain, has entered into an agreement with SCP Resource Finance LP and ECM Capital Advisors Ltd',
  [(2, 5, 'PROJECT')]),
 ('Nuclear Fuels logo (CNW Group/Nuclear Fuels Inc.)', [(20, 48, 'PROJECT')]),
 ('While Decisive and its subsidiaries will be impacted if significant long-term blanket tariffs are imposed on Canadian goods with respect to its U.S',
  [(6, 14, 'PROJECT')]),
 ('LUCA ACHIEVES TARGETED THROUGHPUT RATES AT CAMPO MORADO AND TAHUEHUTO MINES',
  [(43, 55, 'PROJECT')]),
 ('SOURCE Clifton Mining Company', [(7, 29, 'PROJECT')]),
 ('Although no significant high-grade interval was intercepted, WCCD-0016 returned 0.25 g/t non-oxide Au over.213.8m.with pervasive alteration, hydrothermal brecciation, and visible Quartz veins (1-20 centimeters ("cm"))',
  []),
 ('Roth holds a Ph.D', []),
 ('Cobra Zone.The Cobra Zone is defined by a multi-element soil anomaly and is situated along strike, south of the Rattler Zone anomaly, within Pogonip Group carbonate sediments',
  [(0, 10, 'PROJECT'), (15, 25, 'PROJECT'), (112, 124, 'PROJECT')]),
 ('An additional.4,194 m.has been drilled in six holes at the Buzz Zone and North Zone targets this year in an effort to demonstrate growth opportunities for two priority open-ended resource expansion targets at the Duparquet Project',
  [(213, 230, 'PROJECT')]),
 ('Notable conversion drilling results at Fruta del.Norte South.("FDNS") confirmed the deposit\'s continuity and identified additional mineralized zones',
  [(63, 66, 'PROJECT')]),
 ('CUPANI METALS CLOSES THIRD TRANCHE OF PRIVATE PLACEMENT FOR TOTAL FINANCING OF $4.5M\n\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\tFrançais',
  [(0, 6, 'PROJECT')]),
 ('SOURCE Century Lithium Corp', [(15, 22, 'PROJECT')]),
 ('Denarius Metals also provided an update today on its capital structure',
  []),
 ('forward-looking', []),
 ('Generally, forward-looking information can be identified by the use of forward-looking terminology such as "potential," "we believe," or variations of such words and phrases or statements that certain actions, events or results "will" occur',
  []),
 ('MONTREAL.,.April 3, 2025./CNW/ - Velan Inc', [(33, 38, 'PROJECT')]),
 ('Ms', []),
 ('The entities in which TotalEnergies SE directly or indirectly owns a shareholding are separate legal entities',
  [(22, 35, 'PROJECT')]),
 ('Table 1 presents the new underground resource estimate for the B26 deposit, and Table 2 presents the current metal content within the updated B26 resource estimate',
  [(63, 66, 'PROJECT'), (142, 145, 'PROJECT')]),
 ('Boliviano Exchange Rate Update', []),
 ('The Plata Latina Meeting will be held on.October 16, 2025.at.9:30 a.m',
  [(4, 16, 'PROJECT')]),
 ("A report published today by the Canadian Climate Institute,.Critical Path: Securing Canada's place in the global critical minerals race., finds that investment in these six priority critical minerals in.Canada.would have to grow substantially to keep pace with domestic and global demand",
  []),
 ('About Fokus.Fokus Mining Corporation is a mineral resource company focused on acquiring and exploring precious metal deposits in.Quebec, Canada., particularly in the Abitibi region, 20 km West of.Rouyn-Noranda., with its Galloway Project',
  [(12, 36, 'PROJECT'), (221, 237, 'PROJECT')]),
 ('Although management of the Company believes that the assumptions made and the expectations represented by such statements or information are reasonable, there can be no assurance that forward-looking statements or information herein will prove to be accurate',
  []),
 ('The Camino Rojo Oxide Mine produced 43,788 ounces and sold 38,265 ounces of gold during the third quarter 2024',
  [(4, 15, 'PROJECT')]),
 ('"Our new brand represents both where Compass Mining came from and where we are headed," said.Paul Gosker., CEO of Compass Mining',
  [(37, 51, 'PROJECT'), (114, 128, 'PROJECT')]),
 ('MONTREAL.,.Feb', [(0, 8, 'PROJECT')]),
 ('As of.January 1, 2025., enCore is reporting all mineral resources in accordance with Item 1302 of S-K 1300 in addition to Canadian National Instrument 43-101 ("NI 43-101")',
  []),
 ('SOURCE Argenta Silver Corp', []),
 ('Lundin Mining Announces Declaration of Regular Dividend', []),
 ('Storjuktan UAV Magnetic Geophysical Survey.FNM has commenced its unmanned aerial vehicle (UAV) magnetic geophysical survey over the entire 25,000 hectares ("ha") of the Storjuktan Project area',
  [(0, 10, 'PROJECT'), (169, 179, 'PROJECT')]),
 ("Glencore's successful credit bid concludes the Issuer's court-approved sale and investment solicitation process",
  []),
 ('Since then, and with nothing to show for it, the Board has squandered $2M of that valuable resource in just two months',
  []),
 ("Visitors will see Descon's proprietary integration software in action and learn how our technologies can enhance their packaging operations",
  []),
 ('We are grateful to these stakeholders for their efforts to improve conditions',
  []),
 ('Sigma Lithium Corporation.(NASDAQ: SGML), a leading global lithium producer, ended 2024 by announcing it had.exceeded its Q4 2024 targets.with 75,000 tonnes of quintuple zero green lithium produced, and being positioned to surpass 270,000 tonnes in 2025',
  [(0, 25, 'PROJECT')]),
 ("The 100%-owned, Galloway Project hosts a NI 43-101 inferred mineral resource of 1.42 million ounces of gold (41,195,000 tonnes grading 1.07 g/t Au) at a gold price of US$1,750 per ounce, as disclosed in the Company's March 23, 2023 press release",
  [(16, 32, 'PROJECT')]),
 ('Nio-Metals and/or one or more of its affiliates may, depending on market and other conditions, increase or decrease its beneficial ownership of Common Shares or other securities of Nio Strategic whether in the open market, by privately negotiated agreement or otherwise',
  [(181, 194, 'PROJECT'), (0, 10, 'PROJECT')]),
 ('About the Plomosas Project.The Plomosas Project, including the recent high-grade silver discovery in the San Marcial SE Area, is progressing in 2025 as an emerging high-grade silver district located in southern.Sinaloa, Mexico',
  [(10, 26, 'PROJECT'), (31, 47, 'PROJECT')]),
 ('The shelf prospectus supplement, the corresponding base shelf prospectus and any amendment to the documents are accessible through SEDAR+',
  []),
 ('In 2015, Mr', []),
 ('These forward-looking statements are made as of the date of this news release',
  []),
 ('(CNW Group/Omineca Mining and Metals Ltd.)', [(11, 41, 'PROJECT')]),
 ('The Company owns a 22.1% interest in Rio Narcea Recursos, S.L', []),
 ("Frank Giustra.may be obtained from the Company's CFO & Corporate Secretary,.Gerrie van der Westhuizen.(+1 604-566-9080)",
  []),
 ('MONTREAL.,.June 17, 2025./CNW/ - Torngat Metals Ltd., a.Quebec.-based rare earth development company, is pleased to announce the signing of a CA$110 million bridge loan facility agreement with Export Development Canada ("EDC"), and a loan commitment of up to CA$55 million from the Canada Infrastructure Bank ("CIB"),\xa0to support the next phase of its Strange Lake project',
  [(351, 363, 'PROJECT'), (33, 52, 'PROJECT')]),
 ('(TSXV:.BRVO.) (OTCQX: BRVMF),\xa0(".Bravo." or the ".Company.") is pleased to announce that it has filed an independent technical report (the ".Technical Report.") prepared in accordance with National Instrument 43-101 -.Standards of Disclosure for Mineral Projects.(".NI 43-101.")\xa0in respect of the updated mineral resource estimate for the Company\'s 100% owned Luanga palladium + platinum + rhodium + gold + nickel deposit (".Luanga deposit." or ".Luanga PGM+Au+Ni deposit."), located in the Carajás Mineral Province, state of Pará,.Brazil',
  []),
 ('Concurrent with the Horizon Transaction, Royal Gold has entered into a definitive arrangement agreement with Sandstorm, pursuant to which Royal Gold will acquire all of the issued and outstanding common shares of Sandstorm in an all-share transaction valued at approximately.US$3',
  [(41, 51, 'PROJECT'),
   (138, 148, 'PROJECT'),
   (109, 118, 'PROJECT'),
   (213, 222, 'PROJECT')]),
 ('As part of its pre-feasibility study (PFS), Freegold has engaged a power consultant to evaluate the local power infrastructure and investigate alternative energy sources to enhance long-term sustainability',
  [(44, 52, 'PROJECT')]),
 ('Chalmers continued: "And, of course, we also have the Toliara Project in.Madagascar., which is a world-class heavy mineral sands and rare earth development project, currently targeted to come on line as early as 2028, subject to receipt of.Madagascar.government approvals and acceptable stability arrangements, and our Bahia Project in.Brazil., which is a heavy mineral sands and REE exploration and permitting project targeted to come on line in 2029',
  [(319, 332, 'PROJECT'), (54, 69, 'PROJECT')]),
 ('The inaugural exploration program on the adjoining Pheno Claims will also take place during this program as the Company looks to capitalize on a unique critical metal opportunity in Golden Triangle',
  [(51, 63, 'PROJECT')]),
 ('ABOUT SANDSTORM GOLD ROYALTIES', []),
 ('Forward-Looking Statements', []),
 ('SOURCE Freeman Gold Corp', [(7, 19, 'PROJECT')]),
 ('Daxter took the helm as our CEO just over one year ago to this date', []),
 ('The Nemo Project comprises 321 exploration claims (the ".Claims.") that interlock with CUPANI\'s existing claims in the Extensions Zone',
  [(119, 134, 'PROJECT'), (4, 16, 'PROJECT')]),
 ("Geol., Vice President, Exploration of Kootenay Silver, is the Company's nominated Qualified Person pursuant to National Instrument 43-101, Standards for Disclosure for Mineral Projects, has reviewed the scientific and technical information disclosed in this news release",
  []),
 ('Additional factors that could cause results to differ materially from those described above can be found in SilverCrest\'s management information circular in connection with the Meeting and SilverCrest\'s annual information form for the year ended.December 31, 2023., which are filed with the SEC and on SEDAR+ and available from SilverCrest\'s website at.www.silvercrestmetals.com.under the "Investors" tab, and in other documents SilverCrest files with the SEC or on SEDAR+',
  []),
 ("The net proceeds of the Offering shall be used to fund exploration activities at the Company's Cruz de Plata gold-silver project and for working capital and general corporate purposes, as is more fully described in the Offering Document (as defined herein)",
  [(95, 108, 'PROJECT')]),
 ('(".Alpayana.") assures Sierra shareholders that, provided the statutory minimum tender condition of 50% is satisfied as of the expiry of the initial deposit period, Alpayana intends to waive all remaining conditions of its offer (the ".Revised Offer.") and to take-up and pay for all common shares of Sierra Metals Inc',
  [(3, 11, 'PROJECT'),
   (165, 173, 'PROJECT'),
   (23, 29, 'PROJECT'),
   (301, 307, 'PROJECT')]),
 ('These diamondiferous kimberlites are located in close proximity to established infrastructure, including paved highways and the electrical power grid, which provide significant advantages for future mine development',
  []),
 ("Further to Trilogy's December 17, 2025, news release announcing the 2026 program and budget for Ambler Metals, Ambler Metals has also begun recruiting key management roles to drive project execution",
  [(96, 109, 'PROJECT'), (111, 124, 'PROJECT')]),
 ('SOURCE Saskatchewan Research Council.For more information, contact: Allison Collins, External Relations, Saskatchewan Research Council, Phone: 306-385-4208, Email:.[email\xa0protected]',
  [(7, 19, 'PROJECT'), (105, 117, 'PROJECT')]),
 ("This information is based on management's reasonable assumptions and beliefs in light of the information currently available to us and are made as of the date of this press release",
  []),
 ('SOURCE Paladin Energy Ltd.For further information: Investor Relations - Head Office: Paula Raffo, Paladin Investor Relations, T: +61 8 9423 8100, E:.[email\xa0protected].; Canada: Bob Hemmerling, Paladin Investor Relations, T: +1 250-868-8140, E:.[email\xa0protected].; Media, Head Office: Anthony Hasluck, Paladin Corporate Affairs, T: +61 438 522 194, E:.[email\xa0protected].; Canada: Ian Hamilton, Partner, FGS Longview, T: +1 905-399-6591, E:.[email\xa0protected]',
  [(7, 14, 'PROJECT'),
   (98, 105, 'PROJECT'),
   (193, 200, 'PROJECT'),
   (301, 308, 'PROJECT')]),
 ('Cautionary Note Regarding Forward-Looking Statements', []),
 ('("Coast Copper" or the "Company").(TSXV:.COCO.)\xa0is pleased to announce the results of its second phase work program on its 100% owned Knob Hill NW property as well as the acquisition of the Hanson property in northwestern.British Columbia.(".BC."),.Canada',
  [(190, 205, 'PROJECT')]),
 ('"We see this low-risk oil and gas venture as complimentary to our lithium business',
  []),
 ("Additionally, the issuance is exempt from the formal valuation and minority approval requirement in Section 5.6 of MI 61-101 in reliance on Section 5.7(1)(a) of MI 61-101 as neither the fair market value of the subject matter of, nor the fair market value of the consideration for, the shares exceeds 25% of Granite Creek's market capitalization",
  []),
 ('Callinex started the year by completing a magnetotelluric geophysical survey ("MT") over the Descendent and other key areas of the Pine Bay Project area',
  [(131, 147, 'PROJECT')]),
 ('SOURCE Karnalyte Resources Inc', []),
 ('Channel and Chip sample results in the\xa0Jimenez target from the Target Generation program previously reported and referred to in Figure 1 (see News Releases dated May 9, 2022, July 05, 2022, January 03, 2023\xa0and September 11, 2024)',
  [(39, 46, 'PROJECT')]),
 ('Facility C US$ Tranche Loans have an annual interest rate of SOFR plus 13%, capped at 18%, with all interest and principal being due at the end of the 2-year Facility C term',
  []),
 ('To join the conference call without operator assistance, you may register your phone number.here.30 minutes prior to the scheduled start of the call to receive an instant automated call back',
  []),
 ('In late July the Company repaid an additional.$40 million.in principal under the Stand-by Facility of the PLF"',
  [(81, 98, 'PROJECT')]),
 ('1, 2025./CNW/ -.GR Silver Mining Ltd', [(16, 36, 'PROJECT')]),
 ("The feedstock will be sourced from post-industrial and end-of-life magnets, marking a major milestone in both companies' long-standing efforts to create sustainable, domestic supply chains",
  []),
 ('Deliver test silicon and ready-made designs for Quantum Compute in Memory (QCIM), using a highly-efficient chip design technique called "compute-in-memory", first pioneered by the AI revolution, and used by BTQ to accelerate quantum encryption',
  [(75, 79, 'PROJECT')]),
 ("To this effect, Blue Sky reports that.Guillermo Pensado.has agreed to serve as the Company's Technical Consultant for the joint venture and will relinquish his role as Vice President, Exploration and Development",
  []),
 ('As required by the TSXV, trading of the shares of Artrari on the TSXV under the trading symbol AOCC.P shall remain halted pending satisfaction of TSXV requirements and/or completion of the Transaction',
  [(50, 57, 'PROJECT')]),
 ('To the maximum extent permitted by law or any relevant listing rules of the ASX/TSX, Paladin and Fission and their respective related bodies corporate and affiliates and their respective directors, officers, employees, advisors, agents and intermediaries disclaim any obligation or undertaking to disseminate any updates or revisions to the information in this announcement to reflect any change in expectations in relation to any forward looking statements or any such change in events, conditions or circumstances on which any such statements were based',
  []),
 ('Longitudinal section A-A’ and intercepts (not true width) (CNW Group/Orvana Minerals Corp.)',
  [(69, 75, 'PROJECT')]),
 ('30, 2025./CNW/ -\xa0Aris Mining Corporation (Aris Mining or the Company) (TSX:.ARIS.) (NYSE-A:\xa0ARMN) announces the appointment of Brigitte Baptiste to its Board of Directors, effective immediately',
  [(17, 28, 'PROJECT'), (42, 53, 'PROJECT')]),
 ("The primary XRT analysis produced two very high-density and grade concentrates of 21.80 kg's and 6.10 kg's (Sample 24-037-A01P and 24-037-B01P) with.25.30% Cs₂O, 79 ppm Ta.,.0.50% Li₂O.and.25.60% Cs₂O, 51 ppm Ta.,.0.30% Li₂O",
  []),
 ('Forward-looking statements involve various risks and uncertainties', []),
 ('if video/audio/not yotube', []),
 ('Ovintiv Reports Third Quarter 2024 Financial and Operating Results (CNW Group/Ovintiv Inc.)',
  [(0, 7, 'PROJECT'), (78, 85, 'PROJECT')]),
 ("(URC) is the world's only uranium-focused royalty and streaming company and the only pure-play uranium listed company on the NASDAQ",
  []),
 ('Omineca Commences Lode Gold Drilling Program at Wingdam',
  [(48, 55, 'PROJECT')]),
 ("The goal of this initiative is to utilize DISA's EPA validated proprietary High-Pressure Slurry Ablation (HPSA) technology to safely reclaim and remediate multiple sites across GNEM's properties",
  [(177, 181, 'PROJECT')]),
 ('Diamond Drilling across La Verde expands the gold-rich major copper discovery in coastal Chile (CNW Group/Hot Chili Limited)',
  [(24, 32, 'PROJECT')]),
 ("Q4 marked TZ's first full quarter of commercial production, contributing 40,147 ounces to an annual production total of 63,566 ounces",
  []),
 ('Table 1: Summary of the Siver Hart Project Economic and Technical Parameters/Assumptions',
  []),
 ('To date, approximately 48.2% of the Warrants have been exercised, generating.C$77.0 million.(approximately.US$56 million.) in proceeds for the Company',
  []),
 ('Tesorito Gold Deposit (effective July 31, 2025).At an open-pit cut-off grade of 0.20 g/t Au:',
  []),
 ('".Orovalle - Q1 FY2025 Production Results', [(2, 10, 'PROJECT')]),
 ('One of several identified on the Moyie Anticline Project',
  [(33, 56, 'PROJECT')]),
 ('Election of Directors', []),
 ('The foregoing list of assumptions is not exhaustive', []),
 ('No assurance can be given that these expectations will prove to be correct and such forward-looking statements included in this news release should not be unduly relied upon',
  []),
 ("Rock Tech's vision is to supply the electric vehicle and battery industry with sustainable, locally produced lithium, targeting a 100% recycling rate",
  [(0, 9, 'PROJECT')]),
 ('Sadiola Mine:', [(0, 12, 'PROJECT')]),
 ('VANCOUVER, BC.,.Nov', []),
 ('CAUTIONARY DISCLAIMER - FORWARD-LOOKING STATEMENTS', []),
 ('Ventilation Fresh Air Rase (CNW Group/Foran Mining Corporation)',
  [(38, 62, 'PROJECT')]),
 ('Gneiss Energy acted as financial advisor on the strategic equity raise for Pumpkin Hollow and the Southwest Open Pit',
  [(98, 116, 'PROJECT')]),
 ('Dasa is a reality everyone can see', []),
 ('extensive induced polarization ("IP") geophysical surveys;', []),
 ("Copies of the Agreements will be filed under G1's SEDAR+ profile at.https://www.sedarplus.ca",
  []),
 ('Successfully onboarded Millennial Precious Metals Corp.\'s projects and facilities into Integra\'s environmental, social and governance ("ESG") disclosure frameworks',
  []),

In [58]:
to_spacy(dev_data, 'project_name_tagger/dev.spacy')

In [2]:
import spacy

nlp = spacy.load('project_name_tagger/trf_model/model-best/')

ValueError: [E002] Can't find factory for 'transformer' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: merge_noun_chunks, merge_entities, merge_subtokens, en.lemmatizer

In [3]:
!pip show spacy-transformers

WARNING: Package(s) not found: spacy-transformers